Repository ampproject/amp.dev, pull requests merged in 2018-08, with the labels that each got.

#1043 GDPR, including the Client ID
  assets/sass/_consent.scss
  assets/sass/_global.scss
  views/base.html
  views/partials/consent.html
  views/partials/head.html
Labels: P1: High

#1073 Create benefits@es.yaml
  translations/es/LC_MESSAGES/messages.po
Labels: Type: Localization

#1069 Improve KO translation for "reference".
  translations/ko/LC_MESSAGES/messages.po
Labels: Type: Localization

#1083 KO translation for AMP stories tutorial
  content/docs/design/visual_story@ko.md
Labels: Type: Localization

#1098 Make firebase logs available when deploy fails
  .travis.yml
  build_scripts/deploy.sh
Labels: Type: Site Infrastructure

#1100 Remove combined secure token from .travis.yml, and add them individually to Travis settings
  .travis.yml
  build_scripts/deploy.sh
Labels: Type: Site Infrastructure

#1093 Add KO translation for content/docs/design/visual_story/start_story.md.
  content/docs/design/visual_story/start_story@ko.md
Labels: Type: Localization

#1094 KO translation for visual_story/create_cover_page.md.
  content/docs/design/visual_story/create_cover_page@ko.md
Labels: Type: Localization

#1099 KO translation for visual_story/animating_elements.md.
  content/docs/design/visual_story/animating_elements@ko.md
Labels: Type: Localization

#1103 KO translation for visual_story/create_bookend.md.
  content/docs/design/visual_story/create_bookend@ko.md
Labels: Type: Localization

#1104 KO translations for validation.md and congratualtion.md.
  content/docs/design/visual_story/congratulations@ko.md
  content/docs/design/visual_story/validation@ko.md
Labels: Type: Localization
