Repository ampproject/amp.dev, pull requests merged in 2019-05, with the labels that each got.

#1981 Add amp-autocomplete component example usage.
  examples/source/1.components/amp-autocomplete.html
  examples/static/samples/img/trending.png
  examples/static/samples/json/amp-autocomplete-cities.json
  examples/static/samples/json/amp-autocomplete-countries.json
  examples/static/samples/json/amp-autocomplete-fruit.json
Labels: Category: Examples, P2: Medium, Type: New, cla: yes

#1993 Update combobox example with amp-autocomplete usage
  examples/source/interactivity-dynamic-content/ComboBox.html
Labels: Category: Examples, P2: Medium, Type: Update, cla: yes

#2006 updated maintenance to include paragraph filtering codes
  MAINTENANCE.md
Labels: Category: Documentation, cla: no

#2009 Toggle ampExperiment for amp-autocomplete examples
  examples/source/1.components/amp-autocomplete.html
  examples/source/interactivity-dynamic-content/ComboBox.html
Labels: Category: Examples, P1: High, Status: WIP, Type: Update, cla: yes

#2013 Add sample email used at IO talk
  examples/source/interactivity-dynamic-content/Conference_Survey_Email.html
  platform/config/go-links.yaml
Labels: cla: yes

#2012 Fix / update email examples
  examples/source/0.introduction/Hello_World_Email.html
  examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
  examples/source/interactivity-dynamic-content/Article_Bookmark_Email.html
  examples/source/interactivity-dynamic-content/Bookmark_Article_Email.html
  examples/source/interactivity-dynamic-content/Friend_Requests_Email.html
Labels: cla: yes

#2011 Added email filters for components not valid for email format
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
Labels: Category: Documentation, Type: Update, cla: yes

#2016 Shortlink for CORS documentation
  platform/config/go-links.yaml
Labels: cla: yes

#2018 add optimize amp shortlink
  platform/config/go-links.yaml
Labels: cla: no

#2015 Overhauled tools section
  frontend/scss/components/organisms/stage-tools.scss
  frontend/scss/components/organisms/tool-block.scss
  frontend/scss/components/templates/tools.scss
  frontend/templates/views/overview/tools.j2
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
  pages/shared/data/tools.yaml
  pages/static/img/tools/amp_for_wordpress.jpg
  pages/static/img/tools/insights.png
  pages/static/img/tools/makestories.jpg
  pages/static/img/tools/search_console.png
Labels: Category: Content, P0: Critical, Site: amp.dev, Type: Update, cla: yes

#2023 re-add boilerplate generator
  pages/shared/data/tools.yaml
  pages/static/img/docs/tools/ampboilerplate.png
  pages/static/img/docs/tools/ampexperiments.jpg
  pages/static/img/docs/tools/ampplayground.jpg
  pages/static/img/docs/tools/ampvalidator.jpg
  pages/static/img/docs/tools/visualstudiocode.jpg
Labels: cla: yes

#2020 Updated sizes attribute documentation
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes.md
Labels: cla: yes

#2024 🐛 Add missing boilerplate redirect.
  .github/ISSUE_TEMPLATE
  firebase.json
Labels: cla: no

#2026 🐛 Fix scroll issue on iOS
  frontend/scss/components/organisms/preview-pane.scss
Labels: cla: yes

#2027 ✨ Add amp-camp demo to Use Cases page.
  frontend/scss/components/organisms/fragment-slider-controls.scss
  frontend/scss/components/organisms/fragment-slider-texts.scss
  frontend/scss/components/templates/tools.scss
  frontend/scss/components/templates/use-cases.scss
  frontend/templates/views/partials/fragment-slider-controls.j2
  frontend/templates/views/partials/fragment-slider-images.j2
  frontend/templates/views/partials/fragment-slider-texts.j2
  pages/static/img/use-cases/amp-camp/amp-camp-01.jpg
  pages/static/img/use-cases/amp-camp/amp-camp-02.jpg
  pages/static/img/use-cases/amp-camp/amp-camp-03.jpg
  pages/static/img/use-cases/amp-camp/amp-camp-04.jpg
  pages/static/img/use-cases/amp-camp/amp-camp-05.jpg
  pages/static/img/use-cases/amp-camp/amp-camp-06.jpg
  pages/static/img/use-cases/amp-camp/amp-camp-07.jpg
  platform/lib/routers/pages.js
Labels: cla: yes

#2028 Feature/migrate translations
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.pot
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: Category: Localization, P1: High, Type: Update, cla: yes

#2038 Add anchor link
  pages/content/amp-dev/about/stories.html
Labels: cla: yes

#2036 adding Tealium
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md
Labels: cla: yes

#2041 Revised language for AMP Camp demo
  frontend/templates/views/partials/fragment-slider-texts.j2
Labels: Category: Content, P1: High, Type: Update, cla: yes

#2046 💄 update scrollbar in code snippets
  frontend/scss/components/molecules/code-snippet.scss
Labels: Category: UX, P1: High, Site: amp.dev, Type: Update, cla: yes

#2045 Update amp-by-example dependency
  package-lock.json
  package.json
Labels: cla: yes

#2035 🐛 Remove invalid path from Korean document
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/index@ko.md
Labels: cla: yes

#2042 🔗Add link to ad manager docs
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md
Labels: cla: yes

#2055 Fix some special characters in the es messages
  package-lock.json
  pages/translations/es/LC_MESSAGES/messages.po
Labels: Category: Localization, cla: yes

#2049 update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#2057 add optimized AMP test file
  pages/static/files/valid-optimized.amp.html
Labels: cla: yes

#2047 💄Update boilerplate generator theme
  boilerplate/build.js
  boilerplate/data/formats.json
  boilerplate/templates/index.html
  boilerplate/templates/styles/code-snippet.scss
  boilerplate/templates/styles/main.scss
  frontend/scss/components/molecules/format-toggle.scss
Labels: cla: yes

#2066 Perf various things around Grow.
  frontend/templates/layouts/default.j2
  frontend/templates/layouts/sitemap.xml
  frontend/templates/views/examples/preview.j2
  frontend/templates/views/partials/burger-menu.j2
  frontend/templates/views/partials/header.j2
  frontend/templates/views/partials/structured-data.j2
  pages/extensions/inline_text_assets/inline_text_assets.py
Labels: Category: Infrastructure, P2: Medium, Site: amp.dev, Type: Update, cla: yes

#2069 🐛 Fix path handling in SampleRenderer.
  examples/lib/SampleRenderer.js
Labels: Category: Functionality, P1: High, Site: amp.dev, Type: Bug, cla: yes

#2070 Support configured redirect links at amp.dev
  platform/config/amp-dev-redirects.yaml
  platform/config/go-links.yaml
  platform/lib/middleware/redirects.js
Labels: cla: yes

#2048 It is the last multipart that needs to end with double dashes
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-format.md
Labels: Category: Documentation, P1: High, Type: Update, cla: yes

#2063 Add tools widgets to About pages
  frontend/scss/components/organisms/tools-teaser.scss
  frontend/scss/components/templates/tools.scss
  frontend/scss/components/templates/what-is-amp.scss
  frontend/templates/views/partials/tools-teaser.j2
  frontend/templates/views/partials/tools-widget.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/documentation/tools.html
  pages/shared/data/tools.yaml
  pages/static/img/tools/gmail_playground.png
  pages/static/img/tools/google_amp_test.jpg
Labels: Category: Content, P1: High, Type: Update, cla: yes

#2074 🐛 Add missing getter for formats to MarkdownDocument
  platform/lib/pipeline/markdownDocument.js
Labels: Category: Functionality, P1: High, Type: Bug, cla: yes

#2075 🐛 Correctly read sample category metadata
  platform/lib/build/samplesBuilder.js
Labels: Category: Examples, P1: High, Type: Bug, cla: yes

#2067 Handler to serve existing playground js/css file if hash is not correct
  platform/lib/routers/resourceFallbackHandler.js
  playground/backend/index.js
Labels: Category: Functionality, Type: Update, cla: yes

#2078 🐛 fixed broken reference to amp-audio
  examples/source/multimedia-animations/Supported_media_types_in_AMP_Stories.html
Labels: Category: Examples, P2: Medium, Site: amp.dev, Type: Bug, cla: yes

#2079 Setup runtime logging endpoint
  examples/lib/SampleRenderer.js
  pages/content/amp-dev/message.html
  platform/config/environments/development.json
  platform/config/environments/production.json
  platform/config/environments/staging.json
  platform/lib/platform.js
  platform/lib/routers/runtimeLog.js
  platform/lib/runtime-log/formatter.js
  platform/lib/templates/index.js
Labels: cla: yes

#2081 🐛 Use correct URL scheme for component docs.
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
Labels: cla: yes

#2082 add log subdomain for local config
  platform/config/environments/local.json
Labels: cla: yes

#2086 remove intrinsic layout to renable removing the boilerplate
  frontend/templates/views/detail/docs-detail.j2
Labels: cla: yes

#2085 Updating roadshow cities
  frontend/scss/components/molecules/event.scss
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2087 Fix sample previews not performing SSR
  examples/lib/SampleRenderer.js
  platform/lib/platform.js
Labels: cla: yes

#2091 🐛 Fix sidebar navigation on paged_list page
  examples/source/interactivity-dynamic-content/Paged_List.html
Labels: Type: Bug, cla: yes

#2084 ♻️ Move Grow URL rewrite to dedicated extension
  pages/extensions/amp_dev/extension.py
  pages/extensions/url_beautifier/__init__.py
  pages/extensions/url_beautifier/url_beautifier.py
  platform/config/podspec.yaml
Labels: Category: Functionality, P2: Medium, Type: Bug, cla: yes

#2092 🍎 Set default state for rolling formats animation.
  frontend/scss/components/molecules/rolling-formats.scss
Labels: Category: UX, P1: High, Site: amp.dev, Type: Update, cla: yes

#2099 fixed some small nits on the animation documentation
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/introduction_to_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
Labels: cla: yes

#2097 Allow samples to specify author like articles
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/author.j2
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2103 🔧Update ampproject.org redirects to fix inline samples.
  firebase.json
Labels: Category: Infrastructure, P0: Critical, Type: Update, cla: no

#2106 ✨ Render markdown in roadmap items.
  frontend/scss/components/templates/roadmap.scss
  pages/content/amp-dev/community/roadmap.html
Labels: Category: UX, P2: Medium, Type: Update, cla: yes

#2050 Update product page add-to-cart API endpoint.
  examples/source/e-commerce/Product_Page.html
Labels: Category: Examples, P1: High, Type: Bug, cla: yes

#2107 Fix/ampbyexample references
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout.md
Labels: P1: High, Type: Bug, cla: yes

#2121 🐛 Fix resizable iframe example
  examples/source/1.components/amp-iframe.html
  examples/static/samples/files/resizable-iframe.html
Labels: Site: amp.dev, Type: Bug, cla: yes

#2109 Playground: extract title from URL
  examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
  examples/source/interactivity-dynamic-content/Article_Bookmark_Email.html
  playground/src/title-updater/base.js
Labels: cla: yes

#2022 Update signed-exchange.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: Category: Documentation, Type: Update, cla: yes

#2126 add site verification for gsuite
  pages/static/googlefc2a7cf70933ae03.html
  platform/lib/routers/static.js
Labels: cla: yes

#2128 updated wording per issue 2125
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
Labels: Category: Documentation, Type: Update, cla: yes

#2118 🎉Translate Guide and Tutorials into Korean
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/include_image@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/index@ko.md
Labels: Category: Localization, Language: KO, cla: yes

#2120 🎉 Improve Ko translation of Getting Started
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/prepare_for_discovery@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/presentation_layout@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/preview_and_validate@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/publish@ko.md
Labels: Category: Localization, Language: KO, cla: yes

#2132 fixed the t
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
Labels: cla: yes

#2135 Fix some broken example links
  examples/source/interactivity-dynamic-content/Autosuggest_form.html
  examples/source/interactivity-dynamic-content/Simple_Autosuggest.html
  examples/source/news-publishing/Recipe.html
  examples/static/samples/json/related_articles.json
  package-lock.json
Labels: cla: yes

#2134 ♻️ Migrate autosuggest API to amp.dev
  examples/api/autosuggest.js
  examples/source/interactivity-dynamic-content/Autosuggest_form.html
Labels: Category: Examples, P1: High, Site: amp.dev, Type: Bug, cla: yes

#2137 Clarify hosting requirements
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#2142 Link to prod-config.json
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
Labels: cla: yes

#2141 Enable valid optimized AMP
  package-lock.json
  package.json
  platform/lib/build/pageTransformer.js
  platform/lib/routers/packager.js
  platform/lib/routers/pages.js
Labels: cla: yes

#2140 Polish amp-iframe sample
  examples/source/1.components/amp-iframe.html
  examples/static/samples/files/amp-iframe.html
  examples/static/samples/files/resizable-iframe.html
Labels: cla: yes

#2143 👽 Adapt boilerplate generator build to new optimizer API
  boilerplate/build.js
Labels: cla: yes

#2151 Add missing size for hello world ad
  .travis.yml
  examples/source/0.introduction/AMPHTML_Ads_Hello_World.html
  gulpfile.js/build.js
Labels: cla: yes

#2152 🚑 Pass environment to sharded gulp pageTransform
  gulpfile.js/build.js
Labels: cla: yes

#2150 ✨ Add new show more button example
  examples/api/photo-stream.js
  examples/source/interactivity-dynamic-content/Show_More_Button.html
Labels: Category: Examples, Site: amp.dev, cla: yes

#2154 ✨ Lint YAML files.
  .travis.yml
  gulpfile.js/test.js
Labels: cla: yes

#2155 🐛 Build samples during development
  gulpfile.js/develop.js
Labels: cla: yes

#2156 Update amp-mustache import.
  examples/source/1.components/amp-recaptcha-input.html
Labels: cla: yes

#2108 ♻️ Migrate checkout backend API
  examples/source/e-commerce/Checkout_Flow/api.js
  examples/source/e-commerce/Checkout_Flow/index.html
Labels: Category: Examples, P1: High, Site: amp.dev, Type: Bug, cla: yes

#2158 🐛 Fix broken references and reenable Grow Reference Checker.
  .travis.yml
  gulpfile.js/test.js
  pages/content/amp-dev/documentation/courses/advanced-course/appendix.md
  pages/content/amp-dev/documentation/courses/beginning-course/appendix.md
  pages/content/amp-dev/documentation/courses/beginning-course/conclusions-and-whats-next.md
  pages/content/amp-dev/documentation/courses/beginning-course/finding-the-right-component.md
  pages/content/amp-dev/documentation/courses/beginning-course/our-first-amp-page.md
  pages/content/amp-dev/documentation/courses/beginning-course/thinking-in-components.md
  pages/content/amp-dev/documentation/courses/index.html
  pages/content/amp-dev/documentation/courses/intermediate-course/handling-user-interactions.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated@ko.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@zh_CN.md
  platform/lib/tools/growReferenceChecker.js
Labels: cla: yes

#2160 Fix bad city name
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2171 Add templates shortlink
  platform/config/go-links.yaml
Labels: cla: yes

#2167 ♻️ Migrate favorite button API to amp.dev
  examples/source/interactivity-dynamic-content/Favorite_Button/api.js
  examples/source/interactivity-dynamic-content/Favorite_Button/index.html
  package-lock.json
  package.json
Labels: Category: Examples, P1: High, Site: amp.dev, Type: Bug, cla: yes

#2174 Added ad integration clarification
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads.md
Labels: cla: yes

#2173 Tools: Add Sparkpost to email creation tools
  pages/shared/data/tools.yaml
  pages/static/img/tools/sparkpost.png
Labels: cla: yes

#2172 🐛 Correctly handle multiple sample builds
  gulpfile.js/build.js
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2177 add prod api key
  .prod.key.json.enc
  .travis.yml
Labels: cla: yes

#2170 Update with Origin Trial notes
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
Labels: cla: yes

#2176 Add ~/bin to path for grow exec
  gulpfile.js/build.js
  gulpfile.js/develop.js
  platform/lib/utils/grow.js
  platform/lib/utils/sh.js
Labels: cla: yes

#2185 🐛 Deploy shared pages
  gulpfile.js/build.js
Labels: cla: yes

#2179 Style and layout: Updated auto-layout table
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout.md
Labels: cla: yes

#2184 Restore dynamic importing of news/YT videos to show on homepage
  frontend/scss/components/organisms/news.scss
  gulpfile.js/build.js
  package-lock.json
  package.json
  pages/content/amp-dev/index.html
  pages/shared/data/blog.yaml
  platform/lib/pipeline/blogImporter.js
Labels: cla: yes

#2186 🐛 Improve DX for local environment
  README.md
  gulpfile.js/build.js
  gulpfile.js/develop.js
Labels: cla: yes

#2178 🐛 Update broken amp-consent example URLs
  examples/source/user-consent/Geolocation-based_Consent_Flow.html
Labels: Category: Examples, P1: High, Site: amp.dev, Type: Bug, cla: yes

#2183 ♻️ Migrate comment-section API to amp.dev
  examples/source/interactivity-dynamic-content/Comment_Section/api.js
  examples/source/interactivity-dynamic-content/Comment_Section/index.html
Labels: Category: Examples, P1: High, Site: amp.dev, Type: Bug, cla: yes

#2190 update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#2191 ♻️ Migrate rating API to amp.dev
  examples/source/interactivity-dynamic-content/Star_Rating/api.js
  examples/source/interactivity-dynamic-content/Star_Rating/index.html
Labels: Category: Examples, Site: amp.dev, cla: yes

#2193 Remove nested note
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
Labels: cla: yes

#2181 Log/fetch version
  integration-tests/Platform.spec.js
  integration-tests/helpers/startPlatform.js
  integration-tests/run.js
  integration-tests/support/jasmine.json
  jest.config.js
  package-lock.json
  package.json
  pages/content/amp-dev/message.html
  pages/static/files/log-messages-v011905140117570.json
  platform/lib/config.js
  platform/lib/routers/runtimeLog.js
  platform/lib/routers/runtimeLog.test.js
  platform/lib/runtime-log/HtmlFormatter.js
  platform/lib/runtime-log/HtmlFormatter.test.js
  platform/lib/runtime-log/LogProvider.js
  platform/lib/runtime-log/LogProvider.test.js
  platform/lib/templates/index.js
  platform/lib/tools/growReferenceChecker.js
  platform/lib/utils/project.js
  playground/spec/run.js
  playground/spec/support/jasmine.json
  playground/src/events/events.test.js
Labels: cla: yes

#2197 💬 Make translation hint more actionable
  frontend/templates/layouts/default.j2
  gulpfile.js/develop.js
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md
Labels: Category: Localization, Type: Update, cla: yes

#2198 changed default input values and sum for calcultor
  examples/static/samples/standalone/amp-website/index.html
Labels: Category: Examples, P1: High, Type: Update, cla: yes

#2199 Don't redirect static files to amp.dev
  examples/static/samples/files/resizable-iframe.html
  platform/lib/build/samplesBuilder.js
  platform/lib/platform.js
  platform/lib/routers/example/static.js
Labels: cla: yes

#2202 :bug: Decrease width of mobile sidebar
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar.scss
Labels: cla: yes

#2205 🚸 Use last non-merge commit message for build info
  platform/lib/utils/git.js
Labels: cla: yes

#2203 Fix/boilerplate
  .eslintignore
  boilerplate/data/categories.json
  boilerplate/lib/templates.js
  boilerplate/templates/files/serviceworkerJs.js
  boilerplate/templates/index.html
  boilerplate/templates/partials/analytics/google.html
  boilerplate/templates/styles/main.scss
  package.json
Labels: cla: yes

#2214 ♻️ Refactor travis conf to fix unintended builds
  .travis.yml
Labels: cla: yes

#2211 Various boilerplate generator fixes
  boilerplate/build.js
  boilerplate/lib/templates.js
  boilerplate/templates/index.html
  boilerplate/templates/styles/main.scss
Labels: cla: yes

#2219 🐛 Copy sitemap when building pages.
  gulpfile.js/build.js
  package-lock.json
  pages/static/robots/prod.txt
Labels: Category: Infrastructure, P1: High, Type: Bug, cla: yes
