Repository ampproject/amp.dev, pull requests merged in 2019-09, with the labels that each got.

#2866 tag errors
  platform/lib/platform.js
Labels: cla: yes

#2867 📝 Advise to use pip to install grow
  README.md
Labels: cla: yes

#2860 🐛 Only try to access teaser if it exists
  frontend/templates/views/partials/teaser.j2
Labels: cla: yes

#2871 🎨 Do not minify CSS variable names
  platform/lib/utils/cssTransformer.js
Labels: cla: yes

#2872 Fix borders around nav items
  frontend/scss/components/organisms/_sidebar.scss
  frontend/scss/components/organisms/burger-menu.scss
Labels: cla: yes

#2870 Improve cache sample endpoints
  examples/api/amp-cache.js
  examples/api/cache.js
  examples/source/2.guides/Using_the_Google_AMP_Cache.html
  examples/static/samples/files/get-example.html
Labels: cla: yes

#2873 🎨 Consolidate navigation title for examples page
  pages/content/amp-dev/documentation/examples/index.html
Labels: cla: yes

#2874 another iOS border fix
  frontend/scss/components/molecules/language-selector.scss
Labels: cla: yes

#2879 Fix draft rendering bug
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2887 Fix title and URL for Cloudflare AMP Real URL.
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#2890 included pip installation instructions for MacOS
  README.md
Labels: cla: yes

#2889 Fix amp script tut
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
Labels: cla: yes

#2899 cleaned up amp-script guide
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
Labels: Category: Documentation, Type: Update, cla: yes

#2900 Add AMPCS2019 location details and update FAQ
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#2892 [translation-ko] Add translations page
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/index@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations@ko.md
Labels: cla: yes

#2868 Add index.md beginning-course (Vietnamese translation)
  pages/content/amp-dev/documentation/courses/beginning-course/index@vi.md
Labels: cla: yes

#2902 Fix CORS for playground
  pages/content/amp-dev/documentation/examples/documentation/_blueprint.yaml
  platform/lib/middleware/subdomain.js
  platform/lib/platform.js
  playground/src/template-dialog/template-dialog.scss
Labels: cla: yes

#2896 💬 Add success stories for kompas and asahi
  frontend/templates/views/detail/success-story-detail.j2
  pages/content/amp-dev/about/success-stories/asahi.yaml
  pages/content/amp-dev/about/success-stories/asahi@ja.yaml
  pages/content/amp-dev/about/success-stories/kompas.yaml
  pages/static/img/success-stories/asahi/asahi_logo.jpg
  pages/static/img/success-stories/asahi/ss_with_ads.jpg
  pages/static/img/success-stories/asahi/ss_without_ads.jpg
  pages/static/img/success-stories/kompas/kompas_logo.jpg
  pages/static/img/success-stories/kompas/kompas_ss.jpg
  pages/static/img/success-stories/kompas/teaser_kompas.jpg
Labels: cla: yes

#2904 Fixes cheerio output for transformation
  platform/lib/format-transform/index.js
  platform/lib/format-transform/index.test.js
  platform/lib/utils/cheerioHelper.js
Labels: cla: yes

#2922 🚨 Fix various AMP validation errors
  pages/content/amp-dev/community/roadmap.html
  pages/content/amp-dev/documentation/components/reference/amp-auto-ads-v0.1@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-bind-v0.1@es.md
  pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@es.md
  pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements@es.md
  pages/content/amp-dev/documentation/index.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
Labels: cla: yes

#2926 🎨 Embed link icon in search with <use>
  frontend/templates/views/partials/search.j2
Labels: cla: yes

#2925 Update dependencies & fix lint errors
  package-lock.json
  package.json
  platform/lib/common/samples.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/routers/search.js
  platform/lib/routers/search.test.js
  platform/lib/tools/growReferenceChecker.js
  playground/src/auto-importer/auto-importer.js
Labels: cla: yes

#2920 🐛 Only rewrite content paths in Grow pod
  pages/extensions/internal_links/pod_internal_link_rewriter.py
  pages/extensions/internal_links/pod_internal_link_rewriter_test.py
Labels: cla: yes

#2927 Allow amp-form example endpoints to support application/x-www-form-urlencoded
  examples/api/amp-form.js
Labels: cla: yes

#2930 Ignore infrastructure files
  .dockerignore
  .gcloudignore
Labels: cla: yes

#2929 Reset variable in amp-lightbox amp-bind sample
  examples/source/1.components/amp-lightbox.html
Labels: cla: yes

#2933 📝 Fix validation errors in translated amp-access docs
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@es.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@id.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@it.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@ko.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@ru.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@zh_CN.md
Labels: cla: yes

#2932 💬 Update case study teaser descriptions
  pages/content/amp-dev/about/success-stories/asahi.yaml
  pages/content/amp-dev/about/success-stories/kompas.yaml
  pages/content/amp-dev/about/success-stories/nobroker.yaml
  pages/content/amp-dev/about/success-stories/renovation_brands.yaml
Labels: cla: yes

#2935 🎨 Unwrap code snippets in sample sections
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2934 Share search markup for search
  pages/content/shared/header.html
Labels: cla: yes

#2941 fixed document location and title
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/index.md
Labels: cla: yes

#2952 Add the tentative AMP Contributor Summit 2019 schedule
  pages/content/amp-dev/events/amp-cs-2019.html
  pages/shared/data/amp-cs-2019.yaml
Labels: cla: yes

#2951 removed references to Cloudflare and replaced with Bing
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/terminology.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@zh_CN.md
Labels: cla: yes

#2953 Adds a go.amp.dev link for the AMPCS2019 schedule
  platform/config/go-links.yaml
Labels: cla: yes

#2954 Revert "Added Eastern Europe roadshow cities"
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2959 Put some old cities in the past, added Eastern Europe cities to upcoming
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2957 🚸 Improve mobile UX
  frontend/scss/components/organisms/sampler.scss
  frontend/scss/components/organisms/translation-hint.scss
Labels: cla: yes

#2958 🚸 Make Get Started links on home point to Docs/Get Started
  pages/content/amp-dev/index.html
Labels: cla: yes

#2956 🐛 Set correct teaser text for NoBroker success story
  pages/content/amp-dev/about/success-stories/nobroker.yaml
Labels: cla: yes

#2948 Adds "Testing AMP emails" doc, moves client-specific playgrounds
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/testing_amp_emails.md
  pages/shared/data/tools.yaml
Labels: cla: yes

#2955 🐛 Escape SSR tags when importing documents
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
Labels: cla: yes

#2961 Update highlighted guides for email and update guides themselves
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
Labels: cla: yes

#2947 Generated search highlights are added to artifacts on travis
  gulpfile.js/build.js
  pages/extensions/extract_highlights_info/page_info_collector.py
  pages/extensions/extract_highlights_info/page_info_collector_test.py
  platform/config/search-promoted-pages/ar.json
  platform/config/search-promoted-pages/en.json
  platform/config/search-promoted-pages/es.json
  platform/config/search-promoted-pages/fr.json
  platform/config/search-promoted-pages/id.json
  platform/config/search-promoted-pages/it.json
  platform/config/search-promoted-pages/ja.json
  platform/config/search-promoted-pages/ko.json
  platform/config/search-promoted-pages/pt_BR.json
  platform/config/search-promoted-pages/ru.json
  platform/config/search-promoted-pages/tr.json
  platform/config/search-promoted-pages/zh_CN.json
  platform/lib/routers/search.js
Labels: cla: yes

#2969 add sample on how to verticaly center an amp-img
  examples/source/1.components/amp-img.html
Labels: cla: yes

#2976 Explain sample previews in more detail
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
Labels: cla: yes

#2967 Update Outlook.com logo
  pages/static/img/email-clients/outlook.png
Labels: cla: yes

#2980 added escaping for raw and server_for_email
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
Labels: cla: yes

#2978 added information on https protocol
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
Labels: cla: yes

#2977 clarified inline style byte limit
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
Labels: cla: yes

#2984 Fixed broken link: payments_in_amp
  examples/source/e-commerce/Payments_in_AMP.html
  examples/source/e-commerce/Product_Page.html
Labels: cla: yes

#2986 Describes trust levels for actions and events
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
Labels: cla: yes

#2987 Explain clone and fork
  README.md
Labels: cla: yes

#2982 Fix a bunch of broken samples
  examples/api/amp-access/index.js
  examples/source/1.components/amp-access.html
  examples/source/1.components/amp-analytics/api.js
  examples/source/1.components/amp-analytics/embed.html
  examples/source/1.components/amp-analytics/index.html
  examples/source/1.components/amp-recaptcha-input/index.html
  examples/source/1.components/amp-web-push/index.html
  examples/source/e-commerce/Checkout_Flow/index.html
  examples/source/e-commerce/Shopping_Cart/index.html
  examples/source/interactivity-dynamic-content/Comment_Section/index.html
  examples/source/interactivity-dynamic-content/Favorite_Button/index.html
  examples/source/interactivity-dynamic-content/Poll/index.html
  examples/source/interactivity-dynamic-content/Star_Rating/index.html
  frontend/templates/views/examples/documentation.j2
Labels: cla: yes

#2992 Fix amp-next-page sample
  examples/source/1.components/amp-next-page.html
Labels: cla: yes

#2960 🚸 Warn if document doesn't match currently selected format
  frontend/templates/views/partials/content.j2
Labels: cla: yes

#2994 Update ComboBox sample to open and close autocomplete suggestions
  examples/source/interactivity-dynamic-content/ComboBox.html
Labels: cla: yes

#2993 Fixed example top-frame preview in portrait mode
  frontend/scss/components/organisms/code-preview.scss
  frontend/templates/views/partials/code-preview/code-preview.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
Labels: cla: yes

#3007 visual polish
  examples/source/1.components/amp-autocomplete.html
Labels: cla: yes

#3008 🐛 Add dedicated router for shared fragments
  platform/lib/platform.js
  platform/lib/routers/growSharedPages.js
Labels: cla: yes

#3019 Search meta tag page-locale has untranslated locales on default page
  frontend/templates/views/partials/structured-data.j2
  pages/extensions/amp_dev/extension.py
Labels: cla: yes

#3002 Feature/explicit anchor on import
  pages/content/amp-dev/community/governance.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/ad-integration-guide.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/a4a_spec.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-debugging.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-html.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/pipeline/specImporter.js
  platform/lib/utils/slugGenerator.js
  platform/lib/utils/slugGenerator.test.js
Labels: cla: yes

#3020 run tests before push
  package-lock.json
  package.json
Labels: cla: yes

#3026 Changed venue for Warsaw
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3017 Update AMP Contributor Summit 2019 schedule
  pages/shared/data/amp-cs-2019.yaml
Labels: cla: yes

#3024 Remove 'Email Provider integration' doc
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md
Labels: cla: yes

#3028 AMP-CS: add dates to the tab titles of the schedule
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#3029 Only perform https redirect if scheme is set to https
  platform/lib/middleware/redirects.js
Labels: cla: yes

#3027 Add link to story ad preview tool
  pages/shared/data/tools.yaml
  pages/static/img/tools/amp-story-ad-preview.jpg
Labels: cla: yes

#3034 s/Google/The AMP Project/
  pages/content/amp-dev/events/code-of-conduct.html
Labels: cla: yes

#3037 Fix support section overview and breadcrumbs
  frontend/scss/components/templates/support-overview.scss
  frontend/templates/views/overview/support.j2
  frontend/templates/views/partials/breadcrumbs.j2
  pages/content/amp-dev/support/_blueprint.yaml
  pages/content/amp-dev/support/faq/platform-involvement.md
Labels: cla: yes

#3033 ✨ Search: UX improvements
  frontend/scss/components/organisms/search.scss
  frontend/templates/views/partials/header.j2
  frontend/templates/views/partials/search.j2
Labels: Category: UX, P1: High, Type: Bug, Type: Feature, cla: yes
