Repository ampproject/amp.dev, pull requests merged in 2019-08, with the labels that each got.

#2676 🐛 Fix endpoint url
  examples/source/interactivity-dynamic-content/Poll/index.html
Labels: Category: Examples, Type: Bug, cla: yes

#2668 fix supported browsers
  pages/content/amp-dev/support/faq/supported-browsers.md
Labels: cla: yes

#2670 ♿️ Support small and low-end devices with 240px width
  frontend/scss/_variables.scss
  frontend/scss/base.scss
  frontend/scss/components/molecules/language-selector.scss
  frontend/scss/components/organisms/burger-menu.scss
  frontend/scss/components/organisms/footer.scss
Labels: Category: UX, P1: High, Type: Update, cla: yes

#2675 Email cors
  package-lock.json
  package.json
  platform/lib/middleware/subdomain.js
  platform/lib/platform.js
Labels: cla: yes

#2677 Enable runtime log endpoint
  pages/content/amp-dev/message.html
  platform/lib/runtime-log/LogProvider.js
  platform/lib/runtime-log/LogProvider.test.js
  smoke-tests/platform/Routes.test.js
Labels: cla: yes

#2682 Add Quintype
  pages/shared/data/faq.yaml
  pages/shared/data/tools.yaml
  pages/static/img/tools/quintype.png
Labels: cla: yes

#2684 enable standalone mode
  pages/static/manifest.json
Labels: cla: yes

#2685 ♻️ Use RCS string replace over DOM method
  gulpfile.js/build.js
Labels: cla: yes

#2688 Revert "♻️ Use RCS string replace over DOM method"
  gulpfile.js/build.js
Labels: cla: yes

#2687 🐛 Run smoke-tests before running deployment
  .travis.yml
Labels: cla: yes

#2689 🐛 Fix broken link in documentation
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@zh_CN.md
Labels: cla: yes

#2637 ✨ Implement example code blocks with preview in iframe
  contributing/documentation.md
  frontend/icons/orientation-toggle.svg
  frontend/icons/reload.svg
  frontend/scss/components/atoms/fab.scss
  frontend/scss/components/molecules/code-snippet.scss
  frontend/scss/components/molecules/device-toggle.scss
  frontend/scss/components/organisms/code-preview.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/scss/components/templates/docs-detail.scss
  frontend/templates/layouts/example-pages/amp-websites-page.j2
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/code-preview/code-preview.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@zh_CN.md
  pages/content/tests/examples/preview_side_frame.md
  pages/content/tests/examples/preview_side_frame_short.md
  pages/content/tests/examples/preview_top_frame.md
  pages/extensions/amp_example_preview/readme.md
  pages/extensions/amp_example_preview/util/constants.py
  pages/extensions/amp_example_preview/util/example_document.py
  pages/extensions/amp_example_preview/util/example_extractor_test.py
  pages/extensions/amp_example_preview/util/markdown_processor.py
  pages/extensions/amp_example_preview/util/preview_generator.py
  pages/extensions/amp_example_preview/util/preview_test.py
Labels: Category: Examples, Category: UX, P1: High, Type: Update, cla: yes

#2694 🐛 Fix invalid keyframe properties
  frontend/scss/_mixins.scss
  frontend/scss/components/molecules/format-visual-websites.scss
  frontend/scss/components/molecules/format-visual.scss
  frontend/scss/components/molecules/visual-image.scss
  frontend/templates/views/partials/format-visuals/websites.j2
Labels: Category: UX, P3: Low, Type: Bug, cla: yes

#2697 Remove markdown=span attribute after markdown was rendered
  pages/extensions/markdown_in_html/__init__.py
  pages/extensions/markdown_in_html/html_block_processor.py
  pages/extensions/markdown_in_html/html_block_processor_test.py
Labels: cla: yes

#2698 Fix title handling for AMP components
  frontend/templates/views/partials/structured-data.j2
Labels: cla: yes

#2669 ♻️ Migrate amp-cache example to amp.dev
  examples/api/amp-cache.js
  examples/source/2.guides/Using_the_Google_AMP_Cache.html
  examples/static/samples/files/get-example.html
  examples/static/samples/files/invalid_amp.html
Labels: Category: Examples, Type: Bug, cla: yes

#2666 ♻️ Migrate product-page to amp.dev
  examples/api/product-browse-page.js
  examples/source/e-commerce/Product_Browse_Page.html
  examples/source/e-commerce/Product_Page.html
  examples/source/e-commerce/Shopping_Cart/api.js
  examples/source/e-commerce/Shopping_Cart/index.html
  package-lock.json
  package.json
Labels: Category: Examples, Type: Bug, cla: yes

#2704 ♻️ Migrate/hotel
  examples/source/e-commerce/Hotel/api.js
  examples/source/e-commerce/Hotel/index.html
  examples/static/samples/json/rooms.json
Labels: Category: Examples, Type: Bug, cla: yes

#2696 Update AMP html tags spec
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
Labels: cla: yes

#2709 Fix SXG warning
  platform/lib/routers/packager.js
Labels: cla: yes

#2712 Fix combobox sample
  examples/source/interactivity-dynamic-content/ComboBox.html
Labels: cla: yes

#2715 update dependencies
  package-lock.json
  package.json
  pages/content/amp-dev/documentation/components/reference/amp-accordion.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/shared/data/blog.yaml
Labels: cla: yes

#2719 🔧 Add datastore scope to GCE instance templates
  gulpfile.js/deploy.js
Labels: cla: yes

#2718 🔧 Redirect ampproject.org to new FAQ pages
  firebase.json
Labels: cla: yes

#2703 Update signed-exchange.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#2721 New meta tags (locale, format) that can be used for filtering in Google CSE
  frontend/templates/views/partials/structured-data.j2
Labels: cla: yes

#2722 ♻️ Do not use DOM for selector rewriting
  gulpfile.js/build.js
  package-lock.json
Labels: cla: yes

#2724 Revert New meta tags (locale, format) that can be used for filtering in Google CSE
  frontend/templates/views/partials/structured-data.j2
Labels: cla: yes

#2332 Tools: Add Onlymega to tools page
  pages/shared/data/tools.yaml
  pages/static/img/tools/onlymega.png
Labels: Category: Content, P2: Medium, Type: New, cla: yes

#2725 Revert ♻️ Do not use DOM for selector rewriting
  gulpfile.js/build.js
  package-lock.json
Labels: cla: yes

#2716 Add AMP-Prototyper to tools section
  pages/shared/data/tools.yaml
  pages/static/img/tools/amp-prototyper.jpg
Labels: cla: yes

#2723 ♻️ Migrate amp-user-notification example backend to amp.dev
  examples/source/1.components/amp-user-notification/api.js
  examples/source/1.components/amp-user-notification/index.html
Labels: Category: Examples, Type: Bug, cla: yes

#2726 added document on securing AMP docs with CSP
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/secure-pages.md
Labels: Category: Documentation, Type: New, cla: yes

#2730 added performance information for fallback images
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
Labels: cla: yes

#2731 New meta tags (locale, format) that can be used for filtering in Google CSE
  frontend/templates/views/partials/structured-data.j2
Labels: cla: yes

#2733 Fix snapshot image path for the AMP-Prototyper in tools section
  pages/shared/data/tools.yaml
Labels: cla: yes

#2736 ♻️ Move selector rewriting into amp-optimizer transformer
  gulpfile.js/build.js
  platform/lib/routers/growPages.js
  platform/lib/utils/cssTransformer.js
Labels: Category: Functionality, P1: High, Type: Update, cla: yes

#2737 🎨 Add explanation to components
  examples/source/interactivity-dynamic-content/Star_Rating/index.html
  examples/source/multimedia-animations/Custom_Loading_Indicators.html
  examples/source/multimedia-animations/Integrating_Videos_in_AMP_an_Overview.html
  examples/source/multimedia-animations/Rich_Media_Notifications.html
  examples/source/multimedia-animations/Video_Ad.html
  examples/source/multimedia-animations/Video_Carousels_with_amp-carousel.html
  examples/source/news-publishing/Recipe.html
  examples/source/user-consent/Advanced_User_Consent_Flow.html
  examples/source/user-consent/Basic_User_Consent_Flow.html
Labels: cla: yes

#2738 🔧 Add datastore scope to GCE instance templates
  gulpfile.js/deploy.js
Labels: cla: yes

#2741 Unbreak build by downloading broken docs from master
  pages/content/amp-dev/documentation/components/reference/amp-accordion.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/shared/data/blog.yaml
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/gitHubImporter.js
Labels: cla: yes

#2743 Typo fix on the Guides & Tutorials page
  frontend/templates/views/partials/resources-grid.j2
Labels: cla: yes

#2672 Added content contribution guidelines
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/ad-integration-guide.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/documentation-types.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/terminology.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech.md
Labels: Category: Content, Category: Documentation, P1: High, Type: New, cla: yes

#2747 only set Vary: AMP-Cache-Transform for html requests
  .gitignore
  platform/lib/platform.js
  platform/lib/routers/packager.js
Labels: cla: yes

#2746 🐛 Fix poll submit endpoint in preview mode
  examples/source/interactivity-dynamic-content/Poll/index.html
Labels: Category: Examples, Type: Bug, cla: yes

#2749 Add gulp tasks for packager deployment
  gulpfile.js/deploy.js
  gulpfile.js/packager.js
  packager/README.md
Labels: cla: yes

#2757 ♻️Migrate amp-analytics example backend to amp.dev
  examples/source/1.components/amp-analytics/api.js
  examples/source/1.components/amp-analytics/embed.html
  examples/source/1.components/amp-analytics/index.html
  package-lock.json
  package.json
Labels: Category: Examples, Type: Bug, cla: yes

#2679 Update browser console validation doc
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp.md
Labels: Status: Blocked, cla: yes

#2761 Removes Contributor Summit 2019 application & promo banner
  frontend/templates/views/partials/header.j2
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#2754 Rewrite pod internal links in <a href to site links
  pages/extensions/internal_links/__init__.py
  pages/extensions/internal_links/pod_internal_link_rewriter.py
  pages/extensions/internal_links/pod_internal_link_rewriter_test.py
  pages/extensions/internal_links/readme.md
  platform/config/podspec.yaml
Labels: cla: yes

#2762 🐛 Fix amp-bind example api endpoint
  examples/source/1.components/amp-bind.html
Labels: Category: Examples, Type: Bug, cla: yes

#2750 🐛 Fix amp-access login
  examples/api/amp-access/index.js
  examples/api/amp-access/login.html
Labels: Category: Examples, Type: Bug, cla: yes

#2748 ♻️ Migrate amp-recaptcha-input example backend to amp.dev
  examples/source/1.components/amp-recaptcha-input/api.js
  examples/source/1.components/amp-recaptcha-input/index.html
Labels: Category: Examples, Type: Update, cla: yes

#2636 ✨Add Toggle for advanced and beginner mode on course sites
  frontend/icons/questionmark.svg
  frontend/scss/components/molecules/experiments.scss
  frontend/scss/components/molecules/level-toggle.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/content.j2
  frontend/templates/views/partials/level-toggle.j2
  pages/content/amp-dev/documentation/courses/advanced-course/appendix.md
  pages/content/amp-dev/documentation/courses/advanced-course/conclusion-and-whats-next.md
  pages/content/amp-dev/documentation/courses/advanced-course/index.md
  pages/content/amp-dev/documentation/courses/advanced-course/loading-and-displaying-server-content.md
  pages/content/amp-dev/documentation/courses/advanced-course/remembering-what-the-user-has-done.md
  pages/content/amp-dev/documentation/courses/beginning-course/appendix.md
  pages/content/amp-dev/documentation/courses/beginning-course/conclusions-and-whats-next.md
  pages/content/amp-dev/documentation/courses/beginning-course/course-introduction.md
  pages/content/amp-dev/documentation/courses/beginning-course/finding-the-right-component.md
  pages/content/amp-dev/documentation/courses/beginning-course/index.md
  pages/content/amp-dev/documentation/courses/beginning-course/our-first-amp-page.md
  pages/content/amp-dev/documentation/courses/beginning-course/thinking-in-components.md
  pages/content/amp-dev/documentation/courses/intermediate-course/accepting-user-input-and-displaying-output.md
  pages/content/amp-dev/documentation/courses/intermediate-course/appendix.md
  pages/content/amp-dev/documentation/courses/intermediate-course/conclusion-and-whats-next.md
  pages/content/amp-dev/documentation/courses/intermediate-course/handling-user-interactions.md
  pages/content/amp-dev/documentation/courses/intermediate-course/index.md
  pages/content/amp-dev/documentation/courses/intermediate-course/making-components-work-together.md
  pages/extensions/amp_dev/markdown_extras/block_filter.py
  platform/lib/routers/growPages.js
  platform/lib/templates/index.js
Labels: cla: yes

#2594 ✨ Add SSR for success story overview page
  frontend/scss/components/templates/success-story.scss
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/about/success-stories/index.html
Labels: cla: yes

#2781 🎨 Remove TOC from courses sites
  pages/content/amp-dev/documentation/courses/advanced-course/_blueprint.yaml
  pages/content/amp-dev/documentation/courses/beginning-course/_blueprint.yaml
  pages/content/amp-dev/documentation/courses/intermediate-course/_blueprint.yaml
Labels: cla: yes

#2785 🎨 Fix search priority of sidebar markup
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/detail/guide-detail.j2
  frontend/templates/views/detail/template-detail.j2
  frontend/templates/views/detail/use-cases-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/overview/courses.j2
  frontend/templates/views/overview/guides.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/sidebar.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: Category: UX, P1: High, Type: Bug, cla: yes

#2787 Fix typo
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
Labels: cla: no

#2776 🎨 Improve new overview pages
  frontend/templates/views/partials/card-grid.j2
  frontend/templates/views/partials/teaser-tags.j2
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
  pages/translations/en/LC_MESSAGES/messages.po
Labels: Category: UX, P1: High, Type: Update, cla: yes

#2720 Add amp-cors-requests.md Chinese translation.
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests@zh_CN.md
Labels: cla: yes

#2797 Redirect faqs
  firebase.json
Labels: cla: no

#2792 update dependencies
  package-lock.json
  package.json
  pages/content/amp-dev/documentation/components/reference/amp-accordion.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
  playground/src/auto-importer/auto-importer.js
  playground/src/editor/editor.js
Labels: cla: yes

#2799 Update README to clarify that Windows is not currently supported
  README.md
Labels: cla: yes

#2795 Better vary filter
  platform/lib/routers/packager.js
Labels: cla: yes

#2786 🎨 Improving the info-button of the level-toggle
  frontend/scss/components/molecules/info-button.scss
  frontend/scss/components/molecules/level-toggle.scss
  frontend/templates/views/partials/content.j2
  frontend/templates/views/partials/level-toggle.j2
  platform/lib/utils/cssTransformer.js
Labels: cla: yes

#2794 re-enable preview
  examples/source/interactivity-dynamic-content/ComboBox.html
Labels: cla: yes

#2780 Fix links and reference checker
  pages/content/amp-dev/documentation/components/reference/amp-ad@ar.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@es.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@fr.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@id.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@it.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@ko.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@ru.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-ad@zh_CN.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@ar.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@es.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@fr.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@id.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@it.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@ko.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@ru.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-bind@zh_CN.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@ar.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@es.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@fr.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@id.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@it.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@ko.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@ru.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-iframe@zh_CN.md
  pages/content/amp-dev/documentation/courses/beginning-course/our-first-amp-page.md
  pages/content/amp-dev/documentation/courses/intermediate-course/making-components-work-together.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/documentation-types.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated.html
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa.md
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/tools/growReferenceChecker.js
Labels: cla: yes

#2805 🎨 Improve styling of overview pages
  frontend/scss/_variables.scss
  frontend/scss/components/atoms/format-tags.scss
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/molecules/table-component.scss
  frontend/scss/components/molecules/teaser-component-code.scss
  frontend/scss/components/molecules/teaser-guides.scss
  frontend/scss/components/molecules/teaser-highlight-guides.scss
  frontend/scss/components/organisms/accordion.scss
  frontend/scss/components/organisms/tools-teaser.scss
  frontend/scss/components/templates/component-overview.scss
  frontend/scss/components/templates/tools.scss
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
Labels: cla: yes

#2777 [Feature] Support multiple components/tags per extension
  package-lock.json
  package.json
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/gitHubImporter.js
Labels: cla: yes

#2809 Fix importing component docs where the name is not a tag
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/markdownDocument.js
Labels: cla: yes

#2810 added pepipost
  pages/shared/data/tools.yaml
  pages/static/img/tools/pepipost.jpg
Labels: cla: yes

#2813 🐛 Correctly encode inline svg backgrounds
  frontend/scss/components/atoms/format-backgrounds.scss
Labels: P2: Medium, Type: Bug, cla: yes

#2812 updated to include sxg provider
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#2705 Search functionality
  examples/source/1.components/amp-date-countdown.html
  frontend/scss/components/molecules/language-selector.scss
  frontend/scss/components/molecules/search-trigger.scss
  frontend/scss/components/organisms/burger-menu.scss
  frontend/scss/components/organisms/header.scss
  frontend/scss/components/organisms/search.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/header.j2
  frontend/templates/views/partials/search.j2
  gulpfile.js/develop.js
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
  pages/content/amp-dev/search.html
  pages/extensions/extract_highlights_info/__init__.py
  pages/extensions/extract_highlights_info/page_info_collector.py
  pages/extensions/extract_highlights_info/readme.md
  platform/config/podspec.yaml
  platform/config/search-promoted-pages.json
  platform/lib/common/AmpConstants.js
  platform/lib/common/samples.js
  platform/lib/common/samples.test.js
  platform/lib/config.js
  platform/lib/platform.js
  platform/lib/routers/search.js
  platform/lib/routers/search.test.js
  platform/lib/utils/cssTransformer.js
  platform/lib/utils/googleSearch.js
Labels: Category: Functionality, P1: High, Type: Feature, cla: yes

#2814 Small search improvements
  frontend/scss/components/organisms/search.scss
  pages/content/amp-dev/search.html
Labels: Category: UX, P3: Low, Type: Update, cla: yes

#2815 Generate component versions at build time
  .travis.yml
  gulpfile.js/build.js
  gulpfile.js/develop.js
  package-lock.json
  package.json
  pages/extensions/amp-component-versions.json
  pages/extensions/amp_dependencies/amp_dependencies.py
  pages/extensions/amp_example_preview/util/amp_component_versions.py
  platform/lib/routers/search.js
  playground/backend/api.js
  playground/src/components-provider/components-provider.js
Labels: cla: yes

#2823 Feature/new roadshow cities
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2772 ♻️ Migrate amp-web-push example to amp.dev
  examples/source/1.components/amp-web-push/api.js
  examples/source/1.components/amp-web-push/index.html
  examples/source/1.components/amp-web-push/static/sw.js
  package-lock.json
  package.json
Labels: Category: Examples, Type: Bug, cla: yes

#2832 Further search improvements
  frontend/scss/components/organisms/search.scss
  frontend/templates/views/partials/search.j2
Labels: Category: UX, P3: Low, Type: Update, cla: yes

#2836 [WIP] Adds an origin trial token for the dynamic autoplay propagation experiment
  frontend/templates/layouts/default.j2
  playground/src/index.hbs
Labels: cla: yes

#2841 analytics track search trigger
  frontend/templates/views/partials/analytics.j2
Labels: cla: yes

#2843 Fix css limitation errors on some example pages
  examples/source/e-commerce/Product_Page.html
  platform/lib/utils/cssTransformer.js
Labels: Category: Examples, P1: High, Type: Bug, cla: yes

#2846 Updated origin trial token for dynamic autoplay delegation
  frontend/templates/layouts/default.j2
  playground/src/index.hbs
Labels: cla: yes

#2851 Internal component links without version resolve to the latest
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
  pages/extensions/internal_links/__init__.py
  pages/extensions/internal_links/component_version_resolver.py
  pages/extensions/internal_links/component_version_resolver_test.py
  pages/extensions/internal_links/pod_internal_link_rewriter.py
  pages/extensions/internal_links/pod_internal_link_rewriter_test.py
  platform/config/podspec.yaml
Labels: cla: yes

#2852 Grow link extension should work with grow 0.7.4
  pages/extensions/internal_links/component_version_resolver.py
  pages/extensions/internal_links/component_version_resolver_test.py
Labels: cla: yes

#2853 Ensure the grow link handling does not confuse locale
  pages/extensions/internal_links/component_version_resolver.py
  pages/extensions/internal_links/component_version_resolver_test.py
  pages/extensions/internal_links/pod_internal_link_rewriter.py
  pages/extensions/internal_links/pod_internal_link_rewriter_test.py
Labels: cla: yes

#2855 Adding content for Middle East roadshows
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2856 Use PNG for custom arrows in amp-carousel example, use responsive for amp-accordion example
  examples/source/1.components/amp-accordion.html
  examples/source/1.components/amp-carousel.html
  examples/static/samples/img/carousel-arrow-left.png
  examples/static/samples/img/carousel-arrow-right.png
Labels: cla: yes

#2858 Replace animation in amp-list example with static placeholder
  examples/source/1.components/amp-list.html
Labels: cla: yes

#2859 Fix folder path for getting started command
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
Labels: cla: yes

#2848 🔍 Do not list sample previews in sitemap
  pages/content/tests/examples/default_settings.md
  pages/content/tests/examples/example_with_comments.md
  pages/content/tests/examples/full_html.md
  pages/content/tests/examples/head_style.md
  pages/content/tests/examples/import.md
  pages/content/tests/examples/multi_examples.md
  pages/content/tests/examples/no_playground.md
  pages/content/tests/examples/no_preview.md
  pages/content/tests/examples/preview_inline.md
  pages/content/tests/examples/preview_side_frame.md
  pages/content/tests/examples/preview_side_frame_short.md
  pages/content/tests/examples/preview_top_frame.md
  pages/content/tests/examples/template.md
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2862 add amp-script sample
  examples/source/1.components/amp-bind.html
  examples/source/1.components/amp-script/api.js
  examples/source/1.components/amp-script/index.html
  examples/source/1.components/amp-script/static/hello-world.js
  package-lock.json
  package.json
  platform/lib/pipeline/componentReferenceImporter.js
Labels: cla: yes
