Repository ampproject/amp.dev, pull requests merged in 2019-04, with the labels that each got.

#1655 Add Kenshoo analytics service documentation
  content/docs/analytics/analytics-vendors.md
Labels: Category: Content, Site: ampproject.org, Type: New

#1658 ✨ Add Kenshoo analytics vendor.
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md
Labels: Category: Content, Site: amp.dev, Type: New

#1673 Fix Ja translation on about-how page
  content/learn/about-how@ja.yaml
Labels: Category: Content, Language: JA, P3: Low, Site: ampproject.org

#1688 🐛 Correctly check if document should have a TOC.
  frontend/templates/views/partials/toc.j2
Labels: Category: Functionality, P2: Medium, Site: amp.dev, Type: Bug

#1702 fix websites link
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/index.html
Labels: cla: yes

#1656 Sw update
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp_to_pwa.md
Labels: Category: Documentation, Site: amp.dev, Type: Update, cla: yes

#1700 preload fira font
  boilerplate/templates/index.html
  frontend/templates/layouts/default.j2
  playground/src/index.hbs
Labels: cla: yes

#1710 Small various fixes.
  frontend/scss/components/molecules/table.scss
  frontend/scss/components/templates/docs-detail.scss
  frontend/templates/views/partials/teaser.j2
  platform/lib/pipeline/markdownDocument.js
Labels: Site: amp.dev, Type: Bug, cla: no

#1715 Feature/fix broken success stories link
  pages/content/amp-dev/about/success-stories/greenslips.yaml
Labels: Type: Bug, cla: yes

#1716 🍱 Migrate missing samples.
  examples/source/0.introduction/AMPHTML_Ads_Hello_World.html
  examples/source/1.components/amp-date-display.html
  examples/source/advertising-analytics/AMPHTML_ads_vs_non_AMP_ads.html
  examples/source/e-commerce/Shopping_Cart.html
  examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection.html
  platform/lib/build/samplesBuilder.js
Labels: Category: Examples, P0: Critical, Type: New, cla: yes

#1711 added email best practices and updated email specific doc filtering
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_email_best_practices.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/validate_emails.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
Labels: Category: Documentation, Site: amp.dev, Type: Update, cla: yes

#1717 Amp cache guide
  examples/api/cache.js
  examples/source/2.guides/Using_the_Google_AMP_Cache.html
  examples/static/samples/files/amp-url-converter.html
  examples/static/samples/files/amp_url_converter.js
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-debugging.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/index.md
  platform/config/imports/spec.json
  platform/lib/middleware/subdomain.js
Labels: cla: yes

#1712 added checklist to success
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/publishing_checklist.md
Labels: Category: Documentation, P1: High, Site: amp.dev, Type: New, cla: yes

#1725 Add supported browsers section
  frontend/scss/components/organisms/browsers.scss
  pages/content/amp-dev/support/faq/_blueprint.yaml
  pages/content/amp-dev/support/faq/supported-browsers.md
  pages/content/amp-dev/support/index.md
  pages/content/shared/data/supported-browsers.yaml
  pages/static/img/platforms/chrome.png
  pages/static/img/platforms/edge.png
  pages/static/img/platforms/firefox.png
  pages/static/img/platforms/opera.png
  pages/static/img/platforms/safari.png
  pages/static/img/platforms/uc_browser.png
Labels: cla: yes

#1718 Improve caching
  platform/lib/utils/CachingStrategy.js
Labels: cla: yes

#1726 🐛 Do not use g.doc inside sourcecode blocks.
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@fr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@it.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@ru.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@tr.md
Labels: P0: Critical, Site: amp.dev, cla: yes

#1727 Fix component imports
  frontend/templates/layouts/default.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/service-worker.j2
Labels: cla: yes

#1728 Remove important from CSS
  frontend/scss/components/organisms/banner.scss
  frontend/scss/components/organisms/mini-card-list.scss
Labels: cla: yes

#1730 Fix g.doc link in sourcecode
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/index@ko.md
Labels: cla: yes

#1733 Don't call next() after serving a page
  platform/lib/platform.js
  platform/lib/routers/pages.js
Labels: cla: yes

#1729 Fix duplicate tutorials
  pages/content/amp-dev/about/mission-and-vision.html
Labels: cla: yes

#1677 ♻️ Rewrite ampbyexample.com links to internal ones.
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/index@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/login_requiring/index@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/login_requiring/login.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-as-pwa@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/engagement@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_amphtml_ad/summary.md
  pages/content/amp-dev/support/index.md
Labels: Category: Examples, Site: amp.dev, Status: WIP, Type: Update, cla: yes

#1649 Ads & Email Sample Preview.
  examples/source/0.introduction/Banner_Ad.html
  frontend/scss/components/atoms/sample-preview-title.scss
  frontend/scss/components/molecules/device-toggle.scss
  frontend/scss/components/molecules/homepage-link.scss
  frontend/scss/components/organisms/preview-pane.scss
  frontend/templates/views/examples/embed-ads.j2
  frontend/templates/views/examples/preview.j2
  platform/lib/build/samplesBuilder.js
Labels: Category: Examples, Category: UX, Site: amp.dev, cla: yes

#1735 ✨ Add OpenGraph and Twitter Card tags
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/structured-data.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/websites.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.websites.html
  pages/static/img/sharing/about-ads-1x1.png
  pages/static/img/sharing/about-ads-600x314.png
  pages/static/img/sharing/about-email-1x1.png
  pages/static/img/sharing/about-email-600x314.png
  pages/static/img/sharing/about-stories-1x1.png
  pages/static/img/sharing/about-stories-600x314.png
  pages/static/img/sharing/about-websites-1x1.png
  pages/static/img/sharing/about-websites-600x314.png
  pages/static/img/sharing/default-1x1.png
  pages/static/img/sharing/default-600x314.png
  pages/static/img/sharing/docs-component-1x1.png
  pages/static/img/sharing/docs-component-600x314.png
  pages/static/img/sharing/docs-example-1x1.png
  pages/static/img/sharing/docs-example-600x314.png
  pages/static/img/sharing/docs-guide-1x1.png
  pages/static/img/sharing/docs-guide-600x314.png
Labels: Category: Functionality, Site: amp.dev, Type: New, cla: yes

#1736 🐛 Do not use doc.public_path in language selector.
  frontend/templates/views/partials/header.j2
Labels: cla: yes

#1737 🐛 Correctly pass locale when getting doc.
  pages/extensions/amp_dev/extension.py
Labels: cla: yes

#1742 🐛 fix table cells for responsive assets
  frontend/scss/components/molecules/table.scss
Labels: Category: Functionality, Type: Bug, cla: yes

#1743 Improve page serving
  platform/lib/routers/pages.js
Labels: cla: yes

#1744 🐛 Reintroduce HTML extension for built files.
  examples/source/1.components/amp-ad.html
  examples/source/news-publishing/Live_Blog/Live_Blog.html
  pages/content/amp-dev/about/_blueprint.yaml
  pages/content/amp-dev/about/success-stories/_blueprint.yaml
  pages/content/amp-dev/community/_blueprint.yaml
  pages/content/amp-dev/documentation/_blueprint.yaml
  pages/content/amp-dev/documentation/components/_blueprint.yaml
  pages/content/amp-dev/documentation/components/reference/_blueprint.yaml
  pages/content/amp-dev/documentation/examples/documentation/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactive_widget/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity_data/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/login_requiring/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_amphtml_ad/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/_blueprint.yaml
  pages/content/amp-dev/documentation/templates/_blueprint.yaml
  pages/content/amp-dev/events/_blueprint.yaml
  pages/content/amp-dev/support/_blueprint.yaml
  pages/content/amp-dev/support/faq/_blueprint.yaml
  pages/extensions/amp_dev/extension.py
  platform/lib/build/pageMinifier.js
  platform/lib/routers/pages.js
Labels: Category: Infrastructure, P0: Critical, Site: amp.dev, cla: yes

#1741 🔧 Redirect ampproject.org to amp.dev
  firebase.json
  routes.txt
Labels: Category: Infrastructure, Site: amp.dev, Site: ampproject.org, Type: Update, cla: yes

#1746 Fix home links
  frontend/templates/views/partials/header.j2
  pages/content/amp-dev/404.html
  pages/content/amp-dev/500.html
Labels: cla: yes

#1695 Create spacing between paragraphs inside notes
  frontend/scss/components/molecules/tip.scss
Labels: Category: UX, Site: amp.dev, Type: Update

#1723 Don't put text in lists in a smaller font size.
  frontend/scss/components/atoms/text.scss
Labels: cla: yes

#1753 Updating profile, company name and description
  content/includes/amp-conf.yaml
Labels: cla: yes

#1755 🐛 Add redirect rules for language independent requests
  firebase.json
Labels: cla: yes

#1754 updated speakers and photos
  pages/content/shared/data/amp-conf.yaml
  pages/static/img/amp-conf/speakers/komada.jpg
  pages/static/img/amp-conf/speakers/ohtsu.jpg
  pages/static/img/amp-conf/speakers/ryo.jpg
Labels: cla: yes

#1756 🐛 fixed image sizing in some tables
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_story_best_practices.md
Labels: Category: Functionality, Type: Bug, cla: yes

#1759 🐛 Dissolve differences between i18n paths and globals
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/login_requiring/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp.md
Labels: Category: Infrastructure, P0: Critical, Site: amp.dev, cla: yes

#1769 Fix drafted samples and e-commerce Get Started.
  examples/source/1.components/amp-springboard-player.html
  examples/source/1.components/amp-web-push.html
  examples/source/e-commerce/AMP_for_E-Commerce_Getting_Started.html
  examples/source/interactivity-dynamic-content/Favorite_Button.html
  examples/source/interactivity-dynamic-content/Friend_Requests_Email.html
  frontend/templates/views/partials/example-sidebar.j2
Labels: Category: Examples, cla: yes

#1770 🐛 Add missing sample static files.
  examples/source/2.guides/Internationalization.html
  examples/source/advertising-analytics/Joining_Analytics_Sessions.html
  examples/static/samples/hreflang/fr/index.amp.html
  examples/static/samples/hreflang/fr/index.html
  examples/static/samples/hreflang/index.amp.html
  examples/static/samples/hreflang/index.html
  examples/static/samples/internationalization/alternate/fr/index.amp.html
  examples/static/samples/internationalization/alternate/fr/index.html
  examples/static/samples/internationalization/alternate/fr/index.mobile.html
  examples/static/samples/internationalization/alternate/index.amp.html
  examples/static/samples/internationalization/alternate/index.html
  examples/static/samples/internationalization/alternate/index.mobile.html
  examples/static/samples/internationalization/alternate/ja/index.amp.html
  examples/static/samples/internationalization/alternate/ja/index.html
  examples/static/samples/internationalization/alternate/ja/index.mobile.html
  examples/static/samples/internationalization/amp_hreflang_example_1.png
  examples/static/samples/internationalization/amp_hreflang_example_2.png
  examples/static/samples/internationalization/basic/fr/index.amp.html
  examples/static/samples/internationalization/basic/fr/index.html
  examples/static/samples/internationalization/basic/index.amp.html
  examples/static/samples/internationalization/basic/index.html
  examples/static/samples/internationalization/basic/ja/index.amp.html
  examples/static/samples/internationalization/basic/ja/index.html
  examples/static/samples/internationalization/rtl.html
  examples/static/samples/linker/demo-page.html
  examples/static/samples/linker/destination-page.html
Labels: Category: Examples, cla: yes

#1760 🐛 Update redirect configuration pointing to amp.dev
  firebase.json
Labels: Category: Infrastructure, P1: High, Site: ampproject.org, Type: Update, cla: yes

#1774 install sw via iframe
  frontend/templates/views/partials/service-worker.j2
  pages/static/serviceworker.html
  platform/lib/routers/static.js
Labels: cla: yes

#1775 Missing files
  examples/static/samples/files/amp-app-banner-manifest.json
  examples/static/samples/json/seatmap-neighbours.json
Labels: cla: yes

#1768 fix get-involved-banner text color
  frontend/scss/base.scss
  frontend/scss/components/organisms/banner.scss
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.websites.html
Labels: cla: no

#1675 Setup robots.txt and sitemap.xml
  pages/static/robots/prod.txt
  pages/static/robots/staging.txt
  pages/static/sitemap/sitemap.xml
  pages/static/sitemap/sitemap_ampbyexample.xml
  pages/static/sitemap/sitemap_ampproject.xml
  pages/static/sitemap/sitemap_ampstart.xml
  pages/static/sitemap/sitemap_manual.xml
  platform/config/podspec.yaml
  platform/lib/config.js
  platform/lib/routers/static.js
Labels: Category: Infrastructure, Site: amp.dev, Type: New, cla: no

#1709 show a referrer notification
  frontend/templates/layouts/default.j2
  platform/lib/common/filteredPage.js
  platform/lib/common/referrerNotification.js
  platform/lib/routers/pages.js
Labels: Category: UX, Site: amp.dev, Type: New, cla: yes

#1778 migrate amp-addthis sample
  examples/source/1.components/amp-addthis.html
Labels: cla: yes

#1780 🐛 Fix structured data.
  frontend/templates/views/partials/structured-data.j2
  platform/lib/build/samplesBuilder.js
Labels: Category: Examples, cla: yes

#1776 🐛 Migrate webpush sample files.
  examples/index.js
  examples/source/1.components/amp-web-push/api.js
  examples/source/1.components/amp-web-push/index.html
  examples/source/1.components/amp-web-push/static/amp-web-push-helper-frame.html
  examples/source/1.components/amp-web-push/static/amp-web-push-permission-dialog.html
  examples/source/1.components/amp-web-push/static/sw.js
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#1782 🐛 Update governance redirect.
  firebase.json
Labels: cla: yes

#1781 append .html if not in path
  platform/lib/routers/pages.js
Labels: cla: yes

#1784 🐛 Fix path for media_iframes_3p collection.
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/_blueprint.yaml
Labels: cla: yes

#1785 🎨 Reorder and add redirect rules to ampproject.org
  firebase.json
Labels: cla: yes

#1786 disable inline preview and enable preview
  examples/source/1.components/amp-web-push/index.html
Labels: cla: yes

#1787 Update importing.
  README.md
  package.json
  pages/content/amp-dev/community/governance.md
  platform/config/imports/spec.json
  platform/lib/build/samplesBuilder.js
  platform/lib/pipeline/gitHubImporter.js
  platform/lib/pipeline/roadmapImporter.js
  platform/lib/pipeline/specImporter.js
Labels: Category: Infrastructure, cla: yes

#1790 🐛 Add redirect rule for Actions and Events.
  firebase.json
Labels: cla: yes

#1791 ✨ Add specific rules for /latest/blog/.
  firebase.json
Labels: cla: yes

#1794 Fixing a minor typo
  pages/translations/messages.pot
Labels: cla: yes

#1793 Fixing minor typo pt2
  frontend/templates/views/detail/component-detail.j2
Labels: cla: yes

#1798 🐛 Fix hidden burger menu on mobile iOS viewer
  frontend/scss/components/organisms/burger-menu.scss
Labels: cla: yes

#1816 updated talk name
  pages/content/shared/data/amp-conf.yaml
Labels: cla: yes

#1803 add amp validation task
  examples/source/1.components/amp-web-push/static/sw.js
  gulpfile.js/validate.js
  package-lock.json
  package.json
Labels: cla: yes

#1818 🐛Fix redirects for ampproject.org
  firebase.json
Labels: cla: yes

#1813 🐛 Add missing extension to Start collection.
  pages/content/amp-dev/documentation/guides-and-tutorials/start/_blueprint.yaml
Labels: Category: Infrastructure, P1: High, Site: amp.dev, Type: Bug, cla: yes

#1812 ✨ Add Governance to community menu.
  pages/content/amp-dev/community/_blueprint.yaml
  pages/content/amp-dev/community/governance.md
  platform/config/imports/spec.json
Labels: Category: UX, Site: amp.dev, cla: yes

#1820 Fix format handling
  platform/lib/routers/pages.js
Labels: cla: yes

#1811 🐛 Fix local format filtering.
  platform/lib/routers/pages.js
Labels: Category: UX, P3: Low, Site: amp.dev, Type: Bug, cla: yes

#1810 🐛 Fix invalid AMPs.
  frontend/scss/components/templates/what-is-amp.scss
  frontend/templates/views/detail/success-story-detail.j2
  frontend/templates/views/partials/example-sidebar.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/websites.html
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
  pages/content/amp-dev/events/amp-roadshow.html
  pages/content/amp-dev/index.html
  pages/content/amp-dev/support/faq/supported-browsers.md
  pages/content/shared/_blueprint.yaml
  pages/extensions/amp_dev/markdown_extras/block_video.py
  pages/shared/data/amp-conf.yaml
  pages/shared/data/benefits.yaml
  pages/shared/data/blog.yaml
  pages/shared/data/cms.yaml
  pages/shared/data/hello-world.html
  pages/shared/data/roadshow.yaml
  pages/shared/data/supported-browsers.yaml
  platform/lib/build/pageMinifier.js
Labels: cla: yes

#1824 Remove "cd platform" from README
  README.md
Labels: cla: yes

#1825 Add lorem ipsum descriptions to images in api/photo-stream
  examples/api/photo-stream.js
  package-lock.json
  package.json
Labels: cla: yes

#1829 ✨add video for stamp ad template
  examples/static/samples/video/amp-stories-ad-template-single-video.mp4
Labels: cla: yes

#1831 Use https for photo stream, create hello endpoint
  examples/api/hello.js
  examples/api/photo-stream.js
  package-lock.json
  package.json
Labels: cla: yes

#1832 ⚡️ Use box-shadow instead of drop-shadow for tip
  frontend/scss/components/molecules/tip.scss
Labels: cla: yes

#1833 fix lint errors
  examples/api/hello.js
  examples/api/photo-stream.js
Labels: cla: yes

#1836 Reenable blurry placeholder
  package-lock.json
  package.json
Labels: cla: yes

#1830 Improve vertical rhythm and normalize typography across all pages
  frontend/scss/components/atoms/_headline.scss
  frontend/scss/components/atoms/_text.scss
  frontend/scss/components/atoms/headline.scss
  frontend/scss/components/atoms/text.scss
  frontend/scss/components/molecules/code-snippet.scss
  frontend/scss/components/molecules/conf-event.scss
  frontend/scss/components/molecules/table.scss
  frontend/scss/components/molecules/tip.scss
  frontend/scss/components/organisms/stage.scss
  frontend/scss/components/templates/docs-detail.scss
  frontend/scss/components/templates/roadmap.scss
  frontend/scss/components/templates/template.scss
  frontend/scss/components/templates/tools.scss
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
Labels: cla: yes

#1845 ♻️ Make header keyboard accessible.
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/molecules/language-selector.scss
  frontend/scss/components/organisms/header.scss
  frontend/scss/components/templates/_default.scss
  frontend/templates/views/partials/header.j2
Labels: cla: yes

#1849 Typo fix in embed pin widget doc
  examples/source/1.components/amp-pinterest.html
Labels: cla: yes

#1844 🐛 fix component visual link overlaping on hover
  frontend/scss/components/organisms/component-visual.scss
Labels: Category: UX, P3: Low, Site: amp.dev, Type: Bug, cla: yes

#1851 add vision/mission short link
  platform/config/go-links.yaml
Labels: cla: yes

#1852 Add /stories-best-practices shortlink to stories guidelines
  platform/config/go-links.yaml
Labels: cla: yes

#1856 Removes the experiment from amp-recaptcha-input
  examples/source/1.components/amp-recaptcha-input.html
Labels: cla: yes

#1855 Fix broken link on sample/link/demo-page.html
  examples/static/samples/linker/demo-page.html
Labels: cla: yes

#1857 Refactor FilteredPages
  platform/lib/common/filteredPage.js
  platform/lib/routers/pages.js
Labels: cla: yes

#1814 ✨ Make header and footer available standalone.
  pages/content/shared/footer.html
  pages/content/shared/header.html
Labels: Category: Infrastructure, P2: Medium, Site: amp.dev, Type: New, cla: yes

#1861 ✨ Use amp-geo to show different newsletter link
  frontend/scss/components/templates/home.scss
  frontend/templates/views/partials/consent.j2
  pages/content/amp-dev/index.html
Labels: Category: UX, P2: Medium, Site: amp.dev, Type: Update, cla: yes

#1834 add packager
  .dockerignore
  .gcloudignore
  gulpfile.js/deploy.js
  gulpfile.js/packager.js
  package-lock.json
  package.json
  packager/Dockerfile
  packager/README.md
  packager/amppkg.toml
  packager/app.yaml
  packager/decrypt.sh
  platform/config/environments/local.json
  platform/config/environments/production.json
  platform/config/environments/staging.json
  platform/config/podspec.yaml
  platform/lib/platform.js
  platform/lib/routers/packager.js
  platform/lib/routers/pages.js
  platform/lib/utils/sh.js
Labels: cla: yes

#1842 Fix sample listing in playground.
  .gitignore
  examples/source/0.introduction/index.json
  examples/source/1.components/index.json
  examples/source/2.guides/index.json
  examples/source/advertising-analytics/index.json
  examples/source/e-commerce/index.json
  examples/source/interactivity-dynamic-content/index.json
  examples/source/multimedia-animations/index.json
  examples/source/news-publishing/index.json
  examples/source/personalization/index.json
  examples/source/style-layout/index.json
  examples/source/user-consent/index.json
  examples/source/visual-effects/index.json
  platform/lib/build/samplesBuilder.js
  platform/lib/middleware/subdomain.js
  playground/src/template-dialog/base.js
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#1868 🙈 Unignore files in /examples/source/.
  .dockerignore
  .gcloudignore
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#1866 🐛 develop.json was missing packager
  platform/config/environments/development.json
Labels: Type: Bug, cla: yes

#1872 <amp-story> is no longer experimental
  pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/index.md
Labels: cla: yes

#1873 Updating bio, title, session title and description
  pages/shared/data/amp-conf.yaml
Labels: cla: yes

#1864 🐛 brought back categories for ad samples
  examples/source/interactivity-dynamic-content/Slides_Ad.html
  examples/source/interactivity-dynamic-content/Stack_With_Bind_Ad.html
  examples/source/multimedia-animations/Scrollbound_Video_Ad.html
  examples/source/multimedia-animations/Video_Ad.html
  examples/source/style-layout/Banner_Ad.html
  examples/source/style-layout/Carousel_Ad.html
  examples/source/style-layout/Lightbox_Ad.html
  examples/source/visual-effects/Scrollbound_Animation_Ad.html
Labels: P1: High, Type: Bug, cla: yes

#1869 Update URL for attribute 'config'
  examples/source/1.components/amp-call-tracking.html
Labels: cla: no

#1876 🐛Normalize sitemap paths
  frontend/templates/layouts/sitemap.xml
  pages/content/amp-dev/404.html
  pages/content/amp-dev/500.html
  pages/content/amp-dev/offline.html
  pages/content/shared/_blueprint.yaml
  pages/content/shared/footer.html
  pages/content/shared/header.html
  platform/config/podspec.yaml
Labels: Category: Infrastructure, P0: Critical, cla: yes

#1875 Add governance shortlink
  platform/config/go-links.yaml
Labels: cla: yes

#1878 📌 Update to Grow 0.7.4.
  .travis.yml
  frontend/templates/layouts/default.j2
  frontend/templates/layouts/sitemap.xml
  frontend/templates/views/partials/banner.j2
  frontend/templates/views/partials/breadcrumbs.j2
  frontend/templates/views/partials/burger-menu.j2
  frontend/templates/views/partials/case-grid.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/footer.j2
  frontend/templates/views/partials/format-toggle.j2
  frontend/templates/views/partials/fragment-slider-texts.j2
  frontend/templates/views/partials/header.j2
  frontend/templates/views/partials/kpis.j2
  frontend/templates/views/partials/resources-grid.j2
  frontend/templates/views/partials/structured-data.j2
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/404.html
  pages/content/amp-dev/500.html
  pages/extensions/amp_dev/extension.py
  platform/config/podspec.yaml
Labels: Category: Infrastructure, Type: Update, cla: yes

#1863 💬 Update Guides & Tutorial landing pages.
  frontend/scss/components/templates/docs-guides-overview.scss
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.websites.html
Labels: Category: Content, P3: Low, Site: amp.dev, Type: Update, cla: yes

#1874 ✨ Add shortcode for format filtering.
  frontend/templates/layouts/default.j2
  pages/extensions/amp_dev/extension.py
  pages/extensions/amp_dev/markdown_extras/block_filter.py
Labels: Category: Functionality, P1: High, Site: amp.dev, Type: New, cla: yes

#1828 remove duplicate tip
  examples/source/1.components/amp-install-serviceworker.html
Labels: cla: yes

#1886 🎨 Tidy up and bring livestreams to AMP Conf pages.
  frontend/scss/components/molecules/conf-location.scss
  frontend/scss/components/molecules/conf-speaker.scss
  frontend/scss/components/molecules/faq.scss
  frontend/scss/components/molecules/jumpto-item.scss
  frontend/scss/components/molecules/language-selector.scss
  frontend/scss/components/molecules/roadshow-video.scss
  frontend/scss/components/organisms/ampconf-footer.scss
  frontend/scss/components/organisms/jumpto-list.scss
  frontend/scss/components/organisms/stage-amp-conf.scss
  frontend/scss/components/templates/events.scss
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
  pages/shared/data/amp-conf.yaml
Labels: Category: Content, P1: High, Site: amp.dev, Type: Update, cla: yes

#1885 Update speakers for email talk
  pages/shared/data/amp-conf.yaml
  pages/static/img/amp-conf/speakers/anirudhkhanna.jpg
  pages/static/img/amp-conf/speakers/filip.jpg
  pages/static/img/amp-conf/speakers/michaelwuergler.jpg
Labels: Category: Content, P1: High, Site: amp.dev, Type: Update, cla: yes

#1884 ✨ Small UX improvements.
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/breadcrumbs.j2
  frontend/templates/views/partials/structured-data.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/_blueprint.yaml
Labels: Category: UX, Site: amp.dev, Type: Update, cla: yes

#1839 added signed exchange documentation
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
  pages/static/img/docs/guides/sxg/signedexchange.jpg
  pages/static/img/docs/guides/sxg/sxg.png
  pages/static/img/docs/guides/sxg/sxg1.jpg
  pages/static/img/docs/guides/sxg/sxg2.jpg
  pages/static/img/docs/guides/sxg/sxg3.jpg
Labels: cla: no

#1895 Remove gplus from amp-social-share
  examples/source/1.components/amp-social-share.html
Labels: cla: yes

#1893 🐛 fixe aspect ratio for teaser examples
  frontend/scss/components/molecules/teaser-example.scss
Labels: P2: Medium, Type: Bug, cla: yes

#1900 Add Shopify shortlink
  platform/config/go-links.yaml
Labels: cla: yes

#1897 White space removal from "Dev Ops".
  pages/content/amp-dev/events/amp-conf-2019@ja.html
Labels: cla: yes

#1901 🐛 fixed aspect ratio issue with news cards
  frontend/scss/components/organisms/news.scss
Labels: P2: Medium, Type: Bug, cla: yes

#1666 added amp script guide
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
Labels: Category: Documentation, Site: amp.dev, Type: New, cla: yes

#1905 🍏 fix text overlap for rolling animation
  frontend/scss/components/molecules/rolling-formats.scss
Labels: P2: Medium, Type: Bug, cla: yes

#1906 ♿️ added prefers reduced motion for caseband
  frontend/scss/components/organisms/case-band.scss
Labels: Category: UX, P1: High, Type: Update, cla: yes

#1907 add link to about section
  pages/content/amp-dev/about/websites.html
Labels: cla: yes

#1909 Update signed-exchange.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#1911 Remove title from email template
  playground/src/runtime/templates/email.template.html
Labels: cla: yes

#1918 Feature/fix animation ios
  frontend/scss/components/molecules/rolling-formats.scss
Labels: P1: High, Type: Bug, cla: yes

#1912 💬 Update amp.dev for AMP Conf Day 2.
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity_data/using_javascript.md
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
Labels: Category: Content, P0: Critical, Site: amp.dev, Type: Update, cla: yes

#1915 Include videos in courses page, other minor changes
  frontend/scss/components/templates/courses-overview.scss
  frontend/templates/views/partials/sidebar.j2
  pages/content/amp-dev/documentation/courses/index.html
  pages/content/amp-dev/documentation/courses/teachers.md
Labels: cla: no

#1908 🐛 Stop injecting unused deps into home.
  frontend/templates/views/partials/format-visuals/ads.j2
  frontend/templates/views/partials/format-visuals/email.j2
  frontend/templates/views/partials/format-visuals/stories.j2
  frontend/templates/views/partials/format-visuals/websites.j2
Labels: Category: Infrastructure, P1: High, Site: amp.dev, cla: yes

#1920 💬 Prepare AMP Conf 2019 page for after conf.
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
Labels: Category: Content, P1: High, Site: amp.dev, Type: Update, cla: yes

#1917 🎨 Verify release tag prior build.
  gulpfile.js/deploy.js
  platform/lib/utils/sh.js
Labels: Category: Infrastructure, P3: Low, Site: amp.dev, Type: Update, cla: yes

#1925 don't send a full html page for non html requests
  platform/lib/routers/notFound.js
Labels: cla: yes

#1923 Fix amp-ad's A9 parameter
  examples/source/1.components/amp-ad.html
Labels: cla: yes

#1927 🔥 Remove duplicate AMP HTML Layout guide.
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/introduction.md
Labels: Category: Content, cla: yes

#1928 increate keepAliveTimeout
  platform/lib/platform.js
Labels: cla: yes

#1929 💄 Improve responsive behaviour for AMP Conf page.
  frontend/scss/components/organisms/jumpto-list.scss
  frontend/scss/components/templates/events.scss
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
Labels: cla: yes

#1930 log health checks
  platform/lib/platform.js
Labels: cla: yes

#1931 use a bigger machine
  gulpfile.js/deploy.js
Labels: cla: yes

#1934 ✨ Add timer to express.
  platform/lib/platform.js
Labels: cla: yes

#1936 add lru cache for recently used pages
  package-lock.json
  package.json
  platform/lib/routers/pages.js
Labels: cla: yes

#1938 ♻️ Use route instead of middleware for pages.
  platform/lib/routers/pages.js
Labels: cla: yes

#1939 🎨 Use seconds over milliseconds, log critical times
  platform/lib/platform.js
Labels: cla: yes

#1940 Fix/docker image
  Dockerfile
  gulpfile.js/deploy.js
Labels: cla: yes

#1942 Fix/500 error message
  platform/lib/platform.js
  platform/lib/routers/pages.js
Labels: cla: yes

#1943 Improve subdomain
  examples/static/samples/standalone/amp-story/index.html
  gulpfile.js/deploy.js
  platform/lib/middleware/subdomain.js
  platform/lib/platform.js
  platform/lib/routers/packager.js
Labels: cla: yes

#1945 avoid double subdomains in logs
  platform/lib/platform.js
Labels: cla: yes

#1946 Fix incorrect condition
  platform/lib/middleware/subdomain.js
Labels: cla: yes

#1948 migrate to internal packager
  platform/config/environments/production.json
Labels: cla: yes

#1947 ♻️ Statically format filter pages.
  .dockerignore
  .gcloudignore
  platform/lib/build/pageTransformer.js
  platform/lib/common/filteredPage.js
  platform/lib/common/referrerNotification.js
  platform/lib/pipeline.js
  platform/lib/routers/pages.js
  platform/lib/utils/project.js
Labels: cla: yes

#1950 🐛 Correctly build amphtml URL.
  platform/lib/build/pageTransformer.js
Labels: cla: yes

#1953 add trailing slash to amphtml ref
  platform/lib/build/pageTransformer.js
Labels: cla: yes

#1955 fix path for real
  platform/lib/build/pageTransformer.js
Labels: cla: yes

#1956 Measure mean transform times
  package-lock.json
  package.json
  platform/lib/build/pageTransformer.js
  platform/lib/pipeline.js
Labels: cla: yes

#1957 fix amp pages not written to dist
  platform/lib/build/pageTransformer.js
Labels: cla: yes

#1959 use new page dest folder
  platform/lib/utils/project.js
Labels: cla: yes

#1960 🐛 Only ignore pages folder in project root
  .dockerignore
  .gcloudignore
Labels: cla: yes

#1961 limit to a single instance
  app.yaml
Labels: cla: yes

#1962 Small fixes
  frontend/templates/views/examples/preview.j2
  gulpfile.js/deploy.js
  platform/lib/platform.js
Labels: cla: yes

#1966 cache serviceworker in CDN for 10min
  platform/lib/routers/static.js
  platform/lib/utils/cacheHelpers.js
Labels: cla: yes

#1967 add max-age for requests with query param
  examples/api/echo.js
  examples/api/hello.js
  examples/api/photo-stream.js
Labels: cla: yes
