Repository ampproject/amp.dev, pull requests merged in 2019-02, with the labels that each got.

#1384 🔧 Enable all languages to be built
  platform/config/podspec.yaml
Labels: Category: Infrastructure, Category: Localization

#1386 🚑 Use unicode literals all over the place
  pages/extensions/amp_dev/__init__.py
  pages/extensions/amp_dev/markdown_extras/__init__.py
  pages/extensions/amp_dev/markdown_extras/block_video.py
Labels: Category: Localization, Type: Bug

#1387 Format filter on request instead of statically
  platform/build.js
  platform/lib/build/formatFilter.js
  platform/lib/common/filteredPage.js
  platform/lib/pipeline.js
  platform/lib/routers/pages.js
  platform/lib/utils/project.js
Labels: Category: Infrastructure

#1391 🗯 Make copy changes to home, email, websites
  frontend/templates/views/detail/success-story-detail.j2
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/websites.html
  pages/content/amp-dev/index.html
Labels: Category: Content

#1400 🎨Dynamically render benefits from a yaml data source
  frontend/icons/prev-arrow.svg
  frontend/scss/_mixins.scss
  frontend/scss/components/molecules/kpi.scss
  frontend/scss/components/organisms/fragment-slider-controls.scss
  frontend/scss/components/organisms/kpi-list.scss
  frontend/templates/views/partials/kpis.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/websites.html
  pages/content/amp-dev/index.html
  pages/content/shared/data/benefits.yaml
Labels: Category: Functionality

#1395 💄 change cookie layer from left to right
  frontend/scss/components/organisms/consent.scss
Labels: Category: UX

#1403 ◀️Feature/kpi stories integration
  frontend/scss/components/templates/what-is-amp.scss
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/websites.html
Labels: Category: UX

#1405 Template fixes and 2 new templates
  pages/content/amp-dev/documentation/templates/app_install_ads.yaml
  pages/content/amp-dev/documentation/templates/multi_image_ads.yaml
  pages/content/amp-dev/documentation/templates/single_image_ads.yaml
  pages/content/amp-dev/documentation/templates/single_video_ads.yaml
  pages/content/amp-dev/documentation/templates/text.yaml
  pages/static/files/templates/app_install_ads.zip
  pages/static/files/templates/multi-image-ads.zip
  pages/static/files/templates/single-image-ads.zip
  pages/static/files/templates/single-video.zip
  pages/static/files/templates/text.zip
  pages/static/img/templates/single_video.gif
  pages/static/img/templates/text.png
Labels: Category: Content
