Repository ampproject/amp.dev, pull requests merged in 2019-12, with the labels that each got.

#3253 Don't transform URL if it contains <%
  platform/lib/config.js
Labels: cla: yes

#3250 ⚡️ Add caching layer for rendered templates
  package-lock.json
  package.json
  platform/lib/routers/growPages.js
  platform/lib/routers/whoAmI.js
  platform/lib/utils/pageCache.js
  platform/lib/utils/project.js
Labels: Category: Infrastructure, P1: High, Status: WIP, Type: Feature, cla: yes

#3257 fix typo
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#3259 Remove WP Stories editor while we're rebooting
  pages/shared/data/tools.yaml
Labels: cla: yes

#3254 Add go links for contribution process and I2I
  platform/config/go-links.yaml
Labels: cla: yes

#3262 Update messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
Labels: cla: yes

#3264 📓Update story ad docs
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/story_ads_best_practices.md
Labels: cla: yes

#3266 update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#3234 💬 Add complex.com success story
  pages/content/amp-dev/about/success-stories/complex.yaml
  pages/static/img/success-stories/complex/complex-logo.jpg
  pages/static/img/success-stories/complex/complex-screen-1.jpg
  pages/static/img/success-stories/complex/complex-screen-2.jpg
  pages/static/img/success-stories/complex/complex-teaser.jpg
Labels: Category: Content, P1: High, Type: New, cla: yes

#3267 Update amp-autocomplete documentation to include examples for "inline" and "query"
  examples/source/1.components/amp-autocomplete.html
Labels: cla: yes

#3276 adding translation guide for Brazilian Portuguese
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations@pt_BR.md
Labels: cla: yes

#3279 Feature/3263 translation pt br beginners course
  pages/content/amp-dev/documentation/courses/beginning-course/index@pt_BR.md
  pages/content/amp-dev/documentation/courses/teachers@pt_BR.md
Labels: cla: yes

#3280 amp-list rendering from amp-state height fix.
  examples/source/1.components/amp-list.html
Labels: cla: yes

#3236 Add dark mode sample
  examples/source/style-layout/Dark_Mode_Toggle.html
Labels: cla: yes

#3294 [Translate-ko] Add beginning-course index page
  pages/content/amp-dev/documentation/courses/beginning-course/index@ko.md
Labels: cla: yes

#3299 Remove experiment notes on `amp-autocomplete` documentation
  examples/source/1.components/amp-autocomplete.html
Labels: cla: yes

#3300 nit fix about custom JS
  pages/content/amp-dev/about/how-amp-works.html
Labels: cla: yes

#3303 fixed nit
  pages/content/amp-dev/about/how-amp-works.html
Labels: cla: yes

#3291 ♻️ Hardcode redis instances for page cache
  package.json
  platform/config/environments/production.json
  platform/config/environments/staging.json
  platform/lib/config.js
  platform/lib/utils/pageCache.js
Labels: cla: yes

#3304 🐛 Return absolute URLs for search results
  platform/lib/routers/search.js
Labels: cla: yes

#3261 Added eSputnik
  pages/shared/data/tools.yaml
  pages/static/img/tools/esputnik-logo.png
Labels: cla: yes

#3273 Updating amp-consent examples and showing opt-out behavior
  examples/api/amp-consent.js
  examples/source/user-consent/Advanced_User_Consent_Flow.html
  examples/source/user-consent/Client_Side_User_Consent_Flow.html
  examples/source/user-consent/External_User_Consent_Flow.html
  examples/source/user-consent/Geolocation-based_Consent_Flow.html
  examples/source/user-consent/Server_Side_User_Consent_Flow.html
  examples/source/user-consent/Story_User_Consent.html
  pages/static/sitemap/sitemap_ampbyexample.xml
  platform/config/amp-dev-redirects.yaml
Labels: cla: yes

#3311 contrib: improve issue template formatting
  .editorconfig
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/content.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/tool.md
Labels: cla: yes

#3310 Amp-consent geolocation playground example
  examples/source/user-consent/Geolocation-based_Consent_Flow.html
Labels: cla: yes

#3309 Import `release-schedule.md` into AMP.dev
  platform/config/imports/spec.json
Labels: cla: yes

#3316 Add Adobe Campaign
  pages/shared/data/tools.yaml
  pages/static/img/tools/adobe_campaign.png
Labels: cla: yes

#3319 clarified CSS byte limit
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index.md
Labels: cla: yes

#3302 added info on Ads animations
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/introduction_to_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics.md
Labels: cla: yes

#3326 meta: further refine issue template formatting
  .github/ISSUE_TEMPLATE/--content-proposal-.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/content.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/tool.md
Labels: Status: WIP, Type: Update, cla: yes
