Repository ampproject/amp.dev, pull requests merged in 2019-03, with the labels that each got.

#1401 💄 Decrease space in front of rolling formats
  frontend/scss/components/molecules/rolling-formats.scss
  frontend/templates/views/partials/rolling-formats.j2
Labels: Category: UX

#1416 Feature/navigation-flyout
  frontend/icons/code-examples.svg
  frontend/icons/components-flyout.svg
  frontend/icons/gradient-ads.svg
  frontend/icons/gradient-email.svg
  frontend/icons/gradient-stories.svg
  frontend/icons/gradient-websites.svg
  frontend/icons/guides-documents.svg
  frontend/icons/suitcase.svg
  frontend/scss/_mixins.scss
  frontend/scss/components/atoms/_color.scss
  frontend/scss/components/organisms/header.scss
  frontend/templates/views/partials/header.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/websites.html
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/templates/index.html
  pages/content/amp-dev/documentation/tools.html
Labels: Category: UX

#1404 Feature/sidebar to amp sidebar
  boilerplate/templates/styles/main.scss
  frontend/icons/sidebar-toggle.svg
  frontend/scss/components/atoms/headline.scss
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/atoms/video.scss
  frontend/scss/components/molecules/code-snippet.scss
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/molecules/tutorial-progress.scss
  frontend/scss/components/organisms/_sidebar.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/footer.scss
  frontend/scss/components/organisms/header.scss
  frontend/scss/components/organisms/mini-card-list.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/scss/components/organisms/toc.scss
  frontend/scss/components/organisms/translation-hint.scss
  frontend/scss/components/templates/_default.scss
  frontend/scss/components/templates/component-detail.scss
  frontend/scss/components/templates/component-overview.scss
  frontend/scss/components/templates/docs-detail.scss
  frontend/scss/components/templates/docs-guides-overview.scss
  frontend/scss/components/templates/guide.scss
  frontend/scss/components/templates/roadmap.scss
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/detail/guide-detail.j2
  frontend/templates/views/detail/template-detail.j2
  frontend/templates/views/detail/use-cases-detail.j2
  frontend/templates/views/examples/manual.j2
  frontend/templates/views/examples/overview.j2
  frontend/templates/views/overview/guides.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/content.j2
  frontend/templates/views/partials/format-toggle.j2
  frontend/templates/views/partials/sidebar-toggle-button.j2
  frontend/templates/views/partials/sidebar-toggle-observer.j2
  frontend/templates/views/partials/sidebar-toggle.j2
  frontend/templates/views/partials/sidebar.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: Category: Documentation, Category: UX

#1434 added amp roadshow to events
  frontend/icons/cities-map.svg
  frontend/icons/gradient-map.svg
  frontend/scss/_mixins.scss
  frontend/scss/_variables.scss
  frontend/scss/components/molecules/_event.scss
  frontend/scss/components/molecules/agenda-item.scss
  frontend/scss/components/molecules/amplify.scss
  frontend/scss/components/molecules/event.scss
  frontend/scss/components/molecules/faq.scss
  frontend/scss/components/molecules/jumpto-item.scss
  frontend/scss/components/molecules/roadshow-pillar.scss
  frontend/scss/components/molecules/roadshow-video.scss
  frontend/scss/components/molecules/visited-city.scss
  frontend/scss/components/organisms/agenda.scss
  frontend/scss/components/organisms/cities.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/consent.scss
  frontend/scss/components/organisms/jumpto-list.scss
  frontend/scss/components/organisms/roadshow-content.scss
  frontend/scss/components/organisms/stage.scss
  frontend/scss/components/templates/custom-content.scss
  pages/content/amp-dev/events/_blueprint.yaml
  pages/content/amp-dev/events/amp-roadshow.html
  pages/content/shared/data/roadshow.yaml
Labels: Category: Content

#1517 💬 Add Advance Create success story.
  pages/content/amp-dev/about/success-stories/advance_create.yaml
  pages/static/files/case-studies/advance_create.pdf
  pages/static/img/success-stories/advance_create/advance_create_1.jpg
  pages/static/img/success-stories/advance_create/advance_create_logo.png
  pages/static/img/success-stories/advance_create/advance_create_teaser.jpg
Labels: Category: Content, P3: Low, Type: New

#1536 🐛 fixed broken links to component reference
  pages/content/amp-dev/about/how-amp-works.html
Labels: Type: Bug

#1531 🔥 remove unused scss files
  frontend/scss/components/molecules/_load-more.scss
  frontend/scss/components/molecules/_teaser-obsolete.scss
  frontend/scss/components/templates/docs-quick-start.scss
  frontend/scss/components/templates/styleguide.scss
  frontend/scss/components/templates/success-story.scss
  frontend/scss/components/templates/tutorial.scss
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating.md
Labels: Type: Update

#1560 🐛 kpi list scrolling issue
  frontend/scss/components/organisms/kpi-list.scss
Labels: Type: Bug

#1541 🐛 fix broken icons on story carousel buttons
  frontend/scss/components/organisms/story-carousel.scss
Labels: Type: Bug

#1562 📱 fix text alignment for content with text layout
  frontend/scss/components/templates/success-story.scss
Labels: Type: Bug

#1563 📱 fixed roadshow video for responsive
  frontend/icons/cities-map.svg
  frontend/scss/components/molecules/_kpi.scss
  frontend/scss/components/molecules/_teaser.scss
  frontend/scss/components/molecules/kpi.scss
  frontend/scss/components/molecules/roadshow-video.scss
  frontend/scss/components/molecules/teaser-example.scss
  frontend/scss/components/organisms/cities.scss
  frontend/scss/components/organisms/news.scss
  frontend/scss/components/organisms/sampler.scss
  frontend/scss/components/organisms/teaser-grid.scss
  frontend/scss/components/templates/custom-content.scss
  frontend/scss/components/templates/what-is-amp.scss
  frontend/templates/views/detail/success-story-detail.j2
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/events/amp-roadshow.html
Labels: Type: Bug

#1582 Add new landingpages
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/organisms/banner.scss
  frontend/scss/components/organisms/card-grid.scss
  frontend/scss/components/organisms/footer.scss
  frontend/scss/components/organisms/format-cards.scss
  frontend/scss/components/organisms/resources-grid.scss
  frontend/scss/components/organisms/video-slider.scss
  frontend/scss/components/templates/docs-guides-overview.scss
  frontend/templates/views/partials/format-toggle.j2
  frontend/templates/views/partials/video-carousel.j2
  package-lock.json
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.websites.html
  platform/lib/common/filteredPage.js
  platform/lib/routers/pages.js
Labels: Category: Content, Category: Documentation, P1: High, Type: Update

#1575 Fixes a11y issues.
  frontend/scss/components/molecules/banner.scss
  frontend/scss/components/molecules/code-snippet.scss
  frontend/scss/components/organisms/news.scss
  frontend/templates/views/partials/burger-menu.j2
  frontend/templates/views/partials/case-grid.j2
  frontend/templates/views/partials/footer.j2
  frontend/templates/views/partials/format-visuals/websites.j2
  frontend/templates/views/partials/header.j2
  pages/content/amp-dev/index.html
Labels: Category: UX, P3: Low, Type: Update

#1590 Feature/stories content update
  frontend/scss/components/molecules/copy.scss
  frontend/scss/components/organisms/story-carousel.scss
  frontend/scss/components/templates/what-is-amp.scss
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/documentation/templates/single_image_ads.yaml
  pages/content/amp-dev/documentation/templates/single_video_ads.yaml
  pages/content/shared/data/benefits.yaml
  pages/static/img/templates/multiple-image-template.jpg
  pages/static/img/templates/single-image-template.gif
  pages/static/img/templates/single-image-template.jpg
  pages/static/img/templates/single-image-template.mp4
  pages/static/img/templates/single_video.gif
  pages/static/img/templates/single_video.jpg
  pages/static/img/templates/single_video.mp4
Labels: Category: Functionality

#1599 Perf documentation landing pages.
  frontend/scss/components/organisms/resources-grid.scss
  frontend/templates/views/partials/resources-grid.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.websites.html
  platform/lib/routers/pages.js
Labels: Category: Documentation, P0: Critical, Site: amp.dev, Type: Update

#1589 Feature/bug fixes
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/organisms/burger-menu.scss
  frontend/scss/components/organisms/jumpto-list.scss
  frontend/scss/components/templates/_default.scss
  frontend/scss/components/templates/events.scss
  frontend/scss/components/templates/meta.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/code-of-conduct.j2
  frontend/templates/views/meta.j2
  frontend/templates/views/partials/footer.j2
  frontend/templates/views/partials/meta.j2
  frontend/templates/views/partials/sidebar-toggle-button.j2
  pages/content/amp-dev/documentation/tools.html
  pages/content/amp-dev/events/amp-conf/accessibility.html
  pages/content/amp-dev/events/amp-conf/code-of-conduct.html
  pages/content/amp-dev/events/amp-roadshow.html
  pages/content/amp-dev/support/_blueprint.yaml
  pages/content/shared/data/benefits.yaml
Labels: Category: Functionality, Type: Bug

#1614 Improve examples.
  frontend/scss/components/molecules/homepage-link.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/templates/views/examples/preview.j2
  platform/lib/build/samplesBuilder.js
  platform/lib/platform.js
  platform/lib/routers/examples.js
Labels: Category: Examples, Site: amp.dev, Type: Update

#1619 ✨ Remove empty filter bubbles.
  frontend/templates/views/partials/category-filter.j2
  frontend/templates/views/partials/teaser.j2
  platform/lib/common/filteredPage.js
Labels: Category: UX, Site: amp.dev

#1620 ♻️ Use URL over raw strings to construct filtered URLs
  platform/lib/common/filteredPage.js
Labels: Category: Functionality, P0: Critical

#1622 💄 Rearrange sample preview header.
  frontend/scss/components/atoms/sample-preview-title.scss
  frontend/scss/components/molecules/device-toggle.scss
  frontend/scss/components/organisms/preview-pane.scss
  frontend/templates/views/examples/preview.j2
Labels: Category: Examples, Category: UX

#1625 ✨ brought back correct stories for about page
  pages/content/amp-dev/about/stories.html
Labels: Category: Content

#1628 🐛 Fix various glitches around component overview.
  frontend/scss/components/molecules/teaser-component.scss
  pages/translations/en/LC_MESSAGES/messages.po
  platform/lib/build/pageMinifier.js
  platform/lib/common/filteredPage.js
Labels: Category: UX, Site: amp.dev, Type: Bug, Type: Update

#1629 🐛 Explicitly add format to About Get Started links
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/websites.html
Labels: Category: UX, Site: amp.dev, Type: Bug

#1641 ⚡️only include fadeTransition animation when sidebar is present
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/templates/docs-detail.scss
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/detail/guide-detail.j2
  frontend/templates/views/detail/template-detail.j2
  frontend/templates/views/detail/use-cases-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/overview/guides.j2
  frontend/templates/views/partials/footer.j2
  frontend/templates/views/partials/sidebar-toggle-visibility-observer.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: Category: Functionality, Type: Bug

#1644 🐛 Add missing blog link in burger menu.
  frontend/templates/views/partials/burger-menu.j2
Labels: Category: UX, P2: Medium, Site: amp.dev, Type: Bug

#1643 ✨ Add icon to tools page in flyout.
  pages/content/amp-dev/documentation/tools.html
Labels: Category: UX, Site: amp.dev, Type: New

#1646 🐛 Make example categories expandable by title.
  frontend/scss/components/organisms/_sidebar.scss
  frontend/templates/views/partials/example-sidebar.j2
Labels: Category: UX, P1: High, Site: amp.dev, Type: Bug

#1654 Fix broken email hello world sample
  examples/source/0.introduction/AMPHTML_Email_Hello_World.html
Labels: Category: Examples, P1: High, Site: amp.dev, Type: Bug

#1547 Fixing company name, bio and talk description
  content/includes/amp-conf.yaml
Labels: Site: ampproject.org
