Repository ampproject/amp.dev, pull requests merged in 2019-06, with the labels that each got.

#2209 added amp-script tutorial
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
  pages/static/img/docs/tutorials/custom-javascript-tutorial/checkpassfail.mp4
  pages/static/img/docs/tutorials/custom-javascript-tutorial/image1.jpg
  pages/static/img/docs/tutorials/custom-javascript-tutorial/image2.jpg
  pages/static/img/docs/tutorials/custom-javascript-tutorial/image3.jpg
Labels: cla: yes

#2229 added amp-script tutorial (#2209)
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
  pages/static/img/docs/tutorials/custom-javascript-tutorial/checkpassfail.mp4
  pages/static/img/docs/tutorials/custom-javascript-tutorial/image1.jpg
  pages/static/img/docs/tutorials/custom-javascript-tutorial/image2.jpg
  pages/static/img/docs/tutorials/custom-javascript-tutorial/image3.jpg
Labels: cla: yes

#2226 Remove amp-font from amp.dev, and don't recommend its usage any longer
  frontend/templates/layouts/default.j2
  frontend/templates/views/examples/documentation.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@zh_CN.md
Labels: cla: yes

#2217 Tools: Add Sendgrid and SES
  pages/content/amp-dev/documentation/tools.html
  pages/shared/data/tools.yaml
  pages/static/img/tools/aws-ses.svg
  pages/static/img/tools/sendgrid.png
Labels: cla: yes

#2206 Use binding=refresh|no in amp-list wherever possible
  boilerplate/templates/index.html
  examples/source/1.components/amp-bind.html
  examples/source/1.components/amp-list.html
  examples/source/1.components/amp-mustache.html
  examples/source/e-commerce/AMP_for_E-Commerce_Getting_Started.html
  examples/source/e-commerce/Checkout_Flow/index.html
  examples/source/e-commerce/Hotel.html
  examples/source/e-commerce/Housing.html
  examples/source/e-commerce/Product_Browse_Page.html
  examples/source/e-commerce/Product_Page.html
  examples/source/e-commerce/Shopping_Cart.html
  examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
  examples/source/interactivity-dynamic-content/Autosuggest_form.html
  examples/source/interactivity-dynamic-content/Favorite_Button/index.html
  examples/source/interactivity-dynamic-content/Linked_Dropdowns.html
  examples/source/interactivity-dynamic-content/SeatMap.html
  examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection.html
  examples/source/interactivity-dynamic-content/Show_More_Button.html
  examples/source/interactivity-dynamic-content/Simple_Autosuggest.html
  examples/source/multimedia-animations/Custom_Loading_Indicators.html
  examples/source/news-publishing/News_Article.html
  examples/source/news-publishing/Recipe.html
  examples/source/personalization/Geolocation_with_amp-list.html
  examples/source/user-consent/Advanced_User_Consent_Flow.html
  examples/source/user-consent/Basic_User_Consent_Flow.html
  examples/static/samples/files/Product_Browse_Page.html
  examples/static/samples/standalone/amp-website/index.html
  pages/content/amp-dev/documentation/courses/advanced-course/loading-and-displaying-server-content.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/seatmap.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-format.md
Labels: Status: Blocked, cla: yes

#2213 ♻️ Migrate paged_list API to amp.dev
  examples/source/interactivity-dynamic-content/Paged_List/api.js
  examples/source/interactivity-dynamic-content/Paged_List/index.html
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#2196 🐛 Correct links to specific experiments
  examples/source/1.components/amp-experiment.html
  gulpfile.js/develop.js
Labels: Category: Examples, cla: yes

#2212 Implement grow extension to convert example code
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/code-preview/code-preview.j2
  gulpfile.js/build.js
  jest.config.js
  package.json
  pages/content/tests/_blueprint.yaml
  pages/content/tests/examples/_blueprint.yaml
  pages/content/tests/examples/default_settings.md
  pages/content/tests/examples/example_with_comments.md
  pages/content/tests/examples/full_html.md
  pages/content/tests/examples/head_style.md
  pages/content/tests/examples/import.md
  pages/content/tests/examples/multi_examples.md
  pages/content/tests/examples/no_playground.md
  pages/content/tests/examples/no_preview.md
  pages/content/tests/examples/preview_inline.md
  pages/content/tests/examples/template.md
  pages/extensions/amp_dependency_injector/amp_dependency_injector.py
  pages/extensions/amp_dev/extension.py
  pages/extensions/amp_dev/post_processors/__init__.py
  pages/extensions/amp_example_preview/__init__.py
  pages/extensions/amp_example_preview/amp_example_preview.py
  pages/extensions/amp_example_preview/util/__init__.py
  pages/extensions/amp_example_preview/util/constants.py
  pages/extensions/amp_example_preview/util/example_extractor.py
  pages/extensions/amp_example_preview/util/markdown_processor.py
  pages/extensions/amp_example_preview/util/preview.py
  pages/extensions/amp_example_preview/util/preview_generator.py
  platform/config/podspec.yaml
  platform/lib/config.js
  platform/lib/config.test.js
  tests/pages/examples/default-settings.spec.js
  tests/readme.md
Labels: cla: yes

#2245 update dependencies
  package-lock.json
  package.json
  playground/webpack.config.js
Labels: cla: yes

#2239 Fix/sidebar
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/detail/guide-detail.j2
  frontend/templates/views/detail/template-detail.j2
  frontend/templates/views/detail/use-cases-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/overview/courses.j2
  frontend/templates/views/overview/guides.j2
  frontend/templates/views/partials/sidebar-toggle-button.j2
  frontend/templates/views/partials/sidebar-toggle-observer.j2
  frontend/templates/views/partials/sidebar-toggle-visibility-observer.j2
  frontend/templates/views/partials/sidebar-toggle.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: cla: yes

#2247 🐛 Fix broken amp-form sample
  examples/source/1.components/amp-form.html
Labels: Category: Examples, P1: High, Type: Bug, cla: yes

#2237 ✨ List experiments on experiments page
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
Labels: Category: Documentation, P2: Medium, Type: Update, cla: yes

#2252 ✨ Add credentials util.
  package-lock.json
  package.json
  platform/lib/config.js
  platform/lib/utils/credentials.js
Labels: cla: yes

#2253 Fix/sidebar
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/organisms/_sidebar.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/header.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/scss/components/templates/_default.scss
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/sidebar.j2
Labels: cla: yes

#2204 Add new AMP for Email spec pages
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
  platform/config/amp-dev-redirects.yaml
  platform/config/imports/spec.json
Labels: cla: yes

#2256 Shortlink for Shadow Reader AMP => AMP/PWA post
  platform/config/go-links.yaml
Labels: cla: yes

#2240 ♻️ Migrate slow-response API to amp.dev
  examples/api/slow-response.js
  examples/source/1.components/amp-list.html
  examples/source/multimedia-animations/Custom_Loading_Indicators.html
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#2259 How to include code samples in lists
  MAINTENANCE.md
Labels: cla: yes

#2260 Let topic link 'Track engagement with analytics' open index page
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-tech@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@fr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@it.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@ru.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@tr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/index@zh_CN.md
Labels: cla: yes

#2249 ♻️ Migrate amp-form API to amp.dev
  examples/api/amp-form.js
  examples/source/1.components/amp-analytics.html
  examples/source/1.components/amp-autocomplete.html
  examples/source/1.components/amp-date-picker.html
  examples/source/1.components/amp-form.html
  examples/source/interactivity-dynamic-content/Conference_Survey_Email.html
  examples/source/interactivity-dynamic-content/Multi_Page_Flow.html
  examples/static/samples/files/amp-form-success.html
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#2266 Fix/sidebar
  frontend/scss/base.scss
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/organisms/toc.scss
  frontend/scss/components/templates/_default.scss
  frontend/scss/components/templates/component-overview.scss
Labels: cla: yes

#2244 Explain AMP server-side-rendering
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/server-side-rendering.md
  pages/static/img/docs/guides/optimized-amp-diff.png
Labels: cla: yes

#2270 🐛 Fix amp-addthis floating example
  examples/source/1.components/amp-addthis.html
Labels: Category: Examples, P2: Medium, Site: amp.dev, Type: Bug, cla: yes

#2279 🐛 Bookend in AMP Story samples are back
  examples/source/advertising-analytics/Doubleclick_AMP_Story_Ads.html
  examples/source/multimedia-animations/Supported_media_types_in_AMP_Stories.html
  examples/source/style-layout/AMP_Story_Layouts.html
  examples/source/user-consent/Story_User_Consent.html
  examples/source/visual-effects/AMP_Story_Animations.html
  examples/source/visual-effects/Ken_Burns.html
Labels: cla: yes

#2278 🐛 Fix amp-form verification example
  examples/api/amp-form.js
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#2265 Align path "optimize-and-measure" and improve redirect logic
  jest.config.js
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/_blueprint.yaml
  platform/config/amp-dev-redirects.yaml
  platform/lib/config.js
  platform/lib/middleware/redirects.js
  platform/lib/middleware/redirects.test.js
Labels: cla: yes

#2283 Fix the <amp-video> HLS sample
  examples/source/1.components/amp-video.html
Labels: cla: yes

#2281 started contribution guide
  README.md
  contributing/documentation.md
  contributing/samples.md
Labels: cla: yes

#2262 Fix sitemap 404
  platform/lib/routers/pages.js
  platform/lib/routers/pages.test.js
  platform/lib/routers/static.js
Labels: cla: yes

#2291 🐛 Update link to platform and vendors page
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
Labels: cla: yes

#2292 💬 Add Distributed Media Lab to Platform & Vendor partners
  pages/content/amp-dev/community/platform-and-vendor-partners.html
Labels: cla: yes

#2200 Update amp-autocomplete rich content example
  examples/source/1.components/amp-autocomplete.html
Labels: Status: Blocked, cla: yes

#2302 Fix/invalid sidebar
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/sidebar.j2
Labels: cla: yes

#2299 ♻️ Update echo API endpoint
  examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
Labels: Category: Examples, P3: Low, Site: amp.dev, Type: Bug, cla: yes

#2301 🐛Replace broken links to stories #2287
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_story_best_practices.md
Labels: cla: yes

#2242 Delete autosuggest examples and redirect to autocomplete
  examples/source/1.components/amp-autocomplete.html
  examples/source/interactivity-dynamic-content/Autosuggest_form.html
  examples/source/interactivity-dynamic-content/ComboBox.html
  examples/source/interactivity-dynamic-content/Simple_Autosuggest.html
  platform/config/amp-dev-redirects.yaml
Labels: Status: Blocked, cla: yes

#2296 Remove old long form name of AMP everywhere
  pages/content/amp-dev/about/success-stories/advance_create.yaml
  pages/content/amp-dev/about/success-stories/carved.yaml
  pages/content/amp-dev/about/success-stories/discover_car_hire.yaml
  pages/content/amp-dev/about/success-stories/fastcommerce.yaml
  pages/content/amp-dev/about/success-stories/greenweez.yaml
  pages/content/amp-dev/about/success-stories/grupo.yaml
  pages/content/amp-dev/about/success-stories/jagran.yaml
  pages/content/amp-dev/about/success-stories/readwhere.yaml
  pages/content/amp-dev/about/success-stories/relay_media.yaml
  pages/content/amp-dev/about/success-stories/slate.yaml
  pages/content/amp-dev/about/success-stories/tokopedia.yaml
  pages/content/amp-dev/about/success-stories/transunion.yaml
  pages/content/amp-dev/about/success-stories/triplelift.yaml
  pages/content/amp-dev/about/success-stories/us_xpress.yaml
  pages/content/amp-dev/about/success-stories/washingtonpost.yaml
  pages/content/amp-dev/about/success-stories/wego.yaml
  pages/content/amp-dev/documentation/examples/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@fr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@it.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@ru.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@tr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages@zh_CN.md
Labels: cla: yes

#2300 🐛 Fix broken image URLs
  examples/source/news-publishing/News_Article.html
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#2290 Incorrect API url on remote-data tutorial (#2289)
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@zh_CN.md
Labels: cla: yes

#2297 🐛 Fix error message response
  examples/api/amp-form.js
Labels: Category: Examples, Site: amp.dev, Type: Bug, cla: yes

#2263 Do not build grow tests for production
  gulpfile.js/build.js
  package.json
  platform/lib/config.js
Labels: cla: yes

#2298 ♻️ Migrate amp-consent API to amp.dev
  examples/api/amp-consent.js
  examples/source/user-consent/Advanced_User_Consent_Flow.html
  examples/source/user-consent/Basic_User_Consent_Flow.html
  examples/source/user-consent/External_User_Consent_Flow.html
Labels: Category: Examples, Site: amp.dev, cla: yes

#2314 Correct autocomplete redirect path
  platform/config/amp-dev-redirects.yaml
Labels: cla: yes

#2317 🐛 Fix src of story image and video
  examples/source/multimedia-animations/Supported_media_types_in_AMP_Stories.html
Labels: cla: yes

#2315 Fix code snipped running out of background container
  frontend/scss/components/molecules/code-snippet.scss
Labels: cla: yes

#2316 Tweak tools page styling and structure
  frontend/scss/components/atoms/grid-toggle.scss
  frontend/scss/components/organisms/tools-teaser.scss
  frontend/scss/components/templates/_default.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
  pages/shared/data/tools.yaml
Labels: cla: yes

#2319 💄Remove gradient from code-snippets
  frontend/scss/components/molecules/code-snippet.scss
  frontend/scss/components/organisms/code-preview.scss
  playground/src/editor/editor.scss
Labels: cla: yes

#2318 🐛 Add and edit padding to the help section
  frontend/scss/components/molecules/tip.scss
  frontend/scss/components/organisms/help.scss
  frontend/scss/components/templates/component-detail.scss
Labels: cla: yes

#2310 Re-add city markers to roadshow map
  frontend/icons/cities-map-pin.svg
  frontend/icons/cities-map.svg
  frontend/scss/components/molecules/visited-city.scss
  frontend/scss/components/organisms/cities.scss
  pages/content/amp-dev/events/amp-roadshow.html
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2320 ♻️ Migrate amphtml-email API to amp.dev
  examples/source/interactivity-dynamic-content/Article_Bookmark_Email/api.js
  examples/source/interactivity-dynamic-content/Article_Bookmark_Email/index.html
Labels: Category: Examples, Site: amp.dev, cla: yes

#2330 Fix format-toggle dropdown-list too wide on safari
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/molecules/format-toggle.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/scss/components/templates/component-overview.scss
Labels: cla: yes

#2321 🐛 replaced mentions to ampstart.com
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/congratulations@zh_CN.md
Labels: cla: yes

#2322 Fix header and navigation styling issues
  frontend/scss/_variables.scss
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/molecules/banner.scss
  frontend/scss/components/organisms/burger-menu.scss
  frontend/scss/components/organisms/footer.scss
  frontend/scss/components/organisms/header.scss
  frontend/templates/views/partials/banner.j2
  frontend/templates/views/partials/header.j2
Labels: cla: no

#2335 Examples playground links: section separator + no link for head snippets
  frontend/templates/views/examples/documentation.j2
Labels: cla: yes

#2336 Fix broken link in carousel example
  examples/source/1.components/amp-carousel.html
Labels: cla: yes

#2342 Add tools and email-tools redirects
  platform/config/go-links.yaml
Labels: cla: yes

#2348 ✏️ remove space in order to fix link
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@es.md
Labels: cla: yes

#2305 Fix broken links in AMP for Email Fundamentals
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/setting_up.md
Labels: cla: yes

#2329 Implement extraction of inline examples and playground link
  contributing/documentation.md
  frontend/templates/layouts/example-pages/amp-ads-page.j2
  frontend/templates/layouts/example-pages/amp-email-page.j2
  frontend/templates/layouts/example-pages/amp-stories-page.j2
  frontend/templates/layouts/example-pages/amp-websites-page.j2
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/partials/code-preview/code-preview.j2
  package-lock.json
  package.json
  pages/content/tests/examples/example_with_comments.md
  pages/content/tests/examples/full_html.md
  pages/content/tests/examples/head_style.md
  pages/extensions/amp_example_preview/standalone_example_validator.py
  pages/extensions/amp_example_preview/util/amp_component_versions.py
  pages/extensions/amp_example_preview/util/constants.py
  pages/extensions/amp_example_preview/util/example_document.py
  pages/extensions/amp_example_preview/util/example_document_test.py
  pages/extensions/amp_example_preview/util/example_exporter.py
  pages/extensions/amp_example_preview/util/example_exporter_test.py
  pages/extensions/amp_example_preview/util/example_extractor.py
  pages/extensions/amp_example_preview/util/example_extractor_test.py
  pages/extensions/amp_example_preview/util/markdown_processor.py
  pages/extensions/amp_example_preview/util/preview.py
  pages/extensions/amp_example_preview/util/preview_generator.py
  pages/extensions/amp_example_preview/util/preview_test.py
  pages/extensions/amp_example_preview/util/templates.py
  pages/extensions/amp_example_preview/util/unit-test/podspec.yaml
  pages/extensions/jinja2_optimized_codehilite/__init__.py
  pages/extensions/jinja2_optimized_codehilite/custom_html_formatter.py
  pages/extensions/jinja2_optimized_codehilite/custom_html_lexer.py
  pages/extensions/jinja2_optimized_codehilite/jinja2_expression_unescape.py
  pages/extensions/jinja2_optimized_codehilite/jinja2_optimized_codehilite.py
  platform/config/podspec.yaml
  platform/lib/common/filteredPage.js
  platform/lib/config.js
  platform/lib/platform.js
  platform/lib/routers/inlineExamples.js
  platform/lib/routers/pages.test.js
  platform/lib/utils/project.js
Labels: Category: Documentation, P1: High, Type: Feature, cla: yes

#2352 Tools: Add React Storefront framework to the developer tools.
  pages/shared/data/tools.yaml
  pages/static/img/docs/tools/react-storefront.png
Labels: Category: Content, P2: Medium, Type: New, cla: no

#2337 ♻️ Migrate amp-access API to amp.dev
  examples/api/amp-access.js
  examples/source/1.components/amp-access.html
  examples/source/interactivity-dynamic-content/Comment_Section/index.html
  examples/static/samples/files/login.html
Labels: Category: Examples, cla: yes

#2304 💄 Style broken iframe-example
  examples/source/e-commerce/Product_Browse_Page.html
  examples/source/e-commerce/Product_Page.html
Labels: cla: yes

#2359 Migrate ampbyexample iframes to inline example
  frontend/templates/layouts/example-pages/amp-ads-page.j2
  frontend/templates/layouts/example-pages/amp-stories-page.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@fr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@it.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@ru.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@tr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design@zh_CN.md
Labels: cla: yes

#2358 Allows go-links.yaml to have regex based redirects
  platform/config/go-links.yaml
  platform/lib/routers/go.js
  platform/lib/routers/go.test.js
Labels: Category: UX, P2: Medium, Type: Feature, cla: yes

#2372 🎨 Add a link and a section with id to repair stage link
  pages/content/amp-dev/about/email.html
Labels: cla: yes

#2373 🎨 Change class name of section in examples and add styling
  frontend/scss/components/organisms/help.scss
  frontend/templates/views/examples/documentation.j2
Labels: cla: yes

#2384 Improve support for jinja2 code in markdown source blocks
  pages/extensions/jinja2_optimized_codehilite/custom_html_lexer.py
  pages/extensions/jinja2_optimized_codehilite/custom_js_lexer.py
  pages/extensions/jinja2_optimized_codehilite/jinja2_optimized_codehilite.py
  pages/extensions/jinja2_optimized_codehilite/readme.md
Labels: cla: yes

#2375 Fix typo and broken links in the contributing docs
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#2381 Fix mustache escaping in markdown and fix unit test lookup
  jest.config.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
Labels: cla: yes

#2380 Support inline preview for examples with [sourcecode] tags
  pages/extensions/amp_example_preview/util/example_extractor.py
  pages/extensions/amp_example_preview/util/example_extractor_test.py
  pages/extensions/amp_example_preview/util/preview.py
Labels: cla: yes

#2248 ♻️ Move logic from .travis.yml to bash scripts.
  .travis.yml
  travis_scripts/before_install.sh
  travis_scripts/deploy.sh
  travis_scripts/preparation.sh
Labels: Category: Infrastructure, cla: yes

#2390 Revert "♻️ Move logic from .travis.yml to bash scripts."
  .travis.yml
  travis_scripts/before_install.sh
  travis_scripts/deploy.sh
  travis_scripts/preparation.sh
Labels: cla: yes

#2383 Added Tic-tac-toe sample (Issue #2338)
  examples/source/interactivity-dynamic-content/Tic_Tac_Toe.html
  examples/static/samples/img/teaser/tictactoe.png
Labels: Category: Examples, P1: High, Type: New, cla: yes

#2393 🐛Fix credentials util
  platform/lib/utils/credentials.js
Labels: P1: High, Type: Bug, cla: yes

#2377 🌠 Add comments to imported files with link to source-file
  pages/content/amp-dev/community/governance.md
  pages/content/amp-dev/documentation/components/reference/amp-accordion.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/ad-integration-guide.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/a4a_spec.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-debugging.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-html.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
  pages/content/amp-dev/support/index.md
  pages/shared/data/blog.yaml
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/specImporter.js
Labels: cla: yes

#2363 WIP: AMP Contributors Summit 2019 Event Page
  pages/content/amp-dev/events/_blueprint.yaml
  pages/content/amp-dev/events/amp-cs-2019.html
  pages/shared/data/amp-cs-2019.yaml
Labels: Category: Content, P2: Medium, Status: WIP, Type: New, cla: yes

#2391 Added Mailgun email service to tools #2331
  pages/shared/data/tools.yaml
  pages/static/img/tools/mailgun.png
Labels: Category: Content, P2: Medium, Type: New, cla: yes
