Repository ampproject/amp.dev, pull requests merged in 2019-10, with the labels that each got.

#3047 Kiev => Kyiv, and more
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3050 Compress CSS using csso
  package-lock.json
  package.json
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md
  platform/lib/routers/growPages.js
  platform/lib/utils/cssTransformer.js
Labels: cla: yes

#3051 Go links for AMP roadshow tutorials
  platform/config/go-links.yaml
Labels: cla: yes

#3054 Ensure whitespace is aligned correctly when parsing samples
  examples/source/1.components/amp-video.html
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#3056 Better go links for AMP roadshow tutorials
  platform/config/go-links.yaml
Labels: cla: yes

#2981 Added Maileon email service to tools
  pages/shared/data/tools.yaml
  pages/static/img/tools/maileon.png
Labels: cla: yes

#3060 update docs to point out examples
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
Labels: cla: yes

#3070 Added AdGlare to the list of Ad Server vendors.
  pages/shared/data/faq.yaml
Labels: cla: yes

#3066 Updates the AMP Contributor Summit schedule
  pages/content/amp-dev/events/amp-cs-2019.html
  pages/shared/data/amp-cs-2019.yaml
Labels: cla: yes

#3058 update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#3071 Adds a go link for AMP's Working Groups
  platform/config/go-links.yaml
Labels: cla: yes

#3072 🐛 Point issue reporters to amphtml instead of amp.dev
  pages/content/amp-dev/index.html
Labels: cla: yes

#3061 support query params
  packager/amppkg.toml
Labels: cla: yes

#3059 💄 Implement UI fixes for iPhone 5/SE
  frontend/scss/components/atoms/headline.scss
  frontend/scss/components/molecules/teaser-component-code.scss
  frontend/scss/components/molecules/teaser-component.scss
  frontend/scss/components/molecules/teaser-guides.scss
  frontend/scss/components/molecules/teaser-highlight-guides.scss
  frontend/scss/components/organisms/format-cards.scss
  frontend/scss/components/organisms/resources-grid.scss
  frontend/scss/components/organisms/resources-overview.scss
Labels: Category: UX, P2: Medium, Type: Bug, cla: yes

#3052 added go links for presentation
  platform/config/go-links.yaml
Labels: cla: yes

#3073 :fire: Disable animation for standalone preview
  frontend/scss/components/organisms/code-preview.scss
  frontend/templates/views/partials/code-preview/code-preview.j2
Labels: Category: UX, P2: Medium, Type: Bug, cla: yes

#3074 Update the location information for the AMP Contributor Summit
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#3079 Change Kyiv roadshow date
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3076 Fix sample doc pages not validating
  platform/lib/routers/growPages.js
  platform/lib/utils/HeadDedupTransformer.js
  platform/lib/utils/HeadDedupTransformer.test.js
Labels: cla: yes

#3080 💄 Optimize spacing at the end of line in code-snippets
  frontend/scss/components/molecules/code-snippet.scss
Labels: Category: UX, P3: Low, Type: Bug, cla: yes

#3084 Add link for CS presentation
  platform/config/go-links.yaml
Labels: cla: yes

#3064 Include OS-specific pip setup instructions
  README.md
Labels: cla: yes

#3098 Add timestamp to deploy tag
  gulpfile.js/deploy.js
Labels: cla: yes

#3105 Add go.amp.dev/learn-email and go.amp.dev/test-email
  platform/config/go-links.yaml
Labels: cla: yes

#3097 add idealmedia to ad vendors
  pages/shared/data/faq.yaml
Labels: cla: yes

#3095 add mgid to ad vendors
  pages/shared/data/faq.yaml
Labels: cla: yes

#3092 ✨ Implement the experiment toggle in standalone sample preview
  frontend/scss/components/molecules/device-toggle.scss
  frontend/scss/components/molecules/experiments.scss
  frontend/scss/components/organisms/preview-pane.scss
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/examples/preview.j2
  frontend/templates/views/partials/experiments/experiments-controls.j2
  frontend/templates/views/partials/experiments/experiments-script.j2
  frontend/templates/views/partials/experiments/experiments.j2
  pages/content/shared/experiments.html
  platform/lib/platform.js
  platform/lib/routers/example/experiments.js
Labels: Category: UX, P2: Medium, Type: Feature, cla: yes

#3091 update deps
  package-lock.json
  package.json
Labels: cla: yes

#3108 fix sw paths
  examples/source/1.components/amp-install-serviceworker.html
Labels: cla: yes

#3112 Lower-case "Signed Exchange".
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
Labels: cla: yes

#3113 🐛 Fix FAQ teasers
  frontend/scss/components/molecules/teaser-faq.scss
Labels: Category: UX, P2: Medium, Type: Bug, cla: yes

#3109 Add AARP success story
  pages/content/amp-dev/about/success-stories/aarp.yaml
  pages/static/img/success-stories/aarp/aarp_1.png
  pages/static/img/success-stories/aarp/aarp_2.png
  pages/static/img/success-stories/aarp/aarp_logo.png
  pages/static/img/success-stories/aarp/aarp_teaser.png
Labels: Category: Content, Type: New, cla: yes

#3110 🐛 Prevent grid columns from oversizing in Chrome Canary
  frontend/scss/components/organisms/banner.scss
  frontend/scss/components/organisms/resources-overview.scss
  frontend/scss/components/templates/_default.scss
  frontend/scss/components/templates/overview.scss
  frontend/scss/components/templates/support-overview.scss
Labels: Category: UX, P3: Low, Type: Bug, cla: yes

#3121 Fix comparing `input-throttled` and `input-debounced` to non-existing `input` event
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
Labels: cla: yes

#3116 Moar roadshows!
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3128 Format toggle links to current page if target format is supported
  frontend/templates/views/partials/format-toggle.j2
Labels: cla: yes

#3125 Search test should not rely upon external data
  platform/lib/routers/search.test.js
Labels: cla: yes

#3139 Update amphtml-validator
  package-lock.json
  package.json
Labels: cla: yes

#3065 ✨ Add working group pages
  .gitignore
  frontend/icons/bitmap.svg
  frontend/icons/camera.svg
  frontend/icons/github-logo.svg
  frontend/icons/slack-logo.svg
  frontend/icons/slack.svg
  frontend/scss/_variables.scss
  frontend/scss/components/templates/working-group.scss
  frontend/templates/views/detail/working-group-detail.j2
  gulpfile.js/import.js
  package-lock.json
  package.json
  pages/content/amp-dev/community/_blueprint.yaml
  pages/content/amp-dev/community/working-groups/_blueprint.yaml
  pages/static/img/working-groups-top-desktop.png
  pages/static/img/working-groups-top.png
Labels: Category: Content, Status: Blocked, cla: yes

#3150 Corrects the spelling of "referencees" to "references."
  pages/content/amp-dev/documentation/index.html
Labels: cla: yes

#3151 🐛 Readd csso dependency
  package.json
Labels: cla: yes

#3156 Point go.amp.dev/owners to owners app
  platform/config/go-links.yaml
Labels: cla: yes

#3154 🐛 Fix roadshow pages broken "Jump to" section
  frontend/scss/components/molecules/jumpto-item.scss
  frontend/scss/components/organisms/jumpto-list.scss
  frontend/scss/components/organisms/jumpto.scss
  frontend/scss/components/templates/events.scss
  frontend/templates/views/partials/jumpto.j2
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
  pages/content/amp-dev/events/amp-cs-2019.html
  pages/content/amp-dev/events/amp-roadshow.html
Labels: Category: UX, P1: High, Type: Bug, cla: yes

#3162 🌐 Add insticator to translated md-files for amp-ad component.
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ar.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@es.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@fr.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@id.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@it.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ko.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ru.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@zh_CN.md
Labels: cla: yes

#3170 Removed Busan from roadshows
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3174 added AMP CORS img
  pages/static/img/docs/cors-font.jpg
Labels: cla: yes
