Repository ampproject/amp.dev, pull requests merged in 2019-11, with the labels that each got.

#3180 Fix build procedures (local Gulp, locale subset)
  README.md
  contributing/samples.md
  package.json
  platform/lib/routers/growPages.js
Labels: cla: yes

#3134 Issue ampproject#2382 updated
  pages/content/amp-dev/about/websites.html
Labels: cla: yes

#3169 🐛 Search: fix autosubmitting by clicking outside of the input
  frontend/scss/components/organisms/search.scss
  frontend/templates/views/partials/search.j2
Labels: Category: UX, P3: Low, Type: Bug, cla: yes

#3188 🐛 Fix examples documentation pages styling bugs
  frontend/scss/components/templates/_default.scss
  frontend/scss/components/templates/examples/manual.scss
  frontend/templates/views/examples/documentation.j2
Labels: Category: UX, P3: Low, Type: Bug, cla: yes

#2999 added inline executable samples
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/introduction_to_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
Labels: cla: yes

#3046 Animated hamburger menu example
  examples/source/multimedia-animations/Animated_hamburger_menu.html
  examples/static/samples/img/teaser/animated-hamburger-menu.jpg
Labels: cla: yes

#3192 🐛 Allow carriage return in MarkdownDocument
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
  pages/shared/data/blog.yaml
  platform/lib/pipeline/markdownDocument.js
Labels: cla: yes

#3196 Update renovation_brands.yaml
  pages/content/amp-dev/about/success-stories/renovation_brands.yaml
Labels: cla: yes

#3199 Playground: fix component auto import
  playground/serve.go
  playground/src/auto-importer/auto-importer.js
Labels: cla: yes

#3191 Migrate AMP by Example code to amp.dev
  examples/api/product-browse-page.js
  examples/source/1.components/amp-web-push/api.js
  examples/source/1.components/amp-web-push/static/sw.js
  examples/source/interactivity-dynamic-content/Poll/api.js
  examples/source/news-publishing/Live_Blog/api.js
  gulpfile.js/build.js
  gulpfile.js/deploy.js
  gulpfile.js/develop.js
  package-lock.json
  package.json
  platform/lib/build/samplesBuilder.js
  platform/lib/common/filteredPage.js
  platform/lib/format-transform/index.js
  platform/lib/pipeline/blogImporter.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/pipeline/roadmapImporter.js
  platform/lib/routers/runtimeLog.test.js
  platform/lib/samples/CodeSection.js
  platform/lib/samples/CodeSection.test.js
  platform/lib/samples/Document.js
  platform/lib/samples/Document.test.js
  platform/lib/samples/DocumentParser.js
  platform/lib/samples/DocumentParser.test.js
  platform/lib/samples/ElementSorting.js
  platform/lib/samples/ElementSorting.test.js
  platform/lib/samples/ExampleFile.js
  platform/lib/samples/ExampleFile.test.js
  platform/lib/samples/FileName.js
  platform/lib/samples/FileName.test.js
  platform/lib/samples/FileNameTestFiles/a.html
  platform/lib/samples/FileNameTestFiles/b.html
  platform/lib/samples/index.js
  platform/lib/tools/generalReferenceLinker.js
  platform/lib/utils/HeadDedupTransformer.test.js
  platform/lib/utils/cheerioHelper.js
  platform/lib/utils/cssTransformer.js
  playground/src/app.js
  playground/src/document/controller.js
  playground/src/menu/base.js
  playground/src/preview/preview.js
Labels: cla: yes

#3200 Add examples for keyboard-select-mode to `amp-selector`
  examples/source/1.components/amp-selector.html
Labels: cla: yes

#3201 Removed experimental note
  pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/congratulations.md
Labels: cla: yes

#3211 updated cache url format
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls.md
  pages/static/img/docs/guides/cache-url-path.jpg
Labels: cla: yes

#3187 Allow slow JSON endpoints to return an error
  examples/api/slow-response.js
Labels: cla: yes

#3205 Remove obsolete @filter logic
  platform/lib/samples/CodeSection.js
  platform/lib/samples/CodeSection.test.js
Labels: cla: yes

#3178 Fixing AMP Start 2 demo path names to images.
  templates/websites/land-see/templates/api/all-stories-page-1.json
  templates/websites/land-see/templates/api/all-stories-page-2.json
  templates/websites/land-see/templates/api/all-stories-page-3.json
  templates/websites/land-see/templates/api/arts-culture-accordion.json
  templates/websites/land-see/templates/api/arts-culture-page-1.json
  templates/websites/land-see/templates/api/arts-culture-page-2.json
  templates/websites/land-see/templates/api/design-accordion.json
  templates/websites/land-see/templates/api/design-page-1.json
  templates/websites/land-see/templates/api/fashion-accordion.json
  templates/websites/land-see/templates/api/fashion-page-1.json
  templates/websites/land-see/templates/api/interiors-accordion.json
  templates/websites/land-see/templates/api/interiors-page-1.json
  templates/websites/land-see/templates/api/popular-page-1.json
  templates/websites/land-see/templates/api/popular.json
  templates/websites/land-see/templates/api/recommended.json
  templates/websites/land-see/templates/land-see.amp.html
Labels: cla: yes

#3181 Links to template demo source code.
  frontend/scss/components/organisms/link-group.scss
  frontend/templates/views/detail/template-detail.j2
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/documentation/templates/app_install_ads.yaml
  pages/content/amp-dev/documentation/templates/beck_galo.yaml
  pages/content/amp-dev/documentation/templates/bikeshop.yaml
  pages/content/amp-dev/documentation/templates/gallery.yaml
  pages/content/amp-dev/documentation/templates/land_see.yaml
  pages/content/amp-dev/documentation/templates/lune.yaml
  pages/content/amp-dev/documentation/templates/multi_image_ads.yaml
  pages/content/amp-dev/documentation/templates/scenic.yaml
  pages/content/amp-dev/documentation/templates/simple_article.yaml
  pages/content/amp-dev/documentation/templates/simple_blog.yaml
  pages/content/amp-dev/documentation/templates/single_image_ads.yaml
  pages/content/amp-dev/documentation/templates/single_video_ads.yaml
  pages/content/amp-dev/documentation/templates/text.yaml
  pages/content/amp-dev/documentation/templates/travel.yaml
  pages/static/img/templates/app_install_ads/pages/ad-desktop-above.jpg
  pages/static/img/templates/app_install_ads/pages/ad-mobile-above.jpg
  pages/static/img/templates/app_install_ads/pages/ad-tablet-above.jpg
  pages/static/img/templates/article/pages/article-desktop-above.jpg
  pages/static/img/templates/article/pages/article-mobile-above.jpg
  pages/static/img/templates/article/pages/article-tablet-above.jpg
  pages/static/img/templates/beck_galo/pages/home-desktop-above.jpg
  pages/static/img/templates/beck_galo/pages/home-mobile-above.jpg
  pages/static/img/templates/beck_galo/pages/home-tablet-above.jpg
  pages/static/img/templates/beck_galo/pages/menu-desktop-above.jpg
  pages/static/img/templates/beck_galo/pages/menu-mobile-above.jpg
  pages/static/img/templates/beck_galo/pages/menu-tablet-above.jpg
  pages/static/img/templates/bikeshop/pages/bikeshop-cart-tablet-above.jpg
  pages/static/img/templates/bikeshop/pages/bikeshop-landing-desktop-above.jpg
  pages/static/img/templates/bikeshop/pages/bikeshop-landing-mobile-above.jpg
  pages/static/img/templates/blog/pages/blog-desktop-above.jpg
  pages/static/img/templates/blog/pages/blog-mobile-above.jpg
  pages/static/img/templates/blog/pages/blog-tablet-above.jpg
  pages/static/img/templates/gallery/pages/gallery-desktop-above.jpg
  pages/static/img/templates/gallery/pages/gallery-inner-desktop-above.jpg
  pages/static/img/templates/gallery/pages/gallery-inner-mobile-above.jpg
  pages/static/img/templates/gallery/pages/gallery-inner-tablet-above.jpg
  pages/static/img/templates/gallery/pages/gallery-mobile-above.jpg
  pages/static/img/templates/gallery/pages/gallery-tablet-above.jpg
  pages/static/img/templates/lune/pages/lune-desktop-above.jpg
  pages/static/img/templates/lune/pages/product-noir-tablet-above.jpg
  pages/static/img/templates/lune/pages/store-mobile-above.jpg
  pages/static/img/templates/themes_1/pages/themes_1-desktop-above.jpg
  pages/static/img/templates/themes_1/pages/themes_1-mobile-above.jpg
  pages/static/img/templates/themes_1/pages/themes_1-tablet-above.jpg
  pages/static/img/templates/travel/pages/travel-desktop-above.jpg
  pages/static/img/templates/travel/pages/travel-mobile-above.jpg
  pages/static/img/templates/travel/pages/travel-tablet-above.jpg
Labels: cla: yes

#3212 🐛 Fix iframe preview rotation glitch and overflow fading-bar
  frontend/scss/components/organisms/code-preview.scss
  frontend/templates/views/partials/code-preview/code-preview.j2
Labels: Category: UX, P3: Low, Type: Bug, cla: yes

#3204 Update "Image gallery with lightbox" sample to support email
  examples/source/multimedia-animations/Image_Galleries_with_amp-carousel.html
Labels: cla: yes

#3195 fixed formatting issues for table and added value info for position i…
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
Labels: cla: yes

#3133 Download validator.js, so that tests can run offline.
  gulpfile.js/testSetup.js
  package.json
  platform/lib/format-transform/index.test.js
Labels: cla: yes

#3194 updated translation page
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md
Labels: Category: Content, Type: Update, cla: yes

#3219 update extracted translation files
  gulpfile.js/develop.js
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.pot
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3160 Added SendPulse
  pages/shared/data/tools.yaml
  pages/static/img/tools/sendpulse-logo.png
Labels: Category: Content, Status: Blocked, Type: New, cla: yes

#3238 Typo: Missing "P" from "Providing"
  pages/content/amp-dev/about/success-stories/jagran.yaml
Labels: cla: yes

#3221 💬 Add ameba.jp success story
  pages/content/amp-dev/about/success-stories/ameba.yaml
  pages/content/amp-dev/about/success-stories/ameba@ja.yaml
  pages/static/img/success-stories/ameba/ameba-logo.png
  pages/static/img/success-stories/ameba/ameba-poster.jpg
  pages/static/img/success-stories/ameba/ameba-screen-2.jpg
  pages/static/img/success-stories/ameba/ameba-screen-3.jpg
  pages/static/img/success-stories/ameba/ameba-screen-desktop-1.jpg
  pages/static/img/success-stories/ameba/ameba-teaser.jpg
  pages/static/img/success-stories/ameba/ameba-video.mp4
Labels: Category: Content, Type: New, cla: yes

#3220 [Translate-ko] Add signed-exchange page, publishing checklist page
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/publishing_checklist@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange@ko.md
Labels: cla: yes

#3240 ✨ Implementing real recent guides and tutorials section
  frontend/templates/views/partials/teaser.j2
  gulpfile.js/build.js
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/shared/data/recent-guides.yaml
  platform/lib/pipeline/recentGuides.js
  platform/lib/utils/git.js
  platform/lib/utils/project.js
Labels: Category: Documentation, P1: High, Type: Feature, cla: yes
