Repository ampproject/amp.dev, pull requests merged in 2019-07, with the labels that each got.

#2408 Implement new design of tools page
  frontend/icons/logo-transparent.svg
  frontend/scss/components/molecules/tools-visual.scss
  frontend/scss/components/organisms/tools-teaser.scss
  frontend/scss/components/templates/tools.scss
  frontend/templates/views/overview/tools.j2
  frontend/templates/views/partials/tools-teaser.j2
  frontend/templates/views/partials/tools-visual.j2
  frontend/templates/views/partials/tools-widget.j2
  pages/content/amp-dev/documentation/tools.html
  pages/shared/data/tools.yaml
  pages/static/img/tools/ampbench.jpg
  pages/static/img/tools/jumprope.jpg
  pages/static/img/tools/placeholder.jpg
  pages/static/img/tools/readiness.jpg
  pages/static/img/tools/tools-visual-image-1.jpg
  pages/static/img/tools/tools-visual-image-2-extra.png
  pages/static/img/tools/tools-visual-image-2.jpg
  pages/static/img/tools/tools-visual-image-3.jpg
Labels: Category: UX, P2: Medium, Type: Update, cla: yes

#2356 💄 Add styling to static DayPicker in examples
  frontend/scss/components/atoms/text.scss
Labels: cla: no

#2409 Add Mail.ru playground to tools
  pages/shared/data/tools.yaml
  pages/static/img/tools/mailru_playground.png
Labels: cla: yes

#2415 ♻️ Migrate housing backend to amp.dev
  examples/source/e-commerce/Housing/api.js
  examples/source/e-commerce/Housing/index.html
Labels: Category: Examples, cla: yes

#2416 fixed heath/health typo
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md
Labels: cla: yes

#2405 Add Japanese localization on "Add Translations" page
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations@ja.md
Labels: cla: yes

#2394 Add pulsing animation to upcoming cities on roadshow map
  frontend/scss/components/organisms/cities.scss
  pages/content/amp-dev/events/amp-roadshow.html
  pages/shared/data/roadshow.yaml
Labels: Category: UX, P2: Medium, Type: Update, cla: yes

#2407 Add trailing slash for example redirect
  platform/config/go-links.yaml
Labels: cla: yes

#2414 Load component versions locally instead of using ABE
  pages/extensions/amp-component-versions.json
  pages/extensions/amp_dependency_injector/amp_dependency_injector.py
  pages/extensions/amp_example_preview/util/amp_component_versions.py
Labels: cla: yes

#2376 Email viewer guidelines
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-viewer.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/viewerRenderTemplate-diagram.png
Labels: Category: Documentation, P1: High, Type: New, cla: yes

#2413 Feature/new roadshows
  frontend/scss/components/organisms/cities.scss
  pages/content/amp-dev/events/amp-roadshow.html
  pages/shared/data/roadshow.yaml
Labels: Category: Content, P2: Medium, Type: Update, cla: yes

#2432 Use blacklist to filter locales so that sitemap is not excluded
  platform/lib/config.js
  platform/lib/config.test.js
Labels: cla: yes

#2437 Update Email Provider integration
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md
Labels: cla: yes

#2433 Fix component version path for unit tests
  pages/extensions/amp_example_preview/util/amp_component_versions.py
Labels: cla: yes

#2104 Create email sample for "infinite cards"
  examples/api/photo-stream.js
  examples/source/interactivity-dynamic-content/Dynamically_updating_items_in_a_feed.html
Labels: Category: Examples, Type: New, cla: yes

#2434 Allow markdown in all table tags of imported documents
  platform/config/podspec.yaml
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
Labels: cla: yes

#2450 🚑 Revert allowance of markdown in all table tags of imported documents
  platform/config/podspec.yaml
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
Labels: cla: yes

#2449 🚑 Make unbuffer respect gulp's exit code
  .travis.yml
  scripts/unbuffer.sh
Labels: Category: Infrastructure, P1: High, Type: Bug, cla: yes

#2453 Update indent in package.json
  package.json
Labels: cla: yes

#2445 Add Clang as Email Provider.
  pages/shared/data/tools.yaml
  pages/static/img/tools/clang.png
Labels: Category: Content, P2: Medium, Type: New, cla: yes

#2455 Fixing WaPo case study
  pages/content/amp-dev/about/success-stories/washingtonpost.yaml
Labels: cla: yes

#2457 Update AMPCS2019 page summary, FAQ and location
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#2460 Adds a link to apply to the AMP Contributor Summit
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#2458 AMP email viewer doc updates
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/email-viewer.md
  pages/static/img/docs/viewer_render_template_diagram.png
Labels: cla: yes

#2462 fix apply button formatting
  pages/content/amp-dev/events/amp-cs-2019.html
Labels: cla: yes

#2306 Update docs for cookie->localStorage experiments change
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
Labels: Category: Documentation, Status: Blocked, Type: Update, cla: yes

#2465 🌐 Add translations for category names
  pages/translations/en/LC_MESSAGES/messages.po
Labels: Category: UX, P2: Medium, Type: Bug, cla: yes

#2464 Replace promise handling with `await` in samplesBuilder.js
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2468 Feature/teachers pixel
  frontend/templates/views/partials/analytics.j2
  pages/content/amp-dev/documentation/courses/teachers.md
Labels: cla: yes

#2470 update cache doc for amp for email
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached.md
Labels: cla: yes

#2478 Revert implement new documentation overview pages.
  frontend/icons/content-modules-wide.svg
  frontend/icons/glasses.svg
  frontend/icons/guide.svg
  frontend/icons/optimize-board.svg
  frontend/scss/_mixins.scss
  frontend/scss/_variables.scss
  frontend/scss/components/molecules/_teaser.scss
  frontend/scss/components/molecules/overview-title.scss
  frontend/scss/components/molecules/table-component.scss
  frontend/scss/components/molecules/teaser-component-code.scss
  frontend/scss/components/molecules/teaser-component.scss
  frontend/scss/components/molecules/teaser-example.scss
  frontend/scss/components/molecules/teaser-guide-tutorial.scss
  frontend/scss/components/molecules/teaser-guides.scss
  frontend/scss/components/molecules/teaser-highlight-guides.scss
  frontend/scss/components/molecules/teaser-playground.scss
  frontend/scss/components/molecules/teaser-success-story.scss
  frontend/scss/components/molecules/teaser-template.scss
  frontend/scss/components/molecules/teaser-use-case.scss
  frontend/scss/components/organisms/banner.scss
  frontend/scss/components/organisms/format-cards.scss
  frontend/scss/components/organisms/fragment-slider-controls.scss
  frontend/scss/components/organisms/resources-grid.scss
  frontend/scss/components/organisms/resources-overview.scss
  frontend/scss/components/organisms/story-carousel.scss
  frontend/scss/components/organisms/video-slider.scss
  frontend/scss/components/templates/component-overview.scss
  frontend/scss/components/templates/custom-content.scss
  frontend/scss/components/templates/docs-guides-overview.scss
  frontend/scss/components/templates/overview.scss
  frontend/templates/views/partials/breadcrumbs.j2
  frontend/templates/views/partials/card-grid.j2
  frontend/templates/views/partials/resources-grid.j2
  frontend/templates/views/partials/teaser.j2
  frontend/templates/views/partials/video-carousel.j2
  pages/content/amp-dev/community/governance.md
  pages/content/amp-dev/documentation/_blueprint.yaml
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/courses/index.html
  pages/content/amp-dev/documentation/examples/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-html.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
  pages/content/amp-dev/documentation/index.html
  pages/shared/data/blog.yaml
  pages/static/img/playground-teaser.png
  pages/static/img/playground-teaser@2x.png
  pages/static/img/playground-teaser@3x.png
Labels: cla: yes

#2129 Removed gmail specific styling information
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
Labels: Category: Documentation, Status: Blocked, Type: Update, cla: yes

#2481 Add Amazon SES as ESP to tools
  pages/shared/data/tools.yaml
Labels: cla: yes

#2472 Adding Sydney and Melbourne to roadshow cities
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2480 🐛 Do not show format toggle for courses
  frontend/templates/views/partials/format-toggle.j2
Labels: cla: yes

#2487 Fix staging deploy errors
  .travis.yml
Labels: cla: yes

#2490 🐛 Fix deprecation warning
  examples/api/amp-access.js
Labels: Category: Examples, Type: Bug, cla: yes

#2459 Migrate FAQ overview and detail pages from amproject.org with new design
  .github/ISSUE_TEMPLATE/tool.md
  frontend/scss/components/molecules/faq-visual.scss
  frontend/scss/components/molecules/teaser-faq.scss
  frontend/scss/components/organisms/accordion.scss
  frontend/scss/components/organisms/browsers.scss
  frontend/scss/components/templates/faq-detail.scss
  frontend/scss/components/templates/faq-overview.scss
  frontend/templates/views/detail/faq-detail.j2
  frontend/templates/views/partials/accordion.j2
  frontend/templates/views/partials/breadcrumbs.j2
  frontend/templates/views/partials/faq-visual.j2
  frontend/templates/views/partials/footer.j2
  frontend/templates/views/partials/header.j2
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/community/_blueprint.yaml
  pages/content/amp-dev/community/platform-and-vendor-partners.html
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/ads_vendors.md
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/support/_blueprint.yaml
  pages/content/amp-dev/support/faq/_blueprint.yaml
  pages/content/amp-dev/support/faq/index.html
  pages/content/amp-dev/support/faq/overview.md
  pages/content/amp-dev/support/faq/platform-and-vendor-partners.md
  pages/content/amp-dev/support/faq/platform-involvement.md
  pages/content/amp-dev/support/faq/publisher-monetization.md
  pages/content/amp-dev/support/faq/supported-browsers.md
  pages/content/amp-dev/support/index.md
  pages/shared/data/faq.yaml
  pages/shared/data/supported-browsers.yaml
  pages/static/files/valid-optimized.amp.html
  pages/static/img/faq/faq-overview.jpg
  pages/static/img/faq/faq-platform-and-vendor-partners.jpg
  pages/static/img/faq/faq-platform-involvement.jpg
  pages/static/img/faq/faq-publisher-monetization.jpg
  pages/static/img/faq/faq-supported-browsers.jpg
  pages/static/img/faq/faq-visual.png
  pages/static/img/platforms/chrome.png
  pages/static/img/platforms/edge.png
  pages/static/img/platforms/firefox.png
  pages/static/img/platforms/opera.png
  pages/static/img/platforms/safari.png
  pages/static/img/platforms/uc_browser.png
  platform/config/amp-dev-redirects.yaml
Labels: Category: Content, P1: High, Type: New, cla: yes

#2325 ♻️ Rewrite pages router to enable SSR.
  examples/lib/SampleRenderer.js
  examples/source/0.introduction/AMPHTML_Ads_Hello_World.html
  examples/source/1.components/amp-live-list/api.js
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/format-toggle.j2
  frontend/templates/views/partials/sidebar.j2
  frontend/templates/views/partials/structured-data.j2
  frontend/templates/views/partials/teaser.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
  pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/start/_blueprint.yaml
  pages/extensions/url_beautifier/url_beautifier.py
  platform/lib/build/pageTransformer.js
  platform/lib/routers/pages.js
  platform/lib/routers/pages.test.js
  platform/lib/templates/index.js
Labels: Category: Functionality, Type: Update, cla: yes

#2439 Added Stripo email editor to tools
  pages/shared/data/tools.yaml
  pages/static/img/tools/stripo.png
Labels: Category: Content, P2: Medium, Type: New, cla: yes

#2489 Update dependencies
  package-lock.json
  package.json
  pages/content/amp-dev/documentation/components/reference/amp-accordion.md
  pages/shared/data/blog.yaml
  platform/config/build-info.yaml
  playground/src/formatter/index.js
Labels: cla: yes

#2010 Updated email validation documentation
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_emails.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors.md
Labels: Category: Documentation, Type: Update, cla: no

#2492 ✨ Allow SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
Labels: Category: UX, P1: High, Type: Feature, cla: yes

#2507 ✨ Make debugging SSR in pages router easier
  platform/lib/routers/pages.js
Labels: cla: yes

#2509 Revert Allow SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
Labels: cla: yes

#2494 Add filtering for AMP examples
  contributing/documentation.md
  contributing/samples.md
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2514 update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#2515 Use new formats() in ABE instead of parseFormats()
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#2389 Add module for transforming samples from one format to another
  platform/lib/config.js
  platform/lib/format-transform/formats/amp4email.js
  platform/lib/format-transform/formats/index.js
  platform/lib/format-transform/index.js
  platform/lib/format-transform/index.test.js
  platform/lib/utils/cheerioHelper.js
Labels: Category: Functionality, Type: Feature, cla: yes

#2518 Update title for AMP Viewer docs
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/email-viewer.md
Labels: cla: yes

#2519 Fix syntax highlighting
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/email-viewer.md
Labels: cla: yes

#2496 fixed title casing
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
Labels: cla: yes

#2516 Fix roadshow maps duplicate locations and event box styling
  frontend/scss/components/molecules/event.scss
  frontend/scss/components/organisms/cities.scss
  pages/content/amp-dev/events/amp-roadshow.html
Labels: Category: UX, P2: Medium, Type: Bug, cla: yes

#2513 Implement brand materials download-links to footer
  frontend/icons/arrow-down.svg
  frontend/icons/download.svg
  frontend/scss/components/organisms/footer.scss
  frontend/templates/views/partials/footer.j2
  pages/static/files/brand-material/AMP_Logo_Rebrush.zip
  pages/static/files/brand-material/AMP_Mini_Styleguide.pdf
Labels: Category: Content, P2: Medium, Type: Feature, cla: yes

#2527 🍱 Add success-story for Rcs-mediagroup
  pages/content/amp-dev/about/success-stories/advance_create.yaml
  pages/content/amp-dev/about/success-stories/rcs_mediagroup.yaml
  pages/static/img/success-stories/rcs/rcs1.jpg
  pages/static/img/success-stories/rcs/rcs_2.jpg
  pages/static/img/success-stories/rcs/rcs_logo.png
  pages/static/img/success-stories/rcs/rcs_teaser.jpg
Labels: Category: Content, cla: yes

#2545 Fix image not showing
  contributing/documentation.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md
Labels: cla: yes

#2544 ♻️ Use different set of tags for SSR
  examples/source/1.components/amp-live-list/index.html
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/format-toggle.j2
  frontend/templates/views/partials/structured-data.j2
  pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/message.html
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/templates/index.js
Labels: Category: Functionality, P1: High, Type: Update, cla: yes

#2548 ♻️ Run amp-toolbox-optimizer on request
  package.json
  platform/lib/build/pageTransformer.js
  platform/lib/routers/pages.js
Labels: Category: Functionality, P1: High, Type: Update, cla: yes

#2552 update dependencies
  package-lock.json
  package.json
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
Labels: cla: yes

#2551 ♻️ Migrate poll backend
  examples/source/interactivity-dynamic-content/Poll/api.js
  examples/source/interactivity-dynamic-content/Poll/index.html
  package-lock.json
Labels: Category: Examples, Type: Update, cla: yes

#2554 ✨ Add SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
Labels: cla: yes

#2559 Revert ✨ Add SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
Labels: cla: yes

#2558 Add Auckland and Porto Alegre, improve form links
  pages/content/amp-dev/events/amp-roadshow.html
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2563 Adds link to CSS spec for emails
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
Labels: cla: yes

#2564 Refactor tools styling files to save bytes on the about pages (~4.6 KB)
  frontend/scss/components/organisms/tools-teaser.scss
  frontend/scss/components/organisms/tools-widget.scss
  frontend/scss/components/templates/tools.scss
  frontend/templates/views/partials/tools-widget.j2
Labels: Category: UX, P1: High, Type: Bug, cla: yes

#2566 AMP Story landscape preview mode
  contributing/samples.md
  examples/source/0.introduction/Stories_in_AMP.html
  examples/source/e-commerce/AMP_for_E-Commerce_Getting_Started.html
  examples/source/style-layout/Desktop_and_Landscape_Mode_Support.html
  frontend/scss/components/organisms/code-preview.scss
  frontend/templates/views/examples/documentation.j2
Labels: cla: yes

#2555 🐛 Fix wrong api endpoint
  examples/source/e-commerce/Checkout_Flow/index.html
Labels: Category: Examples, Type: Bug, cla: yes

#2570 Add gulp extract task, extract new strings, improve JA UI translation
  frontend/templates/views/partials/breadcrumbs.j2
  frontend/templates/views/partials/burger-menu.j2
  frontend/templates/views/partials/header.j2
  frontend/templates/views/partials/sidebar-toggle-button.j2
  gulpfile.js/develop.js
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.pot
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: Category: Localization, P2: Medium, Type: Feature, cla: yes

#2576 Remove html from TOC item names
  pages/extensions/markdown_toc_patch/__init__.py
  pages/extensions/markdown_toc_patch/custom_toc_tree_processor.py
  pages/extensions/markdown_toc_patch/markdown_toc_patch.py
  pages/extensions/markdown_toc_patch/readme.md
  platform/config/podspec.yaml
Labels: cla: yes

#2575 🐛 Fix not opening navigation dropdown on latest edge browsers
  frontend/scss/components/organisms/header.scss
Labels: P1: High, Type: Bug, cla: yes

#2580 🐛 Reenable template watching for development
  gulpfile.js/develop.js
Labels: cla: yes

#2579 🐛 Add missing SSR
  examples/source/interactivity-dynamic-content/SeatMap/api.js
  examples/source/interactivity-dynamic-content/SeatMap/index.html
  examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection/api.js
  examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection/index.html
Labels: Category: Examples, Type: Bug, cla: yes

#2581 fix log api regression
  platform/lib/routers/runtimeLog.js
Labels: cla: yes

#2583 run tests on travis
  .travis.yml
Labels: cla: yes

#2578 Add amp-boilerplate.md new japanese translation.
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate@ja.md
Labels: Category: Localization, P2: Medium, Type: Update, cla: yes

#2525 Move Stripo Editor to Creation & Design section
  pages/shared/data/tools.yaml
Labels: cla: yes

#2592 🎨Change component docs title to Documentation and add < > to title tag
  frontend/templates/views/partials/structured-data.j2
Labels: cla: yes

#2596 Update dependencies
  package-lock.json
  package.json
  platform/lib/middleware/subdomain.js
  platform/lib/platform.js
  platform/lib/routers/pages.js
Labels: cla: yes

#2586 Update issue templates
  .github/ISSUE_TEMPLATE/--content-proposal-.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/content.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/tool.md
Labels: cla: yes

#2598 ♿️ Fix focus state / keyboard access for many areas
  frontend/scss/components/atoms/sidebar-toggle.scss
  frontend/scss/components/molecules/filter-bubble.scss
  frontend/scss/components/molecules/language-selector.scss
  frontend/scss/components/organisms/agenda.scss
  frontend/scss/components/organisms/burger-menu.scss
  frontend/scss/components/organisms/format-explainer.scss
  frontend/scss/components/organisms/fragment-slider-controls.scss
  frontend/scss/components/organisms/fragment-slider-texts.scss
  frontend/scss/components/organisms/video-slider.scss
  frontend/scss/components/templates/roadmap.scss
  frontend/scss/components/templates/tools.scss
  frontend/templates/views/partials/burger-menu.j2
  frontend/templates/views/partials/header.j2
  pages/content/amp-dev/community/roadmap.html
  pages/content/amp-dev/documentation/tools.html
Labels: Category: UX, P1: High, Type: Bug, cla: yes

#2584 enable tests for real
  .travis.yml
  gulpfile.js/build.js
  gulpfile.js/lint.js
  integration-tests/grow/examples/default-settings.spec.js
  integration-tests/platform/Routes.test.js
  package.json
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/ads_vendors.md
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  platform/lib/config.test.js
  platform/lib/format-transform/index.test.js
  platform/lib/middleware/redirects.test.js
Labels: cla: yes

#2600 Remove binding from email sample
  examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
Labels: cla: yes

#2605 💬 Add banner for ACS 2019
  frontend/templates/views/partials/banner.j2
  frontend/templates/views/partials/header.j2
Labels: cla: yes

#2591 Fix grow_sitemap.xml delivery and skip sitemap for grow tests
  gulpfile.js/build.js
  platform/lib/common/growPageLoader.js
  platform/lib/config.js
  platform/lib/platform.js
  platform/lib/routers/growPages.js
  platform/lib/routers/growPages.test.js
  platform/lib/routers/growXmls.js
  platform/lib/templates/index.js
Labels: cla: yes

#2611 Fix roadshow dates
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#2603 🐛 Switch relative to absolute paths
  examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
  examples/source/interactivity-dynamic-content/Article_Bookmark_Email/index.html
  examples/source/interactivity-dynamic-content/Conference_Survey_Email.html
Labels: Category: Examples, Type: Bug, cla: no

#2612 Fix growPages router for homepage
  platform/lib/routers/growPages.js
Labels: cla: yes

#2613 Fix template loading for SamplesBuilder
  platform/lib/templates/index.js
Labels: cla: yes

#2606 Fix import of templates for inline example preview
  pages/extensions/amp_example_preview/util/preview_generator.py
Labels: cla: yes

#2616 Fix AMP Cache URL calculator
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls.md
Labels: cla: yes

#2614 ♻️ Move pageTransformer logic into gulp task
  gulpfile.js/build.js
  package-lock.json
  package.json
  platform/lib/build/pageTransformer.js
Labels: Category: Functionality, Type: Update, cla: yes

#2601 ✨ Allow SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
Labels: cla: yes

#2623 ⏪ Allow SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
Labels: cla: yes

#2625 🐛 Leave spaces intact when minifying pages
  gulpfile.js/build.js
Labels: cla: yes

#2617 Add smoke tests
  .travis.yml
  boilerplate/templates/index.html
  examples/lib/SampleRenderer.js
  examples/source/1.components/amp-live-list/api.js
  examples/source/interactivity-dynamic-content/SeatMap/api.js
  examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection/api.js
  integration-tests/platform/Routes.test.js
  jest.config.js
  package.json
  pages/content/amp-dev/documentation/components/reference/amp-accordion.md
  platform/config/environments/local.json
  platform/lib/config.js
  platform/lib/middleware/subdomain.js
  platform/lib/platform.js
  smoke-tests/grow/examples/default-settings.spec.js
  smoke-tests/platform/Routes.test.js
Labels: cla: yes

#2630 🐛 Fix tool screenshots covering header on latest macos safari
  frontend/scss/components/molecules/tools-visual.scss
Labels: Category: UX, P2: Medium, Type: Bug, cla: yes

#2529 Minor Enhancements for AMP CS 2019 event page.
  frontend/scss/components/templates/_default.scss
  frontend/templates/views/partials/footer.j2
  pages/content/amp-dev/events/accessibility.html
  pages/content/amp-dev/events/amp-conf-2019.html
  pages/content/amp-dev/events/amp-conf-2019@ja.html
  pages/content/amp-dev/events/amp-conf/accessibility.html
  pages/content/amp-dev/events/amp-cs-2019.html
  pages/content/amp-dev/events/code-of-conduct.html
  pages/content/amp-dev/events/code-of-conduct@ja.html
Labels: Category: Content, Status: WIP, Type: Update, cla: yes

#2633 Allow markdown in all html tables
  pages/extensions/markdown_in_html/__init__.py
  pages/extensions/markdown_in_html/html_block_processor.py
  pages/extensions/markdown_in_html/html_block_processor_test.py
  pages/extensions/markdown_in_html/readme.md
  platform/config/podspec.yaml
Labels: cla: yes

#2639 solve filters
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
Labels: cla: no

#2634 Moved Stripo Email Editor to Creation & Design section
  pages/shared/data/tools.yaml
Labels: cla: yes

#2641 ♻️ Migrate live-blog to amp.dev
  examples/source/news-publishing/Live_Blog/api.js
  examples/source/news-publishing/Live_Blog/index.html
Labels: Category: Examples, Type: Bug, cla: yes

#2631 Translate amphtml.md into Japanese.
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml@ja.md
Labels: cla: yes

#2665 Add automatic import of basic components to amp_dependencies hook
  pages/extensions/amp_dependencies/__init__.py
  pages/extensions/amp_dependencies/amp_dependencies.py
  pages/extensions/amp_dependencies/amp_dependencies_test.py
  pages/extensions/amp_dependencies/auto_dependency_injector.py
  pages/extensions/amp_dependencies/readme.md
Labels: cla: yes

#2667 Fix encoding problems with auto dependency importer
  pages/extensions/amp_dependencies/auto_dependency_injector.py
Labels: cla: yes
