Repository ampproject/amp.dev, pull requests merged in 2020-02, with the labels that each got.

#3471 Removed past events from upcoming events
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3473 🔥 Escape all HTML inserted into title tags
  frontend/templates/layouts/example-pages/amp-ads-page.j2
  frontend/templates/layouts/example-pages/amp-stories-page.j2
  frontend/templates/layouts/example-pages/amp-websites-page.j2
  frontend/templates/views/examples/embed-ads.j2
  frontend/templates/views/partials/structured-data.j2
Labels: Category: Content, Status: WIP, Type: Bug, cla: yes

#3478 🔧 Fix filter order and quotes
  frontend/templates/views/partials/structured-data.j2
Labels: cla: yes

#3480 Add a go link to the DevX survey
  platform/config/go-links.yaml
Labels: cla: yes

#3482 🚸 Force-dismiss filter hint as soon as format is clicked
  frontend/scss/components/molecules/format-filter-hint.scss
  frontend/templates/views/partials/format-filter-hint.j2
Labels: cla: yes

#3483 🐛 Build samples when bootstrapping
  gulpfile.js/develop.js
Labels: cla: yes

#3485 📦 Update dependencies.
  package-lock.json
  package.json
Labels: cla: yes

#3458 ♻️ Refactor all existing sidebar templates and styling files
  frontend/scss/components/organisms/_sidebar.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar-component.scss
  frontend/scss/components/organisms/sidebar-default.scss
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/sidebar.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: P3: Low, Type: Update, cla: yes

#3489 ⏪♻️ Refactor all existing sidebar templates and styling files
  frontend/scss/components/organisms/_sidebar.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar-component.scss
  frontend/scss/components/organisms/sidebar.scss
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/sidebar.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: cla: yes

#3488 Set release-schedule visualization to layout:container
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
Labels: cla: yes

#3490 🐛 Handle empty next stops for roadshow gracefully
  pages/content/amp-dev/events/amp-roadshow.html
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3491 ⏪⏪♻️ Refactor all existing sidebar templates and styling files
  frontend/scss/components/organisms/_sidebar.scss
  frontend/scss/components/organisms/component-sidebar.scss
  frontend/scss/components/organisms/sidebar-component.scss
  frontend/scss/components/organisms/sidebar-default.scss
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/example-sidebar.j2
  frontend/templates/views/partials/sidebar.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: cla: yes

#3317 ♻️ Link all resources absolute for search
  platform/lib/routers/search.js
  platform/lib/routers/search.test.js
Labels: cla: yes

#3492 📖 Fixes amphtml issue #25356 for other translations
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@ar.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@es.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@fr.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@id.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@it.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@ja.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@ko.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@pt_BR.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@ru.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@tr.md
  pages/content/amp-dev/documentation/components/reference/amp-list-v0.1@zh_CN.md
Labels: cla: yes

#3493 Use fixed-height layout for calendar with desktop/mobile sizes
  frontend/scss/components/organisms/release-schedule.scss
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
Labels: cla: yes

#3467 Properly extract strings for i18n on non documentation pages
  frontend/templates/layouts/default.j2
  frontend/templates/views/detail/working-group-detail.j2
  frontend/templates/views/partials/breadcrumbs.j2
  frontend/templates/views/partials/category-filter.j2
  frontend/templates/views/partials/filter-bubbles.j2
  frontend/templates/views/partials/footer.j2
  frontend/templates/views/partials/format-filter-hint.j2
  frontend/templates/views/partials/fragment-slider-texts.j2
  frontend/templates/views/partials/jumpto.j2
  frontend/templates/views/partials/rolling-formats.j2
  frontend/templates/views/partials/teaser-grid.j2
  frontend/templates/views/partials/teaser.j2
  frontend/templates/views/partials/tools-teaser.j2
  frontend/templates/views/partials/tools-widget.j2
  pages/content/amp-dev/about/ads.html
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/about/how-amp-works.html
  pages/content/amp-dev/about/mission-and-vision.html
  pages/content/amp-dev/about/stories.html
  pages/content/amp-dev/about/success-stories/index.html
  pages/content/amp-dev/about/websites.html
  pages/content/amp-dev/community/roadmap.html
  pages/content/amp-dev/documentation/courses/index.html
  pages/content/amp-dev/documentation/examples/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/index.html
  pages/content/amp-dev/documentation/index.html
  pages/content/amp-dev/documentation/templates/index.html
  pages/content/amp-dev/documentation/tools.html
  pages/content/amp-dev/events/amp-roadshow.html
  pages/content/amp-dev/index.html
  pages/content/amp-dev/offline.html
  pages/shared/data/amp-conf.yaml
  pages/shared/data/blog.yaml
  pages/shared/data/recent-guides.yaml
  pages/shared/data/roadshow.yaml
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
  platform/config/build-info.yaml
Labels: cla: yes

#3498 🎨 Make language selector in header optional
  frontend/scss/components/molecules/language-selector.scss
  frontend/scss/components/organisms/header.scss
  frontend/templates/views/partials/header.j2
  pages/content/shared/header.html
Labels: cla: yes

#3499 🎨 Ensure shared pages and pages router behave the same
  platform/lib/platform.js
  platform/lib/routers/growPages.js
  platform/lib/routers/growPages.test.js
  platform/lib/routers/growSharedPages.js
Labels: cla: yes

#3506 🐛 Set correct class for example sidebar
  frontend/templates/views/partials/sidebar.j2
Labels: cla: yes

#3507 Warn if CSE key is missing. Fixes #3202
  platform/lib/utils/googleSearch.js
Labels: cla: yes

#3508 Don't override input. Fixes #3103
  examples/static/samples/files/amp_url_converter.js
Labels: cla: yes

#3510 🔥 Remove dead code and dependencies
  package-lock.json
  package.json
  platform/lib/pipeline/collection.js
Labels: cla: yes

#3503 ➖ Remove got as dependency
  package-lock.json
  package.json
Labels: cla: yes

#3500 🐛 Use absolute URLs for search API endpoints
  frontend/templates/views/partials/search.j2
Labels: cla: yes

#3479 guidelines for creating a successful story narrative and technical resources
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_successful_stories.md
Labels: cla: yes

#3512 ⚡️ Remove custom-loader
  frontend/scss/base.scss
  frontend/templates/views/detail/success-story-detail.j2
  frontend/templates/views/partials/case-band.j2
  frontend/templates/views/partials/case-grid.j2
  frontend/templates/views/partials/format-visuals/ads.j2
  frontend/templates/views/partials/format-visuals/email.j2
  frontend/templates/views/partials/format-visuals/stories.j2
  frontend/templates/views/partials/format-visuals/websites.j2
  frontend/templates/views/partials/teaser.j2
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/about/success-stories/index.html
  pages/content/amp-dev/documentation/examples/index.html
  pages/content/amp-dev/index.html
  pages/static/files/valid-optimized.amp.html
Labels: cla: yes

#3486 ⚡️ SSR blog posts on home and use REST API over RSS feed
  gulpfile.js/build.js
  package.json
  pages/content/amp-dev/index.html
  pages/extensions/internal_links/pod_internal_link_rewriter.py
  platform/lib/pipeline/blogImporter.js
  platform/lib/routers/growPages.js
  platform/lib/templates/ImportBlogFilter.js
  platform/lib/templates/index.js
  platform/lib/tools/growReferenceChecker.js
Labels: cla: yes

#3521 Bootstrap fix
  gulpfile.js/develop.js
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
  pages/shared/data/recent-guides.yaml
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#3522 🚑 Use in operator instead of non-existant includes
  pages/extensions/internal_links/pod_internal_link_rewriter.py
Labels: cla: yes

#3517 Plumrocket amp
  pages/shared/data/tools.yaml
  pages/static/img/tools/plumrocket-amp-email.jpg
  pages/static/img/tools/plumrocket-amp-magento.jpg
Labels: cla: yes

#3344 ✨ Add new component intro table
  .gitignore
  frontend/icons/clipboard.svg
  frontend/scss/components/organisms/component-intro.scss
  frontend/scss/components/templates/component-detail.scss
  frontend/templates/views/partials/component-intro.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/content.j2
  frontend/templates/views/partials/sidebar.j2
  frontend/templates/views/partials/version-toggle.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated.html
  pages/content/shared/copy-script.html
  platform/config/imports/componentCategories.json
  platform/config/imports/componentFormats.json
  platform/config/imports/componentReference.json
  platform/config/imports/spec.json
  platform/lib/build/samplesBuilder.js
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/componentReferenceDocument.test.js
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/gitHubImporter.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/pipeline/specImporter.js
  platform/lib/routers/growPages.js
  platform/lib/utils/project.js
Labels: Category: Documentation, P1: High, Type: Feature, cla: yes

#3531 ⏪✨ Add new component intro table
  .gitignore
  frontend/icons/clipboard.svg
  frontend/scss/components/organisms/component-intro.scss
  frontend/scss/components/templates/component-detail.scss
  frontend/templates/views/partials/component-intro.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/content.j2
  frontend/templates/views/partials/sidebar.j2
  frontend/templates/views/partials/version-toggle.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated.html
  pages/content/shared/copy-script.html
  platform/config/imports/componentCategories.json
  platform/config/imports/componentFormats.json
  platform/config/imports/componentReference.json
  platform/config/imports/spec.json
  platform/lib/build/samplesBuilder.js
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/componentReferenceDocument.test.js
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/gitHubImporter.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/pipeline/specImporter.js
  platform/lib/routers/growPages.js
  platform/lib/utils/project.js
Labels: cla: yes

#3529 🐛 Fix dynamic button text for format explainer
  pages/content/amp-dev/index.html
Labels: cla: yes

#3530 🐛 Fix active state for working group navigation items
  frontend/scss/components/templates/working-group.scss
  frontend/templates/views/detail/working-group-detail.j2
  pages/content/amp-dev/community/_blueprint.yaml
Labels: cla: yes

#3539 ✨ Add new component intro table
  .gitignore
  frontend/icons/clipboard.svg
  frontend/scss/components/organisms/component-intro.scss
  frontend/scss/components/templates/component-detail.scss
  frontend/templates/views/partials/component-intro.j2
  frontend/templates/views/partials/component-sidebar.j2
  frontend/templates/views/partials/content.j2
  frontend/templates/views/partials/sidebar.j2
  frontend/templates/views/partials/version-toggle.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/layouts_demonstrated.html
  pages/content/shared/copy-script.html
  platform/config/imports/componentCategories.json
  platform/config/imports/componentFormats.json
  platform/config/imports/componentReference.json
  platform/config/imports/spec.json
  platform/lib/build/samplesBuilder.js
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/componentReferenceDocument.test.js
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/pipeline/gitHubImporter.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/pipeline/markdownDocument.test.js
  platform/lib/pipeline/specImporter.js
  platform/lib/routers/growPages.js
  platform/lib/utils/project.js
Labels: cla: yes

#3537 changed vendor to third party
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/index.md
Labels: cla: yes

#3544 🐛 Fix-up for component intro tables
  frontend/scss/components/organisms/component-intro.scss
  pages/content/shared/copy-script.html
Labels: cla: yes

#3551 Update amp-video-import.html
  boilerplate/templates/partials/media/amp-video-import.html
Labels: cla: yes

#3550 🐛 Correctly link to amp-script doc from example
  examples/source/1.components/amp-script/index.html
Labels: cla: yes

#3556 🎨 Share definition of built in components
  platform/lib/common/AmpConstants.js
  platform/lib/pipeline/componentReferenceImporter.js
  platform/lib/routers/search.js
Labels: cla: yes

#3555 🔥 Remove legacy format filter implementation
  platform/lib/common/filteredPage.js
Labels: cla: yes

#3554 🚸 Force-list components for websites if unspecified
  platform/lib/pipeline/componentReferenceDocument.js
Labels: cla: yes

#3543 🎨 Make Samples Builder non-blocking, always build all on first run
  README.md
  gulpfile.js/build.js
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#3558 🐛 Fix version toggle issues
  frontend/scss/components/templates/component-detail.scss
  platform/lib/pipeline/componentReferenceImporter.js
Labels: cla: yes

#3560 🚸 Improve logging behaviour around Grow
  gulpfile.js/develop.js
  pages/extensions/log_beautifier/__init__.py
  pages/extensions/log_beautifier/log_beautifier.py
  platform/config/podspec.yaml
  platform/lib/utils/grow.js
  platform/lib/utils/sh.js
Labels: cla: yes

#3559 ✨ Add lang selector in AMP Boilerplate Generator
  boilerplate/data/categories.json
  boilerplate/templates/files/websites.html
  boilerplate/templates/index.html
  boilerplate/templates/partials/language-select/lang.html
  boilerplate/templates/styles/main.scss
Labels: cla: yes

#3502 zh-CN translation update
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3563 Don't use join to concatenate a URL, as it drops double slashes
  platform/lib/pipeline/componentReferenceDocument.js
Labels: cla: yes

#3566 📦 Update rcs-core to version 3.0.0
  package-lock.json
  package.json
  platform/lib/utils/cssTransformer.js
Labels: cla: yes

#3460 3 new samples for amp playground
  examples/source/1.components/amp-bind-macro.html
  examples/source/1.components/amp-bind-recaptcha.html
  examples/source/interactivity-dynamic-content/Dynamic_Accordion.html
  examples/static/samples/json/cold.json
  examples/static/samples/json/hot.json
Labels: cla: yes

#3474 Amp playground interactive snippets
  examples/source/interactivity-dynamic-content/Currency_Conversion.html
  examples/source/interactivity-dynamic-content/Linked_Dropdowns.html
  examples/static/samples/json/linked_dropdowns.json
Labels: cla: yes

#3475 3 more snippets
  examples/source/1.components/amp-accordion.html
  examples/source/interactivity-dynamic-content/Conditional_State.html
  examples/source/interactivity-dynamic-content/Multi_Page_Flow.html
  examples/static/samples/json/accordion-fruit.json
Labels: cla: yes

#3561 🐛 Remove select format call out on mobile
  frontend/scss/components/molecules/format-filter-hint.scss
Labels: cla: yes

#3575 🐛 Correctly build component scripts
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/componentReferenceImporter.js
Labels: cla: yes

#3577 🔇 Disable logs during test runs
  platform/lib/config.js
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/markdownDocument.js
  platform/lib/utils/grow.js
  platform/lib/utils/log.js
Labels: cla: yes

#3571 add ampconf banner
  frontend/templates/views/partials/banner.j2
  frontend/templates/views/partials/header.j2
Labels: cla: yes

#3573 Fixed spelling/grammar error on home page
  pages/content/amp-dev/index.html
Labels: cla: yes

#3580 add some strings that were missed in the initial pass
  frontend/templates/views/partials/accordion.j2
  frontend/templates/views/partials/toc.j2
  pages/shared/data/blog.yaml
  pages/shared/data/faq.yaml
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
  platform/config/build-info.yaml
Labels: cla: yes

#3584 fix some typos found during translations
  pages/content/amp-dev/about/stories.html
  pages/shared/data/benefits.yaml
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3582 replace AMP Conf 2019 with 2020 in sidebar
  frontend/templates/views/partials/footer.j2
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3585 remove some awkward phrasing
  pages/content/amp-dev/about/mission-and-vision.html
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3581 remove story titles from translation files
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3586 fix the typo fixes
  pages/content/amp-dev/about/ads.html
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3588 update po files due to #3575
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3595 unwrap sidebar 2020 amp conf link
  frontend/templates/views/partials/footer.j2
Labels: cla: yes

#3600 replace 50k with 75k for various css docs
  examples/source/0.introduction/Hello_World_Email.html
  pages/content/amp-dev/documentation/courses/beginning-course/our-first-amp-page.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@zh_CN.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/converting/resolving-errors@ko.md
Labels: cla: yes

#3583 add upcoming roadshow dates and locations
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3601 fix roadshow dates
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3602 Fix closing tag name typo
  pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements.md
Labels: cla: yes

#3597 🐛 Only show amp-story script for amp-story-* components
  platform/lib/pipeline/componentReferenceImporter.js
Labels: cla: yes

#3596 💬 Add Findomestic success story.
  pages/content/amp-dev/about/success-stories/findomestic.yaml
  pages/static/img/success-stories/findomestic/findomestic-logo.png
  pages/static/img/success-stories/findomestic/findomestic-screen-1.jpg
  pages/static/img/success-stories/findomestic/findomestic-screen-2.jpg
  pages/static/img/success-stories/findomestic/findomestic-teaser.jpg
  pages/static/img/success-stories/findomestic/findomestic-video.mp4
Labels: Category: Content, cla: yes

#3599 Updating page to reflect updated CSS limit
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors.md
Labels: cla: yes

#3603 more updates for the translations
  frontend/templates/views/partials/card-grid.j2
  pages/content/amp-dev/documentation/courses/index.html
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3589 add custom form validation amp-script sample
  examples/source/1.components/amp-script/index.html
Labels: cla: yes

#3606 update homepage grammar on Chinese translation
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3605 add AMP Conf banner to localization files
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3612 make cookie text readable
  examples/source/news-publishing/News_Article.html
Labels: cla: yes

#3611 🐛 Prevent format filter banner from jumping
  frontend/scss/components/molecules/format-filter-hint.scss
  frontend/templates/views/partials/format-filter-hint.j2
Labels: cla: yes
