Repository ampproject/amp.dev, pull requests merged in 2020-03, with the labels that each got.

#3614 💄 Add copy script success animation
  frontend/icons/checkmark.svg
  frontend/icons/clipboard.svg
  frontend/scss/components/organisms/component-intro.scss
  frontend/templates/views/partials/component-intro.j2
  pages/content/shared/copy-script.html
Labels: cla: yes

#3621 fix link to component docs
  examples/source/1.components/amp-inputmask.html
Labels: cla: yes

#3610 🎨 Remove headline tags from teaser texts
  platform/lib/pipeline/markdownDocument.js
Labels: cla: yes

#3609 Update documentation.md
  contributing/documentation.md
Labels: cla: yes

#3638 📦 Updating dependencies.
  package-lock.json
  package.json
Labels: cla: yes

#3642 Re add amp app banner
  examples/source/1.components/amp-app-banner.html
  pages/static/amp-app-banner-manifest.json
  platform/lib/routers/static.js
Labels: cla: yes

#3650 disable AMP Conf banner 😢
  frontend/templates/views/partials/header.j2
Labels: cla: yes

#3651 Deutsch zu unterstützten Sprachen hinzufügen
  platform/lib/config.js
Labels: cla: yes

#3634 ✨ Make component categories linkable
  frontend/templates/views/partials/category-filter.j2
  pages/content/amp-dev/documentation/components/index.html
Labels: cla: yes

#3652 💬 Text update for findomestic success story
  pages/content/amp-dev/about/success-stories/findomestic.yaml
Labels: cla: yes

#3636 remove events
  frontend/scss/components/organisms/cities.scss
  pages/content/amp-dev/events/amp-roadshow.html
  pages/shared/data/recent-guides.yaml
  pages/shared/data/roadshow.yaml
Labels: cla: yes

#3656 🚑 Adapt category filtering for examples overview
  frontend/templates/views/partials/category-filter.j2
  pages/content/amp-dev/documentation/examples/index.html
Labels: cla: yes

#3622 🚸 Filter TOC based on format and level
  frontend/templates/views/partials/toc.j2
  pages/extensions/amp_dev/extension.py
  pages/extensions/amp_dev/markdown_extras/block_filter.py
Labels: cla: yes

#3661 Fix copy button sample
  examples/source/interactivity-dynamic-content/Copy_Button.html
Labels: cla: yes

#3664 🐛 Escape headline when filtering TOC
  pages/extensions/amp_dev/markdown_extras/block_filter.py
Labels: cla: yes

#3662 🐛 Correctly import amp-story sub-components
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/componentReferenceImporter.js
Labels: cla: yes

#3669 🐛 Make filter call blocks unique
  pages/extensions/amp_dev/markdown_extras/block_filter.py
Labels: cla: yes

#3639 Move ESPs to FAQ
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/about/email.html
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
  pages/content/amp-dev/documentation/tools.html
  pages/content/amp-dev/support/faq/email-support.md
  pages/content/amp-dev/support/faq/supported-browsers.md
  pages/shared/data/faq.yaml
  pages/shared/data/tools.yaml
  pages/static/img/faq/faq-email.jpg
  pages/static/img/tools/adobe_campaign.png
  pages/static/img/tools/aweber.png
  pages/static/img/tools/clang.png
  pages/static/img/tools/copernica.png
  pages/static/img/tools/esputnik-logo.png
  pages/static/img/tools/maileon.png
  pages/static/img/tools/mailgun.png
  pages/static/img/tools/pepipost.jpg
  pages/static/img/tools/sendgrid.png
  pages/static/img/tools/sendpulse-logo.png
  pages/static/img/tools/sparkpost.png
  platform/config/go-links.yaml
Labels: cla: yes

#3671 Adds ExpressPigeon to ESP list
  pages/shared/data/faq.yaml
Labels: cla: yes

#3677 Fix typo in courses
  pages/content/amp-dev/documentation/courses/index.html
Labels: cla: yes

#3678 Update DevX Survey for new quarter
  platform/config/go-links.yaml
Labels: cla: yes

#3655 ✨Add show more button to sample list
  frontend/scss/components/organisms/component-intro.scss
  frontend/templates/views/partials/component-intro.j2
Labels: cla: yes

#3681 💬 Add ImpreMedia success story.
  pages/content/amp-dev/about/success-stories/impremedia.yaml
  pages/static/img/success-stories/impremedia/impremedia-logo.png
  pages/static/img/success-stories/impremedia/impremedia-screen-1.jpg
  pages/static/img/success-stories/impremedia/impremedia-teaser.jpg
Labels: cla: yes

#3692 🐛 Fix pointer events for extension version-toggle
  frontend/scss/components/templates/component-detail.scss
Labels: cla: yes

#3694 Sniffing fix
  examples/api/echo.js
  examples/source/interactivity-dynamic-content/ComboBox.html
Labels: cla: yes

#3700 Add four more ESPs and one tool
  pages/shared/data/faq.yaml
  pages/shared/data/tools.yaml
  pages/static/img/tools/sendtestemail.png
Labels: cla: yes

#3696 Add a `go.amp.dev` link for working group updates
  platform/config/go-links.yaml
Labels: cla: yes

#3689 Document validation of delievered AMP emails
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_emails.md
Labels: cla: yes

#3676 🐛Hide examples headline in intro table if there are none
  frontend/templates/views/partials/component-intro.j2
Labels: cla: yes

#3705 update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#3707 🐛 Hide unused script tags in Boilerplate Generator
  boilerplate/templates/partials/analytics/amp-analytics-import.html
  boilerplate/templates/partials/media/amp-video-import.html
Labels: cla: yes

#3710 Remove experiment flag
  examples/source/1.components/amp-inputmask.html
Labels: cla: yes

#3713 🐛 Correctly resolve embed path for amp-analytics example
  examples/source/1.components/amp-analytics/api.js
Labels: cla: yes

#3719 🐛Fix and refactor broken tic tac toe example
  examples/source/interactivity-dynamic-content/Tic_Tac_Toe.html
Labels: cla: yes

#3720 Fix invalid JSON
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics.md
Labels: cla: yes

#3695 🐛 Fix documentation toc scrolling
  frontend/scss/components/organisms/toc.scss
Labels: cla: yes

#3726 🐛 Keep scroll position when filtering on overview pages
  frontend/templates/views/partials/category-filter.j2
  pages/content/amp-dev/documentation/components/index.html
  pages/content/amp-dev/documentation/examples/index.html
Labels: cla: yes

#3729 Removed documentation from ads filtering
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/_blueprint.yaml
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/secure-pages.md
Labels: cla: yes

#3727 🐛 Clickable components and examples breadcrumbs
  frontend/templates/views/partials/breadcrumbs.j2
Labels: cla: yes

#3735 🐛 Stop removing tables from component docs
  platform/lib/pipeline/componentReferenceDocument.js
  platform/lib/pipeline/componentReferenceDocument.test.js
Labels: cla: yes

#3736 📝 Update instructions for Python installation
  README.md
Labels: cla: yes

#3744 Fix typo in custom_fonts@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts@ja.md
Labels: cla: yes

#3751 update the copyright year
  frontend/templates/views/partials/footer.j2
Labels: cla: yes

#3714 📝 Several minor fixes for amp example docs
  examples/source/1.components/amp-addthis.html
  examples/source/1.components/amp-analytics/index.html
  examples/source/1.components/amp-anim.html
  examples/source/1.components/amp-bind.html
  examples/source/1.components/amp-bodymovin-animation.html
  examples/source/1.components/amp-brid-player.html
  examples/source/1.components/amp-carousel.html
  examples/source/1.components/amp-dailymotion.html
  examples/source/1.components/amp-experiment.html
  examples/source/1.components/amp-facebook-comments.html
  examples/source/1.components/amp-facebook-like.html
  examples/source/1.components/amp-facebook-page.html
  examples/source/1.components/amp-facebook.html
  examples/source/1.components/amp-form.html
  examples/source/1.components/amp-fx-collection.html
  examples/source/1.components/amp-fx-flying-carpet.html
  examples/source/1.components/amp-google-vrview-image.html
  examples/source/1.components/amp-iframe.html
  examples/source/1.components/amp-ima-video.html
  examples/source/1.components/amp-image-slider.html
  examples/source/1.components/amp-pixel.html
  examples/source/1.components/amp-reach-player.html
  examples/source/1.components/amp-sticky-ad.html
  examples/source/interactivity-dynamic-content/Currency_Conversion.html
Labels: cla: yes

#3753 📦 Update dependencies.
  package-lock.json
  package.json
Labels: cla: yes

#3756 🐛 Only add required scripts for scripts not for tags
  platform/lib/pipeline/componentReferenceDocument.js
Labels: cla: yes

#3759 👽 Upgrade amp-analytics to new uuid export scheme
  examples/source/1.components/amp-analytics/api.js
Labels: cla: yes

#3758 💬 Adapt unsupported format warning to fit all pages
  frontend/templates/views/partials/content.j2
Labels: cla: yes

#3757 📈 Add various analytics triggers
  frontend/templates/views/partials/analytics.j2
Labels: cla: yes

#3762 🎨 Use new configuration scheme for amp-consent
  frontend/templates/views/partials/analytics.j2
  frontend/templates/views/partials/consent.j2
Labels: cla: yes

#3763 🐛 Fix json error for analytics_basics script tag
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics.md
Labels: cla: yes

#3765 🚸 Display icon instead of default image for news teaser
  pages/content/amp-dev/index.html
Labels: Category: UX, cla: yes

#3764 🐛 Remove trailing and leading blank lines from tip
  platform/lib/pipeline/markdownDocument.js
Labels: cla: yes

#3718 Added step-by-step guidance on embedding stories in web pages
  pages/content/amp-dev/documentation/guides-and-tutorials/integrate/embed-stories.md
Labels: Category: Documentation, cla: yes

#3712 📖 Update amp-sidebar example to include always visible desktop sidebar
  examples/source/1.components/amp-sidebar.html
Labels: cla: yes

#3768 🚸 Show specific component samples as first in component intro
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#3772 🐛 Use length of filtered examples to decide if list is expandable
  frontend/templates/views/partials/component-intro.j2
Labels: cla: yes

#3779 📈 Add labels for tracking events, add event for main navigation clicks
  frontend/templates/views/partials/analytics.j2
Labels: cla: yes

#3778 Add keyboard-select-mode
  examples/source/style-layout/Tab_Panels_with_amp-selector.html
Labels: cla: yes

#3776 Fix AMP Story consent example.
  examples/source/user-consent/Story_User_Consent.html
Labels: cla: yes
