Repository ampproject/amp.dev, pull requests merged in 2020-11, with the labels that each got.

#4899 Adding Join Stories Web Story editor to tools
  pages/content/amp-dev/community/governance.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/a4a_spec.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md
  pages/shared/data/recent-guides.yaml
  pages/shared/data/tools.yaml
  pages/static/img/tools/joinstories.jpg
Labels: Category: Content, Status: WIP, Type: New

#4903 Translation pt br course introduction
  pages/content/amp-dev/documentation/courses/beginning-course/course-introduction@pt_BR.md
  pages/content/amp-dev/documentation/courses/beginning-course/index@pt_BR.md
Labels: Category: Localization, Language: PT_BR, Status: WIP

#4807 Added BEE to AMP E-mail tools
  pages/shared/data/tools.yaml
  pages/static/img/tools/bee.png
Labels: cla: yes

#4777 ⚡️ Use amp-carousel for news slider
  frontend/scss/base.scss
  frontend/scss/components/organisms/news.scss
  frontend/scss/components/organisms/story-carousel.scss
  pages/content/amp-dev/index.html
Labels: cla: yes
