Repository ampproject/amp.dev, pull requests merged in 2020-01, with the labels that each got.

#3335 fix(doc): revise Creating a New Sample formatting
  contributing/samples.md
Labels: cla: yes

#3290 ✨ Clean up stale Google Cloud instance templates
  gulpfile.js/deploy.js
Labels: cla: yes

#3337 Corrected typo
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
Labels: cla: yes

#3340 Added Nodemailer to tools
  pages/shared/data/tools.yaml
  pages/static/img/tools/nodemailer.jpg
Labels: cla: yes

#3347 📦 Update packages.
  package-lock.json
  package.json
Labels: cla: yes

#3328 Adds "Import email" button to the playground
  package-lock.json
  package.json
  playground/src/app.critical.scss
  playground/src/app.js
  playground/src/email-loader/email-loader.js
  playground/src/email-loader/email-loader.test.js
  playground/src/index.hbs
Labels: Category: Playground, Type: Feature, cla: yes

#3350 Adds Copernica as a tool that supports AMP for Email
  pages/shared/data/tools.yaml
  pages/static/img/tools/copernica.png
Labels: cla: yes

#3351 Add go.amp.dev/cherry-picks link
  platform/config/go-links.yaml
Labels: cla: yes

#3364 fixed css issue
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@zh_CN.md
Labels: cla: yes

#3363 feat(meta): disable blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla: yes

#3277 ✨ Cache latest search query and results in service worker
  frontend/templates/views/partials/search.j2
  pages/static/serviceworker.js
  platform/config/search-promoted-pages.json
  platform/lib/routers/search.js
Labels: Category: Functionality, P2: Medium, Type: Feature, cla: yes

#3374 Grammar changes to <amp-script> docs
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
Labels: cla: yes

#3378 resolved issue 3373
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
Labels: cla: yes

#3360 Courses landing pages refresh, and more
  frontend/scss/components/organisms/card-grid.scss
  frontend/scss/components/templates/courses-overview.scss
  frontend/scss/components/templates/docs-detail.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/partials/card-grid.j2
  pages/content/amp-dev/documentation/courses/advanced-course/conclusion-and-whats-next.md
  pages/content/amp-dev/documentation/courses/index.html
  pages/content/amp-dev/documentation/courses/teachers.md
  pages/static/img/courses/site/badge-shield-2x.png
Labels: cla: yes

#3383 clarified inlined style limits
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index.md
Labels: cla: yes

#3391 add missing strings to po files
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/en/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
  pages/translations/zh_CN/LC_MESSAGES/messages.po
Labels: cla: yes

#3390 Fix typo
  examples/source/1.components/amp-gist.html
Labels: cla: no

#3379 Add new Interactivity & Dynamic Content Restrict Duplicate Selection
  examples/source/interactivity-dynamic-content/Restrict_Duplicate_Selection.html
  examples/static/samples/json/fruits.json
Labels: cla: yes

#3389 removed suck less...
  pages/content/amp-dev/documentation/index.html
Labels: cla: yes

#3376 📝 Revise Include custom JavaScript in AMP pages
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
Labels: cla: yes

#3394 🐛 Change success stories tag labels from format to category
  frontend/scss/components/molecules/tag.scss
  frontend/templates/views/partials/teaser.j2
Labels: Category: UX, P2: Medium, Type: Update, cla: yes

#3401 [docs] add translated apology banner for all languages
  pages/translations/ar/LC_MESSAGES/messages.po
  pages/translations/es/LC_MESSAGES/messages.po
  pages/translations/fr/LC_MESSAGES/messages.po
  pages/translations/id/LC_MESSAGES/messages.po
  pages/translations/it/LC_MESSAGES/messages.po
  pages/translations/ja/LC_MESSAGES/messages.po
  pages/translations/ko/LC_MESSAGES/messages.po
  pages/translations/messages.po
  pages/translations/pt_BR/LC_MESSAGES/messages.po
  pages/translations/ru/LC_MESSAGES/messages.po
  pages/translations/tr/LC_MESSAGES/messages.po
Labels: cla: yes

#3403 Rtc partners
  pages/shared/data/faq.yaml
Labels: cla: yes

#3402 🏗 Automatically pin exact versions with `npm install`
  .npmrc
Labels: cla: yes

#3381 normalize viewport declaration
  boilerplate/templates/files/ads.html
  boilerplate/templates/files/stories.html
  boilerplate/templates/files/websites.html
  boilerplate/templates/index.html
  examples/api/cache.js
  examples/source/1.components/amp-script/index.html
  examples/static/samples/files/resizable-iframe.html
  examples/static/samples/hreflang/fr/index.amp.html
  examples/static/samples/hreflang/index.amp.html
  examples/static/samples/standalone/amp-ad/index.html
  examples/static/samples/standalone/amp-website/index.html
  frontend/templates/views/examples/embed-ads.j2
  pages/content/amp-dev/documentation/courses/beginning-course/our-first-amp-page.md
  pages/content/amp-dev/documentation/guides-and-tutorials/develop/story_ads_best_practices.md
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@ar.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@es.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@fr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@id.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@it.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@ja.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@ko.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@pt_BR.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@ru.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@tr.md
  pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup@zh_CN.md
  pages/content/shared/experiments.html
  pages/content/tests/examples/preview_side_frame.md
  pages/content/tests/examples/preview_top_frame.md
  platform/lib/utils/HeadDedupTransformer.test.js
  playground/src/runtime/templates/a4a.template.html
  playground/src/runtime/templates/amphtml.template.html
  templates/ads/app_install_ads/app-install.html
  templates/ads/multi-image-ads/multi-image.html
  templates/ads/single-image-ads/single-image.html
  templates/ads/single-video/single-video/single-video.html
  templates/ads/text/text.html
Labels: cla: yes

#3406 disable analytics in embed mode
  playground/src/app.js
Labels: cla: yes

#3408 👌 Prefill search input field with value instead of placeholder
  frontend/templates/views/partials/search.j2
Labels: Category: UX, P3: Low, Type: Update, cla: yes

#3407 Upgrade AMP Optimizer
  package-lock.json
  package.json
  platform/lib/utils/HeadDedupTransformer.js
  platform/lib/utils/HeadDedupTransformer.test.js
  platform/lib/utils/cssTransformer.js
Labels: cla: yes

#3404 added rebelmouse
  pages/shared/data/faq.yaml
  pages/shared/data/tools.yaml
  pages/static/img/tools/rebelmouse.jpg
Labels: cla: yes

#3327 🚸 Do not enforce websites as default filter format and add filter hint
  frontend/scss/components/molecules/format-filter-hint.scss
  frontend/scss/components/organisms/header.scss
  frontend/templates/layouts/default.j2
  frontend/templates/views/detail/component-detail.j2
  frontend/templates/views/detail/docs-detail.j2
  frontend/templates/views/detail/guide-detail.j2
  frontend/templates/views/examples/documentation.j2
  frontend/templates/views/partials/format-filter-hint.j2
  platform/lib/amp/formatHelper.js
  platform/lib/templates/SupportedFormatsExtension.js
  platform/lib/templates/index.js
  platform/lib/utils/cssTransformer.js
Labels: cla: yes

#3388 cleaned up a lot of language, added links to AMP Conf videos…
  pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/publishing_checklist.md
Labels: cla: yes

#3411 Pull amp-bind doc from master
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools.md
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/ad-integration-guide.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
  pages/shared/data/blog.yaml
  pages/shared/data/recent-guides.yaml
  platform/lib/pipeline/componentReferenceImporter.js
Labels: cla: yes

#3418 📦 Update dependencies
  package-lock.json
  package.json
Labels: cla: yes

#3410 Add WompMobile to providers
  pages/shared/data/tools.yaml
  pages/static/img/tools/wompmobile-logo.png
Labels: cla: yes

#3422 fix potential xss via unescaped url string
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
  platform/lib/middleware/subdomain.js
  playground/backend/api.js
Labels: cla: yes

#3416 sampleBuilder: Do not mangle real sample path
  platform/lib/build/samplesBuilder.js
Labels: cla: yes

#3425 ✨ Allow SSR for tools page
  frontend/templates/views/partials/tools-teaser.j2
  pages/content/amp-dev/documentation/tools.html
  platform/lib/templates/index.js
Labels: cla: yes

#3432 🐛Fix not showing burger menu icon
  frontend/scss/components/organisms/burger-menu.scss
Labels: Category: UX, P0: Critical, Type: Bug, cla: yes

#3435 Update AMP Optimizer
  package-lock.json
  package.json
  platform/lib/utils/HeadDedupTransformer.test.js
Labels: cla: yes

#3436 ✨ Allow SSR for success-stories page
  pages/content/amp-dev/about/success-stories/index.html
Labels: cla: yes

#3437 💄 Fix margin for tools filter bubble
  frontend/scss/components/templates/tools.scss
  pages/content/amp-dev/documentation/tools.html
Labels: cla: yes

#3442 Update go.amp.dev/email-tools to use format filter
  platform/config/go-links.yaml
Labels: cla: yes

#3445 Remove formats from Restrict Duplicate Selection
  examples/source/interactivity-dynamic-content/Restrict_Duplicate_Selection.html
Labels: cla: yes

#3423 Add a visualization explaining the release schedule
  frontend/scss/components/organisms/release-schedule-accessible.scss
  frontend/scss/components/organisms/release-schedule.scss
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule-accessible.html
  pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
Labels: cla: yes

#3447 ✨ Prevent needless redirects
  platform/config/amp-dev-redirects.yaml
  platform/config/go-links.yaml
Labels: cla: yes

#3449 add /pr/ and /issue/ go links
  platform/config/go-links.yaml
Labels: cla: yes

#3448 Better error message on wg import
  gulpfile.js/import.js
  pages/content/amp-dev/community/governance.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/a4a_spec.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
  pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
  pages/shared/data/blog.yaml
  pages/shared/data/recent-guides.yaml
Labels: cla: yes
